"""
Tests for Unit 17: Hook Enforcement.

Synthetic Data Assumptions:
- The hooks JSON produced by generate_hooks_json is parsed via json.loads and
  validated structurally against the HOOKS_JSON_SCHEMA and the behavioral
  contracts (PreToolUse/PostToolUse entries, handler shape, path prefix).
- Shell scripts produced by generate_*_sh functions are validated as strings
  containing the required structural elements described in the contracts.
- The stub sentinel strings for Python and R are taken verbatim from Unit 2
  LANGUAGE_REGISTRY contracts:
    Python: '__SVP_STUB__ = True  # DO NOT DELIVER -- stub file generated by SVP'
    R:      '# __SVP_STUB__ <- TRUE  # DO NOT DELIVER -- stub file generated by SVP'
- Pipeline stages "3", "4", "5" are the builder-script-protected stages.
- Stages "0", "1", "2" are NOT builder-script-protected.
- The write authorization hook reads pipeline_state.json for current stage.
- The monitoring reminder hook reads project_profile.json (NOT pipeline_state.json).
- Exit code 2 is the Claude Code hard-block convention for blocked operations.
- SVP_PLUGIN_ACTIVE environment variable value "1" enables bash commands;
  absent or any other value blocks them.
- The authorized_write_dirs for Python are ["src", "tests", "."] and for R
  are ["R", "tests/testthat", "."] per Unit 2 contracts.
- Infrastructure paths (.svp/, .claude/) are always writable per contract.
- pipeline_state.json is writable only by update_state.py.
- Toolchain (toolchain.json) and ruff.toml are permanently read-only.
- Profile (project_profile.json) is writable only during Stage 0
  project_profile and redo sub-stages.
- Oracle session rules: .svp/oracle_run_ledger.json is always writable
  during oracle sessions.
- Debug session rules: tests/regressions/, unit-specific dirs, and
  delivered_repo_path are writable.
- The Hard Stop Protocol message is referenced in builder script block output.
- Handler objects use {"type": "command", "command": "<path>"} format.
- Paths use ".claude/scripts/" prefix.
"""

import json

from hooks import (
    HOOKS_JSON_SCHEMA,
    generate_hooks_json,
    generate_monitoring_reminder_sh,
    generate_non_svp_protection_sh,
    generate_stub_sentinel_check_sh,
    generate_write_authorization_sh,
)

# ---------------------------------------------------------------------------
# HOOKS_JSON_SCHEMA tests
# ---------------------------------------------------------------------------


class TestHooksJsonSchema:
    """Tests for the HOOKS_JSON_SCHEMA constant."""

    def test_schema_is_a_dict(self):
        assert isinstance(HOOKS_JSON_SCHEMA, dict)

    def test_schema_is_not_empty(self):
        assert len(HOOKS_JSON_SCHEMA) > 0


# ---------------------------------------------------------------------------
# generate_hooks_json tests
# ---------------------------------------------------------------------------


class TestGenerateHooksJson:
    """Tests for generate_hooks_json behavioral contracts."""

    def test_returns_a_string(self):
        result = generate_hooks_json()
        assert isinstance(result, str)

    def test_produces_valid_json(self):
        result = generate_hooks_json()
        parsed = json.loads(result)
        assert isinstance(parsed, dict)

    def test_top_level_has_hooks_key(self):
        parsed = json.loads(generate_hooks_json())
        assert "hooks" in parsed

    def test_hooks_contains_pre_tool_use_key(self):
        parsed = json.loads(generate_hooks_json())
        assert "PreToolUse" in parsed["hooks"]

    def test_hooks_contains_post_tool_use_key(self):
        parsed = json.loads(generate_hooks_json())
        assert "PostToolUse" in parsed["hooks"]

    def test_pre_tool_use_is_a_list(self):
        parsed = json.loads(generate_hooks_json())
        assert isinstance(parsed["hooks"]["PreToolUse"], list)

    def test_post_tool_use_is_a_list(self):
        parsed = json.loads(generate_hooks_json())
        assert isinstance(parsed["hooks"]["PostToolUse"], list)

    def test_pre_tool_use_has_write_authorization_entry(self):
        """PreToolUse must have Write matcher -> write_authorization.sh."""
        parsed = json.loads(generate_hooks_json())
        entries = parsed["hooks"]["PreToolUse"]
        write_entries = [
            e
            for e in entries
            if "write_authorization" in str(e).lower()
            or "Write" in str(e.get("matcher", ""))
        ]
        # Find entry with Write matcher pointing to write_authorization.sh
        found = False
        for entry in entries:
            handler = entry.get("handler", entry)
            command_str = str(handler.get("command", ""))
            if "write_authorization" in command_str:
                found = True
                break
        assert found, (
            "PreToolUse must contain an entry with write_authorization.sh handler"
        )

    def test_pre_tool_use_has_non_svp_protection_entry(self):
        """PreToolUse must have Bash matcher -> non_svp_protection.sh."""
        parsed = json.loads(generate_hooks_json())
        entries = parsed["hooks"]["PreToolUse"]
        found = False
        for entry in entries:
            handler = entry.get("handler", entry)
            command_str = str(handler.get("command", ""))
            if "non_svp_protection" in command_str:
                found = True
                break
        assert found, (
            "PreToolUse must contain an entry with non_svp_protection.sh handler"
        )

    def test_post_tool_use_has_stub_sentinel_check_entry(self):
        """PostToolUse must have Write matcher -> stub_sentinel_check.sh."""
        parsed = json.loads(generate_hooks_json())
        entries = parsed["hooks"]["PostToolUse"]
        found = False
        for entry in entries:
            handler = entry.get("handler", entry)
            command_str = str(handler.get("command", ""))
            if "stub_sentinel_check" in command_str:
                found = True
                break
        assert found, (
            "PostToolUse must contain an entry with stub_sentinel_check.sh handler"
        )

    def test_post_tool_use_has_monitoring_reminder_entry(self):
        """PostToolUse must have Agent matcher -> monitoring_reminder.sh."""
        parsed = json.loads(generate_hooks_json())
        entries = parsed["hooks"]["PostToolUse"]
        found = False
        for entry in entries:
            handler = entry.get("handler", entry)
            command_str = str(handler.get("command", ""))
            if "monitoring_reminder" in command_str:
                found = True
                break
        assert found, (
            "PostToolUse must contain an entry with monitoring_reminder.sh handler"
        )

    def test_all_handlers_use_type_command_not_bash(self):
        """Each handler must use type: 'command', not type: 'bash'."""
        parsed = json.loads(generate_hooks_json())
        for hook_type in ["PreToolUse", "PostToolUse"]:
            for entry in parsed["hooks"][hook_type]:
                handler = entry.get("handler", entry)
                if "type" in handler:
                    assert handler["type"] == "command", (
                        f"Handler type must be 'command', got '{handler['type']}'"
                    )
                    assert handler["type"] != "bash"

    def test_no_handler_uses_script_field(self):
        """Handlers must NOT use a 'script' field."""
        parsed = json.loads(generate_hooks_json())
        for hook_type in ["PreToolUse", "PostToolUse"]:
            for entry in parsed["hooks"][hook_type]:
                handler = entry.get("handler", entry)
                assert "script" not in handler, "Handler must not use 'script' field"

    def test_all_handler_paths_use_claude_scripts_prefix(self):
        """All handler command paths must use .claude/scripts/ prefix."""
        parsed = json.loads(generate_hooks_json())
        for hook_type in ["PreToolUse", "PostToolUse"]:
            for entry in parsed["hooks"][hook_type]:
                handler = entry.get("handler", entry)
                if "command" in handler:
                    assert ".claude/scripts/" in handler["command"], (
                        f"Handler path must use .claude/scripts/ prefix, "
                        f"got: {handler['command']}"
                    )

    def test_handlers_have_command_field(self):
        """Each handler object must have a 'command' field."""
        parsed = json.loads(generate_hooks_json())
        for hook_type in ["PreToolUse", "PostToolUse"]:
            for entry in parsed["hooks"][hook_type]:
                handler = entry.get("handler", entry)
                if "type" in handler:
                    assert "command" in handler, (
                        "Each handler with type must also have a command field"
                    )

    def test_handler_fields_not_on_matcher_object(self):
        """Handler fields (type, command) must NOT appear on the matcher object itself
        when matcher and handler are separate."""
        parsed = json.loads(generate_hooks_json())
        for hook_type in ["PreToolUse", "PostToolUse"]:
            for entry in parsed["hooks"][hook_type]:
                # If entry has both a matcher and a handler, the matcher
                # must not have type/command
                if "matcher" in entry and "handler" in entry:
                    matcher = entry["matcher"]
                    if isinstance(matcher, dict):
                        assert (
                            "type" not in matcher or matcher.get("type") != "command"
                        ), "Matcher object must not have handler's type field"

    def test_schema_matches_hooks_structure(self):
        """The HOOKS_JSON_SCHEMA dict should describe the same structure
        as the output of generate_hooks_json."""
        # Schema must define hooks with PreToolUse and PostToolUse
        # We verify the schema is consistent with the output structure
        assert isinstance(HOOKS_JSON_SCHEMA, dict)
        parsed = json.loads(generate_hooks_json())
        # Both should agree on the top-level key
        assert "hooks" in parsed


# ---------------------------------------------------------------------------
# generate_write_authorization_sh tests
# ---------------------------------------------------------------------------


class TestGenerateWriteAuthorizationSh:
    """Tests for generate_write_authorization_sh behavioral contracts."""

    def test_returns_a_string(self):
        result = generate_write_authorization_sh()
        assert isinstance(result, str)

    def test_output_is_nonempty(self):
        result = generate_write_authorization_sh()
        assert len(result.strip()) > 0

    def test_output_looks_like_shell_script(self):
        """Script should start with a shebang or contain shell constructs."""
        result = generate_write_authorization_sh()
        # Should contain typical shell constructs
        assert (
            "#!/" in result or "if " in result or "exit" in result or "case " in result
        ), "Output does not look like a shell script"

    def test_reads_pipeline_state_json(self):
        """The script must read pipeline_state.json to get current stage."""
        result = generate_write_authorization_sh()
        assert "pipeline_state" in result, "Script must reference pipeline_state.json"

    def test_checks_pipeline_state_protection(self):
        """pipeline_state.json must be writable only by update_state.py."""
        result = generate_write_authorization_sh()
        assert "update_state" in result, (
            "Script must reference update_state.py for pipeline_state protection"
        )

    def test_checks_builder_script_protection_during_stages_3_to_5(self):
        """Builder scripts (.py in scripts/) must be read-only during Stages 3-5."""
        result = generate_write_authorization_sh()
        # Must reference scripts/ directory protection
        assert "scripts/" in result or "scripts" in result, (
            "Script must reference scripts/ directory for builder protection"
        )

    def test_hard_stop_protocol_message_in_builder_block(self):
        """Builder script block message must reference Hard Stop Protocol."""
        result = generate_write_authorization_sh()
        assert (
            "Hard Stop" in result
            or "hard stop" in result.lower()
            or "Hard Stop Protocol" in result
        ), "Builder script block must reference Hard Stop Protocol"

    def test_builder_block_message_mentions_stages_3_5(self):
        """Builder script block message must mention Stages 3-5."""
        result = generate_write_authorization_sh()
        assert "3-5" in result or ("3" in result and "5" in result), (
            "Builder script block message should reference Stages 3-5"
        )

    def test_builder_block_message_mentions_svp_bug(self):
        """Builder script block message should mention /svp:bug for fix workflow."""
        result = generate_write_authorization_sh()
        assert "svp:bug" in result or "/svp:bug" in result, (
            "Builder script block should mention /svp:bug"
        )

    def test_exit_code_2_for_blocked_writes(self):
        """Script must use exit code 2 for blocked writes (Claude Code convention)."""
        result = generate_write_authorization_sh()
        assert "exit 2" in result, "Script must use 'exit 2' for blocked writes"

    def test_toolchain_permanently_read_only(self):
        """Toolchain file must be permanently read-only."""
        result = generate_write_authorization_sh()
        assert "toolchain" in result.lower(), (
            "Script must reference toolchain for read-only protection"
        )

    def test_ruff_toml_permanently_read_only(self):
        """ruff.toml must be permanently read-only."""
        result = generate_write_authorization_sh()
        assert "ruff.toml" in result, (
            "Script must reference ruff.toml for read-only protection"
        )

    def test_profile_writable_conditions(self):
        """Profile must be writable during Stage 0 project_profile and redo sub-stages."""
        result = generate_write_authorization_sh()
        # Must reference project_profile or profile for write conditions
        assert "project_profile" in result or "profile" in result, (
            "Script must reference profile writable conditions"
        )

    def test_oracle_session_ledger_writable(self):
        """oracle_run_ledger.json must be writable during oracle sessions."""
        result = generate_write_authorization_sh()
        assert "oracle_run_ledger" in result, (
            "Script must reference oracle_run_ledger.json for oracle session rules"
        )

    def test_debug_session_regression_dir_writable(self):
        """tests/regressions/ must be writable during debug sessions."""
        result = generate_write_authorization_sh()
        assert "regressions" in result or "tests/regressions" in result, (
            "Script must reference tests/regressions/ for debug session rules"
        )

    def test_references_authorized_write_dirs(self):
        """Script must use per-language authorized_write_dirs."""
        result = generate_write_authorization_sh()
        # Should reference the concept of authorized write directories
        # At minimum, "src" and "tests" should appear (Python authorized dirs)
        has_src = "src" in result
        has_tests = "tests" in result
        has_authorized = "authorized" in result.lower() or "write_dir" in result.lower()
        assert has_src or has_tests or has_authorized, (
            "Script must reference authorized write directories"
        )

    def test_hook_order_stage_read_first(self):
        """Hook order: (1) read stage first, before any path checks."""
        result = generate_write_authorization_sh()
        # The stage read should appear before the specific path checks
        stage_pos = result.find("stage")
        pipeline_state_pos = result.find("pipeline_state")
        # At minimum, pipeline_state must be referenced
        assert pipeline_state_pos >= 0, "Script must read pipeline_state.json"


# ---------------------------------------------------------------------------
# generate_non_svp_protection_sh tests
# ---------------------------------------------------------------------------


class TestGenerateNonSvpProtectionSh:
    """Tests for generate_non_svp_protection_sh behavioral contracts."""

    def test_returns_a_string(self):
        result = generate_non_svp_protection_sh()
        assert isinstance(result, str)

    def test_output_is_nonempty(self):
        result = generate_non_svp_protection_sh()
        assert len(result.strip()) > 0

    def test_output_looks_like_shell_script(self):
        result = generate_non_svp_protection_sh()
        assert "#!/" in result or "if " in result or "exit" in result, (
            "Output does not look like a shell script"
        )

    def test_checks_svp_plugin_active_env_var(self):
        """Must check SVP_PLUGIN_ACTIVE environment variable."""
        result = generate_non_svp_protection_sh()
        assert "SVP_PLUGIN_ACTIVE" in result, (
            "Script must check SVP_PLUGIN_ACTIVE environment variable"
        )

    def test_blocks_when_svp_plugin_active_not_set(self):
        """When SVP_PLUGIN_ACTIVE is not set, all bash commands are blocked."""
        result = generate_non_svp_protection_sh()
        # Should contain logic that blocks when env var is absent
        assert "exit 2" in result, "Script must use 'exit 2' for blocked commands"

    def test_blocks_when_svp_plugin_active_not_1(self):
        """When SVP_PLUGIN_ACTIVE is not '1', commands are blocked."""
        result = generate_non_svp_protection_sh()
        # The script must check for the value "1"
        assert (
            '"1"' in result
            or "'1'" in result
            or "= 1" in result
            or "!= 1" in result
            or '=="1"' in result
            or "eq 1" in result
        ), "Script must compare SVP_PLUGIN_ACTIVE against '1'"

    def test_prints_readme_message_when_blocked(self):
        """When blocked, must print a README-style message."""
        result = generate_non_svp_protection_sh()
        # Should contain some user-facing message
        has_message = "echo" in result or "printf" in result or "cat" in result
        assert has_message, "Script must print a message when blocking commands"

    def test_exit_code_2_for_blocked_commands(self):
        """Exit code 2 for blocked commands (Claude Code convention)."""
        result = generate_non_svp_protection_sh()
        assert "exit 2" in result


# ---------------------------------------------------------------------------
# generate_stub_sentinel_check_sh tests
# ---------------------------------------------------------------------------


class TestGenerateStubSentinelCheckSh:
    """Tests for generate_stub_sentinel_check_sh behavioral contracts."""

    def test_returns_a_string(self):
        result = generate_stub_sentinel_check_sh()
        assert isinstance(result, str)

    def test_output_is_nonempty(self):
        result = generate_stub_sentinel_check_sh()
        assert len(result.strip()) > 0

    def test_output_looks_like_shell_script(self):
        result = generate_stub_sentinel_check_sh()
        assert (
            "#!/" in result
            or "if " in result
            or "exit" in result
            or "grep" in result.lower()
        ), "Output does not look like a shell script"

    def test_greps_for_stub_sentinel(self):
        """Must grep written file for stub sentinel."""
        result = generate_stub_sentinel_check_sh()
        # Should contain grep or similar search mechanism
        assert (
            "grep" in result.lower() or "SVP_STUB" in result or "stub" in result.lower()
        ), "Script must search for stub sentinel in written files"

    def test_references_svp_stub_sentinel_string(self):
        """Must reference the stub sentinel marker."""
        result = generate_stub_sentinel_check_sh()
        assert "__SVP_STUB__" in result or "SVP_STUB" in result, (
            "Script must reference the SVP stub sentinel string"
        )

    def test_exit_code_2_when_sentinel_found(self):
        """Exit code 2 when stub sentinel is found in written file."""
        result = generate_stub_sentinel_check_sh()
        assert "exit 2" in result, (
            "Script must use 'exit 2' when stub sentinel is found"
        )

    def test_message_directs_agent_to_implement(self):
        """When sentinel found, message must direct agent to implement, not copy stub."""
        result = generate_stub_sentinel_check_sh()
        has_implement_msg = (
            "implement" in result.lower()
            or "stub" in result.lower()
            or "copy" in result.lower()
            or "deliver" in result.lower()
        )
        assert has_implement_msg, (
            "Script must contain a message directing agent to implement, "
            "not copy the stub"
        )

    def test_fires_on_post_tool_use_write(self):
        """This is a PostToolUse hook -- it validates content after write.
        The script should process the file that was written."""
        result = generate_stub_sentinel_check_sh()
        # Script should reference the file path (typically from arguments or env)
        assert len(result.strip()) > 0, (
            "Script must have content for post-write validation"
        )


# ---------------------------------------------------------------------------
# generate_monitoring_reminder_sh tests
# ---------------------------------------------------------------------------


class TestGenerateMonitoringReminderSh:
    """Tests for generate_monitoring_reminder_sh behavioral contracts."""

    def test_returns_a_string(self):
        result = generate_monitoring_reminder_sh()
        assert isinstance(result, str)

    def test_output_is_nonempty(self):
        result = generate_monitoring_reminder_sh()
        assert len(result.strip()) > 0

    def test_output_looks_like_shell_script(self):
        result = generate_monitoring_reminder_sh()
        assert "#!/" in result or "if " in result or "exit" in result, (
            "Output does not look like a shell script"
        )

    def test_reads_project_profile_json_not_pipeline_state(self):
        """Must read project_profile.json, NOT pipeline_state.json."""
        result = generate_monitoring_reminder_sh()
        assert "project_profile" in result, "Script must read project_profile.json"

    def test_does_not_read_pipeline_state_json(self):
        """Monitoring reminder must NOT read pipeline_state.json for its decision logic.
        It only reads project_profile.json."""
        result = generate_monitoring_reminder_sh()
        # The script should not reference pipeline_state for the is_svp_build check
        # Note: it is acceptable if pipeline_state appears in a comment, but the
        # functional logic should use project_profile
        # We check the core logic does reference project_profile
        assert "project_profile" in result, (
            "Script must use project_profile.json for is_svp_build check"
        )

    def test_checks_is_svp_build_field(self):
        """Must check is_svp_build field in project_profile.json."""
        result = generate_monitoring_reminder_sh()
        assert "is_svp_build" in result, "Script must check is_svp_build field"

    def test_outputs_monitoring_reminder_when_is_svp_build_true(self):
        """When is_svp_build is true, outputs monitoring reminder."""
        result = generate_monitoring_reminder_sh()
        # The script should contain the reminder text about verifying subagent output
        has_reminder_content = (
            "monitor" in result.lower()
            or "verify" in result.lower()
            or "subagent" in result.lower()
            or "spec" in result.lower()
            or "reminder" in result.lower()
        )
        assert has_reminder_content, (
            "Script must contain monitoring reminder output for svp builds"
        )

    def test_no_op_exit_0_when_is_svp_build_false(self):
        """When is_svp_build is false or absent, exit 0 with no output."""
        result = generate_monitoring_reminder_sh()
        assert "exit 0" in result, (
            "Script must exit 0 (no-op) when is_svp_build is false"
        )

    def test_handles_absent_is_svp_build_field(self):
        """When is_svp_build field is absent, treat as false (no-op exit 0)."""
        result = generate_monitoring_reminder_sh()
        # The script should handle the case where the field doesn't exist
        # This is implicitly covered by exit 0 for non-true cases
        assert "exit 0" in result

    def test_reminder_mentions_orchestrator_verification(self):
        """The monitoring reminder should instruct the orchestrator to verify
        subagent output against the spec before proceeding."""
        result = generate_monitoring_reminder_sh()
        has_verification_instruction = (
            "verify" in result.lower()
            or "check" in result.lower()
            or "spec" in result.lower()
            or "before proceeding" in result.lower()
            or "orchestrator" in result.lower()
        )
        assert has_verification_instruction, (
            "Monitoring reminder must instruct orchestrator to verify "
            "subagent output against spec"
        )


# ---------------------------------------------------------------------------
# Cross-function integration tests
# ---------------------------------------------------------------------------


class TestHooksJsonIntegrationWithScripts:
    """Tests verifying consistency between hooks.json and the shell scripts."""

    def test_hooks_json_references_write_authorization_sh_filename(self):
        """hooks.json must reference write_authorization.sh by name."""
        parsed = json.loads(generate_hooks_json())
        all_commands = []
        for hook_type in ["PreToolUse", "PostToolUse"]:
            for entry in parsed["hooks"][hook_type]:
                handler = entry.get("handler", entry)
                if "command" in handler:
                    all_commands.append(handler["command"])
        matching = [c for c in all_commands if "write_authorization" in c]
        assert len(matching) >= 1

    def test_hooks_json_references_non_svp_protection_sh_filename(self):
        """hooks.json must reference non_svp_protection.sh by name."""
        parsed = json.loads(generate_hooks_json())
        all_commands = []
        for hook_type in ["PreToolUse", "PostToolUse"]:
            for entry in parsed["hooks"][hook_type]:
                handler = entry.get("handler", entry)
                if "command" in handler:
                    all_commands.append(handler["command"])
        matching = [c for c in all_commands if "non_svp_protection" in c]
        assert len(matching) >= 1

    def test_hooks_json_references_stub_sentinel_check_sh_filename(self):
        """hooks.json must reference stub_sentinel_check.sh by name."""
        parsed = json.loads(generate_hooks_json())
        all_commands = []
        for hook_type in ["PreToolUse", "PostToolUse"]:
            for entry in parsed["hooks"][hook_type]:
                handler = entry.get("handler", entry)
                if "command" in handler:
                    all_commands.append(handler["command"])
        matching = [c for c in all_commands if "stub_sentinel_check" in c]
        assert len(matching) >= 1

    def test_hooks_json_references_monitoring_reminder_sh_filename(self):
        """hooks.json must reference monitoring_reminder.sh by name."""
        parsed = json.loads(generate_hooks_json())
        all_commands = []
        for hook_type in ["PreToolUse", "PostToolUse"]:
            for entry in parsed["hooks"][hook_type]:
                handler = entry.get("handler", entry)
                if "command" in handler:
                    all_commands.append(handler["command"])
        matching = [c for c in all_commands if "monitoring_reminder" in c]
        assert len(matching) >= 1

    def test_write_authorization_is_pre_tool_use_not_post(self):
        """write_authorization.sh must be in PreToolUse, not PostToolUse."""
        parsed = json.loads(generate_hooks_json())
        pre_commands = []
        for entry in parsed["hooks"]["PreToolUse"]:
            handler = entry.get("handler", entry)
            if "command" in handler:
                pre_commands.append(handler["command"])
        post_commands = []
        for entry in parsed["hooks"]["PostToolUse"]:
            handler = entry.get("handler", entry)
            if "command" in handler:
                post_commands.append(handler["command"])
        assert any("write_authorization" in c for c in pre_commands), (
            "write_authorization must be in PreToolUse"
        )

    def test_non_svp_protection_is_pre_tool_use(self):
        """non_svp_protection.sh must be in PreToolUse."""
        parsed = json.loads(generate_hooks_json())
        pre_commands = []
        for entry in parsed["hooks"]["PreToolUse"]:
            handler = entry.get("handler", entry)
            if "command" in handler:
                pre_commands.append(handler["command"])
        assert any("non_svp_protection" in c for c in pre_commands)

    def test_stub_sentinel_check_is_post_tool_use(self):
        """stub_sentinel_check.sh must be in PostToolUse."""
        parsed = json.loads(generate_hooks_json())
        post_commands = []
        for entry in parsed["hooks"]["PostToolUse"]:
            handler = entry.get("handler", entry)
            if "command" in handler:
                post_commands.append(handler["command"])
        assert any("stub_sentinel_check" in c for c in post_commands)

    def test_monitoring_reminder_is_post_tool_use(self):
        """monitoring_reminder.sh must be in PostToolUse."""
        parsed = json.loads(generate_hooks_json())
        post_commands = []
        for entry in parsed["hooks"]["PostToolUse"]:
            handler = entry.get("handler", entry)
            if "command" in handler:
                post_commands.append(handler["command"])
        assert any("monitoring_reminder" in c for c in post_commands)

    def test_all_four_scripts_are_referenced_in_hooks(self):
        """All four shell scripts must appear somewhere in hooks.json."""
        parsed = json.loads(generate_hooks_json())
        all_commands = []
        for hook_type in ["PreToolUse", "PostToolUse"]:
            for entry in parsed["hooks"][hook_type]:
                handler = entry.get("handler", entry)
                if "command" in handler:
                    all_commands.append(handler["command"])
        all_text = " ".join(all_commands)
        assert "write_authorization" in all_text
        assert "non_svp_protection" in all_text
        assert "stub_sentinel_check" in all_text
        assert "monitoring_reminder" in all_text


# ---------------------------------------------------------------------------
# Structural invariant tests
# ---------------------------------------------------------------------------


class TestStructuralInvariants:
    """Tests for structural invariants across all generated outputs."""

    def test_hooks_json_only_has_hooks_key_at_top_level(self):
        """Top-level JSON should have 'hooks' key (schema conformance)."""
        parsed = json.loads(generate_hooks_json())
        assert "hooks" in parsed

    def test_hooks_json_only_contains_pre_and_post_tool_use(self):
        """hooks dict should only contain PreToolUse and PostToolUse."""
        parsed = json.loads(generate_hooks_json())
        hook_keys = set(parsed["hooks"].keys())
        assert "PreToolUse" in hook_keys
        assert "PostToolUse" in hook_keys

    def test_pre_tool_use_has_at_least_two_entries(self):
        """PreToolUse must have at least 2 entries (Write and Bash matchers)."""
        parsed = json.loads(generate_hooks_json())
        assert len(parsed["hooks"]["PreToolUse"]) >= 2

    def test_post_tool_use_has_at_least_two_entries(self):
        """PostToolUse must have at least 2 entries (Write and Agent matchers)."""
        parsed = json.loads(generate_hooks_json())
        assert len(parsed["hooks"]["PostToolUse"]) >= 2

    def test_write_authorization_script_contains_exit_2(self):
        """write_authorization.sh must have exit 2 for blocks."""
        result = generate_write_authorization_sh()
        assert "exit 2" in result

    def test_non_svp_protection_script_contains_exit_2(self):
        """non_svp_protection.sh must have exit 2 for blocks."""
        result = generate_non_svp_protection_sh()
        assert "exit 2" in result

    def test_stub_sentinel_check_script_contains_exit_2(self):
        """stub_sentinel_check.sh must have exit 2 for blocks."""
        result = generate_stub_sentinel_check_sh()
        assert "exit 2" in result

    def test_monitoring_reminder_script_contains_exit_0(self):
        """monitoring_reminder.sh must have exit 0 for no-op case."""
        result = generate_monitoring_reminder_sh()
        assert "exit 0" in result

    def test_write_authorization_references_update_state_py(self):
        """pipeline_state.json writable only by update_state.py."""
        result = generate_write_authorization_sh()
        assert "update_state" in result

    def test_write_authorization_references_toolchain_read_only(self):
        """Toolchain is permanently read-only."""
        result = generate_write_authorization_sh()
        assert "toolchain" in result.lower()

    def test_write_authorization_references_ruff_toml_read_only(self):
        """ruff.toml is permanently read-only."""
        result = generate_write_authorization_sh()
        assert "ruff.toml" in result

    def test_write_authorization_handles_debug_session(self):
        """Debug session must enable writable paths for regressions and unit dirs."""
        result = generate_write_authorization_sh()
        assert "debug" in result.lower() or "regressions" in result

    def test_write_authorization_handles_oracle_session(self):
        """Oracle session must enable oracle_run_ledger.json writes."""
        result = generate_write_authorization_sh()
        assert "oracle" in result.lower()

    def test_stub_sentinel_check_references_python_sentinel(self):
        """Should handle Python stub sentinel __SVP_STUB__."""
        result = generate_stub_sentinel_check_sh()
        assert "__SVP_STUB__" in result

    def test_non_svp_protection_checks_env_var_value_1(self):
        """Must specifically check for value '1'."""
        result = generate_non_svp_protection_sh()
        assert "1" in result

    def test_monitoring_reminder_checks_project_profile(self):
        """Must read project_profile.json for is_svp_build."""
        result = generate_monitoring_reminder_sh()
        assert "project_profile" in result
        assert "is_svp_build" in result


# ---------------------------------------------------------------------------
# Write authorization detailed path rule tests
# ---------------------------------------------------------------------------


class TestWriteAuthorizationPathRules:
    """Detailed tests for path-specific rules in write_authorization.sh."""

    def test_infrastructure_paths_always_writable(self):
        """Infrastructure paths (.svp/, .claude/) should always be writable."""
        result = generate_write_authorization_sh()
        # The script should allow writes to .svp/ and .claude/ infrastructure dirs
        has_svp_ref = ".svp" in result
        has_claude_ref = ".claude" in result
        assert has_svp_ref or has_claude_ref, (
            "Script must handle infrastructure path writability (.svp/, .claude/)"
        )

    def test_profile_stage_0_writability(self):
        """Profile writable during Stage 0 project_profile sub-stage."""
        result = generate_write_authorization_sh()
        # Must check for stage 0 / project_profile condition
        has_stage_0 = (
            '"0"' in result
            or "'0'" in result
            or "stage_0" in result
            or "== 0" in result
        )
        has_profile_ref = "profile" in result.lower()
        assert has_stage_0 or has_profile_ref, (
            "Script must handle Stage 0 profile writability"
        )

    def test_profile_redo_writability(self):
        """Profile writable during redo sub-stages."""
        result = generate_write_authorization_sh()
        assert "redo" in result.lower(), (
            "Script must handle redo sub-stage profile writability"
        )

    def test_delivered_repo_path_writable_in_debug(self):
        """delivered_repo_path must be writable during debug sessions."""
        result = generate_write_authorization_sh()
        has_delivered = "delivered" in result.lower() or "repo_path" in result.lower()
        has_debug = "debug" in result.lower()
        assert has_debug, "Script must handle debug session path rules"
