"""
Tests for Unit 10: Stub Generator Dispatch.

Synthetic Data Assumptions:
- Valid Python source for stub generation: a module with imports, a constant,
  a function, and a class. The AST from ast.parse is used as parsed_signatures.
- Valid R source for stub generation: standard R function assignments using '<-'.
- Python language_config includes keys: id, display_name, file_extension,
  stub_sentinel, stub_generator_key, is_component_only (False).
- R language_config includes keys: id, display_name, file_extension,
  stub_sentinel, stub_generator_key, is_component_only (False).
- Stan language_config includes keys: id, display_name, file_extension,
  stub_generator_key ("stan_template"), is_component_only (True).
- Plugin language configs include stub_generator_key matching one of
  "plugin_markdown", "plugin_bash", "plugin_json" and is_component_only True.
- The Python stub sentinel is:
  '__SVP_STUB__ = True  # DO NOT DELIVER -- stub file generated by SVP'
- The R stub sentinel is:
  '# __SVP_STUB__ <- TRUE  # DO NOT DELIVER -- stub file generated by SVP'
- For upstream stub generation, blueprint_dir contains blueprint_contracts.md
  with properly formatted ## Unit N: headings, ### Tier 2 subheadings, and
  fenced code blocks.
- Forward references are upstream units with higher unit numbers than the
  current unit, which must raise ValueError.
- CLI arguments follow the pattern: --blueprint, --unit, --output-dir, --upstream.
- The --language argument is also accepted by main.
- An empty string for --upstream means no dependencies.
"""

import ast
import textwrap

import pytest

from stub_generator import (
    STUB_GENERATORS,
    generate_stub,
    generate_upstream_stubs,
    main,
)

# ---------------------------------------------------------------------------
# Synthetic test data
# ---------------------------------------------------------------------------

VALID_PYTHON_SOURCE = textwrap.dedent("""\
    from typing import Optional

    MY_CONST: int

    def greet(name: str) -> str: ...

    def add(a: int, b: int) -> int: ...

    class Greeter:
        value: int
        def hello(self) -> str: ...
""")

VALID_R_SOURCE = textwrap.dedent("""\
    greet <- function(name) {
        paste("Hello,", name)
    }

    add <- function(a, b) {
        a + b
    }
""")

PYTHON_SENTINEL = "__SVP_STUB__ = True  # DO NOT DELIVER -- stub file generated by SVP"

R_SENTINEL = "# __SVP_STUB__ <- TRUE  # DO NOT DELIVER -- stub file generated by SVP"

PYTHON_LANGUAGE_CONFIG = {
    "id": "python",
    "display_name": "Python",
    "file_extension": ".py",
    "stub_sentinel": PYTHON_SENTINEL,
    "stub_generator_key": "python",
    "is_component_only": False,
}

R_LANGUAGE_CONFIG = {
    "id": "r",
    "display_name": "R",
    "file_extension": ".R",
    "stub_sentinel": R_SENTINEL,
    "stub_generator_key": "r",
    "is_component_only": False,
}

STAN_LANGUAGE_CONFIG = {
    "id": "stan",
    "display_name": "Stan",
    "file_extension": ".stan",
    "stub_generator_key": "stan_template",
    "is_component_only": True,
}

PLUGIN_MARKDOWN_CONFIG = {
    "id": "plugin_markdown",
    "display_name": "Markdown Plugin",
    "file_extension": ".md",
    "stub_generator_key": "plugin_markdown",
    "is_component_only": True,
}

PLUGIN_BASH_CONFIG = {
    "id": "plugin_bash",
    "display_name": "Bash Plugin",
    "file_extension": ".sh",
    "stub_generator_key": "plugin_bash",
    "is_component_only": True,
}

PLUGIN_JSON_CONFIG = {
    "id": "plugin_json",
    "display_name": "JSON Plugin",
    "file_extension": ".json",
    "stub_generator_key": "plugin_json",
    "is_component_only": True,
}


# ---------------------------------------------------------------------------
# STUB_GENERATORS dispatch table tests
# ---------------------------------------------------------------------------


class TestStubGeneratorsDispatchTable:
    """Tests for the STUB_GENERATORS module-level dispatch table."""

    def test_stub_generators_is_a_dict(self):
        assert isinstance(STUB_GENERATORS, dict)

    def test_stub_generators_contains_python_key(self):
        assert "python" in STUB_GENERATORS

    def test_stub_generators_contains_r_key(self):
        assert "r" in STUB_GENERATORS

    def test_stub_generators_contains_stan_template_key(self):
        assert "stan_template" in STUB_GENERATORS

    def test_stub_generators_contains_plugin_markdown_key(self):
        assert "plugin_markdown" in STUB_GENERATORS

    def test_stub_generators_contains_plugin_bash_key(self):
        assert "plugin_bash" in STUB_GENERATORS

    def test_stub_generators_contains_plugin_json_key(self):
        assert "plugin_json" in STUB_GENERATORS

    def test_stub_generators_has_exactly_six_keys(self):
        expected_keys = {
            "python",
            "r",
            "stan_template",
            "plugin_markdown",
            "plugin_bash",
            "plugin_json",
        }
        assert set(STUB_GENERATORS.keys()) == expected_keys

    def test_stub_generators_values_are_callable(self):
        for key, generator in STUB_GENERATORS.items():
            assert callable(generator), f"STUB_GENERATORS[{key!r}] is not callable"


# ---------------------------------------------------------------------------
# Python stub generation tests
# ---------------------------------------------------------------------------


class TestPythonStubGeneration:
    """Tests for Python stub generation via generate_stub."""

    def test_python_stub_returns_string(self):
        parsed = ast.parse(VALID_PYTHON_SOURCE)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        assert isinstance(result, str)

    def test_python_stub_contains_sentinel_as_first_non_import_statement(self):
        parsed = ast.parse(VALID_PYTHON_SOURCE)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        assert PYTHON_SENTINEL in result

    def test_python_stub_sentinel_appears_before_function_definitions(self):
        parsed = ast.parse(VALID_PYTHON_SOURCE)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        sentinel_pos = result.index(PYTHON_SENTINEL)
        # At minimum, a def keyword should appear after the sentinel
        assert "def " in result
        first_def_pos = result.index("def ")
        assert sentinel_pos < first_def_pos

    def test_python_stub_function_bodies_raise_not_implemented_error(self):
        parsed = ast.parse(VALID_PYTHON_SOURCE)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        assert "raise NotImplementedError()" in result

    def test_python_stub_is_valid_python(self):
        parsed = ast.parse(VALID_PYTHON_SOURCE)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        # Must parse without SyntaxError
        ast.parse(result)

    def test_python_stub_preserves_function_signatures(self):
        parsed = ast.parse(VALID_PYTHON_SOURCE)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        assert "def greet(" in result
        assert "def add(" in result

    def test_python_stub_preserves_class_definition(self):
        parsed = ast.parse(VALID_PYTHON_SOURCE)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        assert "class Greeter" in result

    def test_python_stub_class_methods_raise_not_implemented_error(self):
        parsed = ast.parse(VALID_PYTHON_SOURCE)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        # Parse the generated stub and check class method bodies
        tree = ast.parse(result)
        class_found = False
        for node in ast.walk(tree):
            if isinstance(node, ast.ClassDef) and node.name == "Greeter":
                class_found = True
                for item in node.body:
                    if isinstance(item, ast.FunctionDef):
                        # Check that the method body raises NotImplementedError
                        assert any(isinstance(stmt, ast.Raise) for stmt in item.body), (
                            f"Method {item.name} does not raise NotImplementedError"
                        )
        assert class_found, "Class Greeter not found in stub"

    def test_python_stub_class_level_attributes_set_to_none(self):
        parsed = ast.parse(VALID_PYTHON_SOURCE)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        tree = ast.parse(result)
        for node in ast.walk(tree):
            if isinstance(node, ast.ClassDef) and node.name == "Greeter":
                for item in node.body:
                    if isinstance(item, (ast.AnnAssign, ast.Assign)):
                        # Class-level attributes should be set to None
                        if isinstance(item, ast.AnnAssign):
                            assert item.value is not None, (
                                "Annotated attribute should have a value"
                            )
                            assert isinstance(item.value, ast.Constant)
                            assert item.value.value is None

    def test_python_stub_strips_module_level_assert_statements(self):
        source_with_assert = textwrap.dedent("""\
            def foo() -> int: ...

            assert True, "invariant check"

            def bar() -> int: ...
        """)
        parsed = ast.parse(source_with_assert)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        tree = ast.parse(result)
        # No top-level assert statements should remain
        for node in tree.body:
            assert not isinstance(node, ast.Assert), (
                "Module-level assert was not stripped from stub"
            )

    def test_python_stub_preserves_import_statements(self):
        parsed = ast.parse(VALID_PYTHON_SOURCE)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        assert "from typing import Optional" in result


# ---------------------------------------------------------------------------
# R stub generation tests
# ---------------------------------------------------------------------------


class TestRStubGeneration:
    """Tests for R stub generation via generate_stub."""

    def test_r_stub_returns_string(self):
        # For R, parsed_signatures would come from Unit 9's R parser
        # We use a mock parsed result (structured list of function definitions)
        r_parsed = [
            {"name": "greet", "params": ["name"]},
            {"name": "add", "params": ["a", "b"]},
        ]
        result = generate_stub(r_parsed, "r", R_LANGUAGE_CONFIG)
        assert isinstance(result, str)

    def test_r_stub_contains_sentinel_comment(self):
        r_parsed = [
            {"name": "greet", "params": ["name"]},
        ]
        result = generate_stub(r_parsed, "r", R_LANGUAGE_CONFIG)
        assert R_SENTINEL in result

    def test_r_stub_sentinel_is_prepended(self):
        r_parsed = [
            {"name": "greet", "params": ["name"]},
        ]
        result = generate_stub(r_parsed, "r", R_LANGUAGE_CONFIG)
        # Sentinel should appear near the top
        lines = result.strip().split("\n")
        sentinel_found = False
        for line in lines:
            if R_SENTINEL in line:
                sentinel_found = True
                break
        assert sentinel_found

    def test_r_stub_function_bodies_contain_stop_not_implemented(self):
        r_parsed = [
            {"name": "greet", "params": ["name"]},
        ]
        result = generate_stub(r_parsed, "r", R_LANGUAGE_CONFIG)
        assert 'stop("Not implemented")' in result

    def test_r_stub_contains_function_name(self):
        r_parsed = [
            {"name": "greet", "params": ["name"]},
            {"name": "add", "params": ["a", "b"]},
        ]
        result = generate_stub(r_parsed, "r", R_LANGUAGE_CONFIG)
        assert "greet" in result
        assert "add" in result


# ---------------------------------------------------------------------------
# Stan template stub generation tests
# ---------------------------------------------------------------------------


class TestStanTemplateStubGeneration:
    """Tests for Stan template stub generation."""

    def test_stan_stub_returns_string(self):
        result = generate_stub(None, "stan", STAN_LANGUAGE_CONFIG)
        assert isinstance(result, str)

    def test_stan_stub_receives_none_as_parsed_signatures(self):
        # Stan bypasses signature parsing; parsed_signatures is None
        result = generate_stub(None, "stan", STAN_LANGUAGE_CONFIG)
        assert isinstance(result, str)
        assert len(result) > 0

    def test_stan_stub_contains_sentinel_comment(self):
        result = generate_stub(None, "stan", STAN_LANGUAGE_CONFIG)
        # Stan stub should contain some sentinel/marker comment
        assert (
            "//" in result
            or "/*" in result
            or "SVP" in result.upper()
            or "stub" in result.lower()
        )

    def test_stan_stub_is_minimal_stan_model_template(self):
        result = generate_stub(None, "stan", STAN_LANGUAGE_CONFIG)
        # A minimal Stan model has at minimum some structural content
        assert len(result.strip()) > 0


# ---------------------------------------------------------------------------
# Plugin stub generation tests
# ---------------------------------------------------------------------------


class TestPluginMarkdownStubGeneration:
    """Tests for plugin_markdown stub generation."""

    def test_plugin_markdown_stub_returns_string(self):
        result = generate_stub(None, "plugin_markdown", PLUGIN_MARKDOWN_CONFIG)
        assert isinstance(result, str)

    def test_plugin_markdown_stub_bypasses_signature_parsing(self):
        # parsed_signatures is None for plugins
        result = generate_stub(None, "plugin_markdown", PLUGIN_MARKDOWN_CONFIG)
        assert len(result.strip()) > 0

    def test_plugin_markdown_stub_produces_valid_markdown(self):
        result = generate_stub(None, "plugin_markdown", PLUGIN_MARKDOWN_CONFIG)
        # Minimal valid markdown is any non-empty string
        assert isinstance(result, str)
        assert len(result.strip()) > 0


class TestPluginBashStubGeneration:
    """Tests for plugin_bash stub generation."""

    def test_plugin_bash_stub_returns_string(self):
        result = generate_stub(None, "plugin_bash", PLUGIN_BASH_CONFIG)
        assert isinstance(result, str)

    def test_plugin_bash_stub_bypasses_signature_parsing(self):
        result = generate_stub(None, "plugin_bash", PLUGIN_BASH_CONFIG)
        assert len(result.strip()) > 0


class TestPluginJsonStubGeneration:
    """Tests for plugin_json stub generation."""

    def test_plugin_json_stub_returns_string(self):
        result = generate_stub(None, "plugin_json", PLUGIN_JSON_CONFIG)
        assert isinstance(result, str)

    def test_plugin_json_stub_bypasses_signature_parsing(self):
        result = generate_stub(None, "plugin_json", PLUGIN_JSON_CONFIG)
        assert len(result.strip()) > 0


# ---------------------------------------------------------------------------
# generate_stub dispatch tests
# ---------------------------------------------------------------------------


class TestGenerateStubDispatch:
    """Tests for generate_stub dispatch behavior."""

    def test_dispatches_via_stub_generator_key_in_language_config(self):
        """generate_stub dispatches to STUB_GENERATORS[language_config['stub_generator_key']]."""
        parsed = ast.parse(VALID_PYTHON_SOURCE)
        # Should not raise -- dispatches to the "python" generator
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        assert isinstance(result, str)

    def test_dispatch_key_mismatch_raises_error(self):
        """If the stub_generator_key is not in STUB_GENERATORS, should raise."""
        bad_config = {
            "stub_generator_key": "nonexistent_language",
            "is_component_only": False,
        }
        with pytest.raises((KeyError, ValueError)):
            generate_stub(None, "nonexistent", bad_config)

    def test_plugin_types_receive_none_parsed_signatures(self):
        """Plugin dispatch keys bypass signature parsing and receive None."""
        # All plugin types should work with None
        for config in [PLUGIN_MARKDOWN_CONFIG, PLUGIN_BASH_CONFIG, PLUGIN_JSON_CONFIG]:
            result = generate_stub(None, config["id"], config)
            assert isinstance(result, str)

    def test_stan_template_receives_none_parsed_signatures(self):
        """Component languages like Stan bypass signature parsing."""
        result = generate_stub(None, "stan", STAN_LANGUAGE_CONFIG)
        assert isinstance(result, str)

    def test_python_stub_is_importable_without_error(self):
        """Returned stub is importable/valid without error in the target artifact type."""
        parsed = ast.parse(VALID_PYTHON_SOURCE)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        # Compiling should succeed (validates it is importable Python)
        compile(result, "<stub>", "exec")


# ---------------------------------------------------------------------------
# generate_upstream_stubs tests
# ---------------------------------------------------------------------------


class TestGenerateUpstreamStubs:
    """Tests for generate_upstream_stubs behavior."""

    def test_raises_value_error_on_forward_reference(self, tmp_path):
        """Forward-reference guard: upstream unit number >= unit_number raises ValueError."""
        blueprint_dir = tmp_path / "blueprint"
        blueprint_dir.mkdir()
        output_dir = tmp_path / "output"
        output_dir.mkdir()

        # Unit 5 with upstream unit 10 is a forward reference
        with pytest.raises(ValueError):
            generate_upstream_stubs(
                blueprint_dir=blueprint_dir,
                unit_number=5,
                upstream_units=[10],
                output_dir=output_dir,
                language="python",
            )

    def test_raises_value_error_on_equal_unit_number_reference(self, tmp_path):
        """Forward-reference guard: upstream unit number == unit_number raises ValueError."""
        blueprint_dir = tmp_path / "blueprint"
        blueprint_dir.mkdir()
        output_dir = tmp_path / "output"
        output_dir.mkdir()

        with pytest.raises(ValueError):
            generate_upstream_stubs(
                blueprint_dir=blueprint_dir,
                unit_number=5,
                upstream_units=[5],
                output_dir=output_dir,
                language="python",
            )

    def test_raises_value_error_when_any_upstream_is_forward_reference(self, tmp_path):
        """If any upstream unit is a forward reference, ValueError is raised."""
        blueprint_dir = tmp_path / "blueprint"
        blueprint_dir.mkdir()
        output_dir = tmp_path / "output"
        output_dir.mkdir()

        # Unit 10 with upstream [2, 8, 15] -- 15 is a forward reference
        with pytest.raises(ValueError):
            generate_upstream_stubs(
                blueprint_dir=blueprint_dir,
                unit_number=10,
                upstream_units=[2, 8, 15],
                output_dir=output_dir,
                language="python",
            )

    def test_accepts_valid_upstream_units_all_lower(self, tmp_path):
        """All upstream units with lower numbers than unit_number should not raise ValueError."""
        blueprint_dir = tmp_path / "blueprint"
        blueprint_dir.mkdir()
        output_dir = tmp_path / "output"
        output_dir.mkdir()

        # Create a minimal blueprint_contracts.md with Tier 2 blocks for units 2 and 8
        contracts = textwrap.dedent("""\
            ## Unit 2: Language Registry

            ### Tier 2 -- Signatures

            ```python
            def get_language_config(language: str) -> dict: ...
            ```

            ### Tier 3 -- Behavioral Contracts

            Some contracts.

            ## Unit 8: Blueprint Extractor

            ### Tier 2 -- Signatures

            ```python
            def extract_units(blueprint_dir: str) -> list: ...
            ```

            ### Tier 3 -- Behavioral Contracts

            Some contracts.
        """)
        (blueprint_dir / "blueprint_contracts.md").write_text(contracts)
        # Also create prose file if needed
        prose = textwrap.dedent("""\
            ## Unit 2: Language Registry

            Description.

            ## Unit 8: Blueprint Extractor

            Description.
        """)
        (blueprint_dir / "blueprint_prose.md").write_text(prose)

        # Should not raise ValueError for forward references
        # May raise other errors if extraction/parsing details differ, but NOT ValueError
        try:
            generate_upstream_stubs(
                blueprint_dir=blueprint_dir,
                unit_number=10,
                upstream_units=[2, 8],
                output_dir=output_dir,
                language="python",
            )
        except ValueError as e:
            if "forward" in str(e).lower():
                pytest.fail(
                    f"Should not raise forward-reference ValueError for valid upstreams: {e}"
                )
            # Other ValueErrors may be acceptable depending on blueprint content

    def test_writes_stub_files_to_output_dir(self, tmp_path):
        """For each upstream unit, a stub file is written to output_dir."""
        blueprint_dir = tmp_path / "blueprint"
        blueprint_dir.mkdir()
        output_dir = tmp_path / "output"
        output_dir.mkdir()

        contracts = textwrap.dedent("""\
            ## Unit 2: Language Registry

            ### Tier 2 -- Signatures

            ```python
            def get_language_config(language: str) -> dict: ...
            ```

            ### Tier 3 -- Behavioral Contracts

            Some contracts.
        """)
        (blueprint_dir / "blueprint_contracts.md").write_text(contracts)
        prose = textwrap.dedent("""\
            ## Unit 2: Language Registry

            Description.
        """)
        (blueprint_dir / "blueprint_prose.md").write_text(prose)

        try:
            generate_upstream_stubs(
                blueprint_dir=blueprint_dir,
                unit_number=10,
                upstream_units=[2],
                output_dir=output_dir,
                language="python",
            )
            # Check that something was written
            output_files = list(output_dir.rglob("*"))
            non_dir_files = [f for f in output_files if f.is_file()]
            assert len(non_dir_files) > 0, "No stub files were written to output_dir"
        except Exception:
            # If it fails due to blueprint format/content specifics, that is
            # acceptable -- the forward-reference guard is the key invariant
            pass

    def test_empty_upstream_list_produces_no_stubs(self, tmp_path):
        """With no upstream units, no stubs are generated and no error occurs."""
        blueprint_dir = tmp_path / "blueprint"
        blueprint_dir.mkdir()
        output_dir = tmp_path / "output"
        output_dir.mkdir()

        (blueprint_dir / "blueprint_contracts.md").write_text("# Empty\n")
        (blueprint_dir / "blueprint_prose.md").write_text("# Empty\n")

        # No upstream units -- should complete without error
        generate_upstream_stubs(
            blueprint_dir=blueprint_dir,
            unit_number=10,
            upstream_units=[],
            output_dir=output_dir,
            language="python",
        )
        # Output dir should have no generated files (or only dirs)
        output_files = [f for f in output_dir.rglob("*") if f.is_file()]
        assert len(output_files) == 0


# ---------------------------------------------------------------------------
# main (CLI entry point) tests
# ---------------------------------------------------------------------------


class TestMainCLI:
    """Tests for the main CLI entry point."""

    def test_main_accepts_required_arguments(self, tmp_path):
        """main accepts --blueprint, --unit, --output-dir, --upstream."""
        blueprint_dir = tmp_path / "blueprint"
        blueprint_dir.mkdir()
        output_dir = tmp_path / "output"
        output_dir.mkdir()

        contracts = textwrap.dedent("""\
            ## Unit 5: Pipeline State

            ### Tier 2 -- Signatures

            ```python
            def get_state() -> dict: ...
            ```

            ### Tier 3 -- Behavioral Contracts

            Some contracts.
        """)
        bp_file = blueprint_dir / "blueprint_contracts.md"
        bp_file.write_text(contracts)
        prose = textwrap.dedent("""\
            ## Unit 5: Pipeline State

            Description.
        """)
        (blueprint_dir / "blueprint_prose.md").write_text(prose)

        # Call main with required args; may succeed or fail based on
        # implementation details, but should parse args without error
        try:
            main(
                [
                    "--blueprint",
                    str(bp_file),
                    "--unit",
                    "5",
                    "--output-dir",
                    str(output_dir),
                    "--upstream",
                    "",
                ]
            )
        except SystemExit as e:
            # Exit code 0 is success, 1 is failure -- both are valid
            assert e.code in (0, 1, None)

    def test_main_with_empty_upstream_string(self, tmp_path):
        """Empty string for --upstream means no dependencies."""
        blueprint_dir = tmp_path / "blueprint"
        blueprint_dir.mkdir()
        output_dir = tmp_path / "output"
        output_dir.mkdir()

        contracts = textwrap.dedent("""\
            ## Unit 1: Core Configuration

            ### Tier 2 -- Signatures

            ```python
            def load_config() -> dict: ...
            ```

            ### Tier 3 -- Behavioral Contracts

            Root unit.
        """)
        bp_file = blueprint_dir / "blueprint_contracts.md"
        bp_file.write_text(contracts)
        prose = textwrap.dedent("""\
            ## Unit 1: Core Configuration

            Description.
        """)
        (blueprint_dir / "blueprint_prose.md").write_text(prose)

        try:
            main(
                [
                    "--blueprint",
                    str(bp_file),
                    "--unit",
                    "1",
                    "--output-dir",
                    str(output_dir),
                    "--upstream",
                    "",
                ]
            )
        except SystemExit as e:
            assert e.code in (0, 1, None)

    def test_main_with_comma_separated_upstream(self, tmp_path):
        """--upstream accepts comma-separated list of ints."""
        blueprint_dir = tmp_path / "blueprint"
        blueprint_dir.mkdir()
        output_dir = tmp_path / "output"
        output_dir.mkdir()

        contracts = textwrap.dedent("""\
            ## Unit 2: Language Registry

            ### Tier 2 -- Signatures

            ```python
            def get_language_config(language: str) -> dict: ...
            ```

            ### Tier 3 -- Behavioral Contracts

            Some contracts.

            ## Unit 8: Blueprint Extractor

            ### Tier 2 -- Signatures

            ```python
            def extract_units(blueprint_dir: str) -> list: ...
            ```

            ### Tier 3 -- Behavioral Contracts

            Some contracts.

            ## Unit 9: Signature Parser Dispatch

            ### Tier 2 -- Signatures

            ```python
            def parse_signatures(source: str, language: str) -> object: ...
            ```

            ### Tier 3 -- Behavioral Contracts

            Some contracts.

            ## Unit 10: Stub Generator Dispatch

            ### Tier 2 -- Signatures

            ```python
            def generate_stub(parsed: object, language: str) -> str: ...
            ```

            ### Tier 3 -- Behavioral Contracts

            Some contracts.
        """)
        bp_file = blueprint_dir / "blueprint_contracts.md"
        bp_file.write_text(contracts)
        prose = textwrap.dedent("""\
            ## Unit 2: Language Registry

            Description.

            ## Unit 8: Blueprint Extractor

            Description.

            ## Unit 9: Signature Parser Dispatch

            Description.

            ## Unit 10: Stub Generator Dispatch

            Description.
        """)
        (blueprint_dir / "blueprint_prose.md").write_text(prose)

        try:
            main(
                [
                    "--blueprint",
                    str(bp_file),
                    "--unit",
                    "10",
                    "--output-dir",
                    str(output_dir),
                    "--upstream",
                    "2,8,9",
                ]
            )
        except SystemExit as e:
            assert e.code in (0, 1, None)

    def test_main_exits_with_code_0_on_success(self, tmp_path):
        """On success, main exits with code 0 (or returns None)."""
        blueprint_dir = tmp_path / "blueprint"
        blueprint_dir.mkdir()
        output_dir = tmp_path / "output"
        output_dir.mkdir()

        contracts = textwrap.dedent("""\
            ## Unit 1: Core Configuration

            ### Tier 2 -- Signatures

            ```python
            def load_config() -> dict: ...
            ```

            ### Tier 3 -- Behavioral Contracts

            Root unit.
        """)
        bp_file = blueprint_dir / "blueprint_contracts.md"
        bp_file.write_text(contracts)
        prose = textwrap.dedent("""\
            ## Unit 1: Core Configuration

            Description.
        """)
        (blueprint_dir / "blueprint_prose.md").write_text(prose)

        exit_code = None
        try:
            result = main(
                [
                    "--blueprint",
                    str(bp_file),
                    "--unit",
                    "1",
                    "--output-dir",
                    str(output_dir),
                    "--upstream",
                    "",
                ]
            )
            # If main returns without raising, that's success (exit code 0)
            exit_code = 0
        except SystemExit as e:
            exit_code = e.code

        # Success should be exit code 0 or None (implicit return)
        assert exit_code in (0, None), f"Expected success exit code, got {exit_code}"

    def test_main_accepts_language_argument(self, tmp_path):
        """main accepts --language argument."""
        blueprint_dir = tmp_path / "blueprint"
        blueprint_dir.mkdir()
        output_dir = tmp_path / "output"
        output_dir.mkdir()

        contracts = textwrap.dedent("""\
            ## Unit 1: Core Configuration

            ### Tier 2 -- Signatures

            ```python
            def load_config() -> dict: ...
            ```

            ### Tier 3 -- Behavioral Contracts

            Root unit.
        """)
        bp_file = blueprint_dir / "blueprint_contracts.md"
        bp_file.write_text(contracts)
        prose = textwrap.dedent("""\
            ## Unit 1: Core Configuration

            Description.
        """)
        (blueprint_dir / "blueprint_prose.md").write_text(prose)

        try:
            main(
                [
                    "--blueprint",
                    str(bp_file),
                    "--unit",
                    "1",
                    "--output-dir",
                    str(output_dir),
                    "--upstream",
                    "",
                    "--language",
                    "python",
                ]
            )
        except SystemExit as e:
            assert e.code in (0, 1, None)

    def test_main_exits_with_code_1_on_failure(self, tmp_path):
        """On failure, main exits with code 1."""
        output_dir = tmp_path / "output"
        output_dir.mkdir()

        # Pass a non-existent blueprint file to trigger failure
        try:
            main(
                [
                    "--blueprint",
                    str(tmp_path / "nonexistent_blueprint.md"),
                    "--unit",
                    "1",
                    "--output-dir",
                    str(output_dir),
                    "--upstream",
                    "",
                ]
            )
            # If it doesn't raise, that might mean it handled error differently
        except SystemExit as e:
            assert e.code == 1, f"Expected exit code 1 on failure, got {e.code}"
        except (FileNotFoundError, OSError):
            # Also acceptable -- implementation may raise directly
            pass

    def test_main_with_no_args_exits_with_error(self):
        """Calling main with no arguments should fail (missing required args)."""
        with pytest.raises((SystemExit, TypeError)):
            main([])


# ---------------------------------------------------------------------------
# Invariant / cross-cutting tests
# ---------------------------------------------------------------------------


class TestInvariantsAndEdgeCases:
    """Tests for cross-cutting invariants and edge cases."""

    def test_python_stub_for_empty_module_contains_only_sentinel(self):
        """A module with no functions/classes produces a stub with at least the sentinel."""
        empty_source = ""
        parsed = ast.parse(empty_source)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        assert PYTHON_SENTINEL in result

    def test_python_stub_for_module_with_only_imports(self):
        """A module with only imports produces a valid stub with sentinel."""
        import_only = "from typing import Any\nimport os\n"
        parsed = ast.parse(import_only)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        assert PYTHON_SENTINEL in result
        ast.parse(result)  # Must be valid Python

    def test_all_dispatch_keys_in_stub_generators_produce_string_output(self):
        """Every generator in STUB_GENERATORS returns a string when called."""
        # Test with None as parsed_signatures (works for all template-based generators)
        for key in ["stan_template", "plugin_markdown", "plugin_bash", "plugin_json"]:
            if key in STUB_GENERATORS:
                # These should accept (None, config_dict) and return a string
                config = {"stub_generator_key": key, "is_component_only": True}
                result = STUB_GENERATORS[key](None, config)
                assert isinstance(result, str), (
                    f"STUB_GENERATORS[{key!r}] did not return a string"
                )

    def test_python_generator_in_dispatch_table_produces_stub_with_ast(self):
        """The python entry in STUB_GENERATORS works with AST parsed signatures."""
        parsed = ast.parse("def foo() -> int: ...")
        result = STUB_GENERATORS["python"](parsed, PYTHON_LANGUAGE_CONFIG)
        assert isinstance(result, str)
        assert "def foo(" in result

    def test_r_generator_in_dispatch_table_produces_stub(self):
        """The r entry in STUB_GENERATORS produces a string stub."""
        r_parsed = [{"name": "foo", "params": []}]
        result = STUB_GENERATORS["r"](r_parsed, R_LANGUAGE_CONFIG)
        assert isinstance(result, str)
        assert "foo" in result

    def test_generate_stub_dispatches_through_stub_generator_key_not_language_name(
        self,
    ):
        """
        generate_stub uses language_config['stub_generator_key'] for dispatch,
        not the language parameter directly. This is important for component
        languages where the language name differs from the dispatch key
        (e.g., language='stan' but stub_generator_key='stan_template').
        """
        # Stan: language='stan', stub_generator_key='stan_template'
        result = generate_stub(None, "stan", STAN_LANGUAGE_CONFIG)
        assert isinstance(result, str)

    def test_forward_reference_guard_with_multiple_valid_and_one_invalid(
        self, tmp_path
    ):
        """Even if most upstreams are valid, one forward reference raises ValueError."""
        blueprint_dir = tmp_path / "blueprint"
        blueprint_dir.mkdir()
        output_dir = tmp_path / "output"
        output_dir.mkdir()

        with pytest.raises(ValueError):
            generate_upstream_stubs(
                blueprint_dir=blueprint_dir,
                unit_number=10,
                upstream_units=[2, 8, 9, 11],  # 11 > 10 is forward
                output_dir=output_dir,
                language="python",
            )

    def test_forward_reference_guard_boundary_just_below(self, tmp_path):
        """Upstream unit_number - 1 is the maximum valid upstream."""
        blueprint_dir = tmp_path / "blueprint"
        blueprint_dir.mkdir()
        output_dir = tmp_path / "output"
        output_dir.mkdir()

        contracts = textwrap.dedent("""\
            ## Unit 9: Signature Parser Dispatch

            ### Tier 2 -- Signatures

            ```python
            def parse_signatures(source: str, language: str) -> object: ...
            ```

            ### Tier 3 -- Behavioral Contracts

            Some contracts.
        """)
        (blueprint_dir / "blueprint_contracts.md").write_text(contracts)
        (blueprint_dir / "blueprint_prose.md").write_text(
            "## Unit 9: Signature Parser Dispatch\n\nDescription.\n"
        )

        # Unit 10 with upstream [9] -- 9 < 10, should NOT raise ValueError for forward ref
        try:
            generate_upstream_stubs(
                blueprint_dir=blueprint_dir,
                unit_number=10,
                upstream_units=[9],
                output_dir=output_dir,
                language="python",
            )
        except ValueError as e:
            if "forward" in str(e).lower():
                pytest.fail(
                    f"Upstream unit 9 for unit 10 should not be a forward reference: {e}"
                )
