"""Unit 10: Stub Generator Dispatch -- complete test suite.

Synthetic data assumptions:
- STUB_GENERATORS is a dict mapping language dispatch keys (str) to callables
  that accept (parsed_signatures: Any, language_config: Dict[str, Any]) and
  return a stub string.
- Key "python": generates Python stubs. Every function body contains
  `raise NotImplementedError()`. Every class body has methods raising
  NotImplementedError() and class-level attributes set to None. Module-level
  assert statements are stripped. The stub sentinel is prepended as the first
  non-import statement.
- Key "r": generates R stubs. Function bodies contain `stop("Not implemented")`.
  The R sentinel is prepended as a comment.
- Key "stan_template": generates a minimal Stan model template with a sentinel
  comment. Receives None as parsed_signatures (bypasses signature parsing).
- Keys "plugin_markdown", "plugin_bash", "plugin_json": generate minimal valid
  stubs for plugin artifact types. Receive None as parsed_signatures.
- generate_stub dispatches via language_config["stub_generator_key"].
  For plugin and component dispatch keys, parsed_signatures is bypassed (None
  passed to generator). For full languages (Python, R), the language-specific
  sentinel from LANGUAGE_REGISTRY[language]["stub_sentinel"] is prepended
  verbatim.
- Sentinel injection invariant (Bug S3-2, S3-4): the sentinel string MUST be
  the exact value from LANGUAGE_REGISTRY, injected verbatim. No reformatting.
- generate_upstream_stubs: for each upstream unit, extracts Tier 2, parses
  signatures, generates stub, writes to output_dir. Forward-reference guard:
  every dependency must have a lower unit number than unit_number; raises
  ValueError on forward reference.
- main CLI: --blueprint (path), --unit (int), --output-dir (path),
  --upstream (comma-separated ints or empty string). Generates stub for current
  unit and upstream stubs for dependencies. Exit 0 on success, 1 on failure.
- Python sentinel: '__SVP_STUB__ = True  # DO NOT DELIVER -- stub file generated by SVP'
- R sentinel: '# __SVP_STUB__ <- TRUE  # DO NOT DELIVER -- stub file generated by SVP'
- Valid Python Tier 2 source: "def foo(x: int) -> str: ..." produces a stub
  with `def foo(x: int) -> str:` and body `raise NotImplementedError()`.
- Valid R Tier 2 source: "my_func <- function(x, y) { x + y }" produces a stub
  with `stop("Not implemented")` in the body.
- A UnitDefinition from Unit 8 has fields: number, name, tier1, tier2, tier3,
  dependencies, languages, machinery.
"""

import ast
import textwrap
from unittest.mock import patch

import pytest

from src.unit_10.stub import (
    STUB_GENERATORS,
    generate_stub,
    generate_upstream_stubs,
    main,
)

# ---------------------------------------------------------------------------
# Constants: sentinels and synthetic configs
# ---------------------------------------------------------------------------

PYTHON_SENTINEL = "__SVP_STUB__ = True  # DO NOT DELIVER -- stub file generated by SVP"
R_SENTINEL = "# __SVP_STUB__ <- TRUE  # DO NOT DELIVER -- stub file generated by SVP"

PYTHON_LANGUAGE_CONFIG = {
    "id": "python",
    "display_name": "Python",
    "file_extension": ".py",
    "source_dir": "src",
    "test_dir": "tests",
    "stub_generator_key": "python",
    "stub_sentinel": PYTHON_SENTINEL,
    "is_component_only": False,
}

R_LANGUAGE_CONFIG = {
    "id": "r",
    "display_name": "R",
    "file_extension": ".R",
    "source_dir": "R",
    "test_dir": "tests/testthat",
    "stub_generator_key": "r",
    "stub_sentinel": R_SENTINEL,
    "is_component_only": False,
}

STAN_LANGUAGE_CONFIG = {
    "id": "stan",
    "display_name": "Stan",
    "file_extension": ".stan",
    "is_component_only": True,
    "compatible_hosts": ["r", "python"],
    "stub_generator_key": "stan_template",
}

PLUGIN_MARKDOWN_CONFIG = {
    "id": "plugin_markdown",
    "stub_generator_key": "plugin_markdown",
    "is_component_only": True,
}

PLUGIN_BASH_CONFIG = {
    "id": "plugin_bash",
    "stub_generator_key": "plugin_bash",
    "is_component_only": True,
}

PLUGIN_JSON_CONFIG = {
    "id": "plugin_json",
    "stub_generator_key": "plugin_json",
    "is_component_only": True,
}

# Sample Python source (as would be extracted from Tier 2)
PYTHON_TIER2_SOURCE = textwrap.dedent("""\
    from typing import Any, Dict, List
    from pathlib import Path

    def process_data(input_path: Path, config: Dict[str, Any]) -> List[str]:
        ...

    class DataProcessor:
        name: str
        value: int

        def run(self, data: Any) -> None:
            ...

        def reset(self) -> None:
            ...
""")

PYTHON_SIMPLE_FUNC = "def foo(x: int) -> str:\n    ...\n"

PYTHON_WITH_ASSERT = textwrap.dedent("""\
    from typing import Dict

    assert True, "module-level assert"

    REGISTRY: Dict[str, str]

    def compute(x: int) -> int:
        ...

    assert len(REGISTRY) > 0
""")

PYTHON_MULTI_CLASS = textwrap.dedent("""\
    class Alpha:
        x: int = None
        def method_a(self) -> None:
            ...

    class Beta:
        y: str = None
        def method_b(self, val: str) -> str:
            ...
""")

R_TIER2_SOURCE = textwrap.dedent("""\
    my_func <- function(x, y) {
      x + y
    }

    another_func <- function(data, threshold = 0.05) {
      data
    }
""")


# ---------------------------------------------------------------------------
# Helper: parse Python source to AST (simulates what Unit 9 produces)
# ---------------------------------------------------------------------------


def make_python_ast(source: str):
    """Parse Python source into an AST module, as Unit 9's python parser does."""
    return ast.parse(source)


# ---------------------------------------------------------------------------
# STUB_GENERATORS dispatch table
# ---------------------------------------------------------------------------


class TestStubGeneratorsDispatchTable:
    """Tests for the STUB_GENERATORS module-level dispatch table."""

    def test_stub_generators_is_dict(self):
        """STUB_GENERATORS must be a dict."""
        assert isinstance(STUB_GENERATORS, dict)

    def test_python_key_present(self):
        """Dispatch table must contain a 'python' key."""
        assert "python" in STUB_GENERATORS

    def test_r_key_present(self):
        """Dispatch table must contain an 'r' key."""
        assert "r" in STUB_GENERATORS

    def test_stan_template_key_present(self):
        """Dispatch table must contain a 'stan_template' key."""
        assert "stan_template" in STUB_GENERATORS

    def test_plugin_markdown_key_present(self):
        """Dispatch table must contain a 'plugin_markdown' key."""
        assert "plugin_markdown" in STUB_GENERATORS

    def test_plugin_bash_key_present(self):
        """Dispatch table must contain a 'plugin_bash' key."""
        assert "plugin_bash" in STUB_GENERATORS

    def test_plugin_json_key_present(self):
        """Dispatch table must contain a 'plugin_json' key."""
        assert "plugin_json" in STUB_GENERATORS

    def test_python_generator_is_callable(self):
        """The python stub generator must be callable."""
        assert callable(STUB_GENERATORS["python"])

    def test_r_generator_is_callable(self):
        """The r stub generator must be callable."""
        assert callable(STUB_GENERATORS["r"])

    def test_stan_template_generator_is_callable(self):
        """The stan_template stub generator must be callable."""
        assert callable(STUB_GENERATORS["stan_template"])

    def test_plugin_markdown_generator_is_callable(self):
        """The plugin_markdown stub generator must be callable."""
        assert callable(STUB_GENERATORS["plugin_markdown"])

    def test_plugin_bash_generator_is_callable(self):
        """The plugin_bash stub generator must be callable."""
        assert callable(STUB_GENERATORS["plugin_bash"])

    def test_plugin_json_generator_is_callable(self):
        """The plugin_json stub generator must be callable."""
        assert callable(STUB_GENERATORS["plugin_json"])

    def test_all_keys_are_strings(self):
        """All keys in STUB_GENERATORS must be strings."""
        for key in STUB_GENERATORS:
            assert isinstance(key, str), f"Key {key!r} is not a string"

    def test_all_values_are_callable(self):
        """All values in STUB_GENERATORS must be callable."""
        for key, gen in STUB_GENERATORS.items():
            assert callable(gen), f"Generator for {key!r} is not callable"


# ---------------------------------------------------------------------------
# Python stub generator (STUB_GENERATORS["python"])
# ---------------------------------------------------------------------------


class TestPythonStubGenerator:
    """Tests for the Python stub generator via STUB_GENERATORS['python']."""

    def test_python_generator_returns_string(self):
        """Python stub generator returns a string."""
        parsed = make_python_ast(PYTHON_SIMPLE_FUNC)
        result = STUB_GENERATORS["python"](parsed, PYTHON_LANGUAGE_CONFIG)
        assert isinstance(result, str)

    def test_python_function_body_has_raise_not_implemented(self):
        """Every function body in a Python stub must contain raise NotImplementedError()."""
        parsed = make_python_ast(PYTHON_SIMPLE_FUNC)
        result = STUB_GENERATORS["python"](parsed, PYTHON_LANGUAGE_CONFIG)
        assert "raise NotImplementedError()" in result

    def test_python_class_methods_raise_not_implemented(self):
        """Class methods in a Python stub must raise NotImplementedError()."""
        parsed = make_python_ast(PYTHON_MULTI_CLASS)
        result = STUB_GENERATORS["python"](parsed, PYTHON_LANGUAGE_CONFIG)
        # There should be at least two raises for the two methods
        assert result.count("raise NotImplementedError()") >= 2

    def test_python_class_attributes_set_to_none(self):
        """Class-level attributes in a Python stub must be set to None."""
        parsed = make_python_ast(PYTHON_MULTI_CLASS)
        result = STUB_GENERATORS["python"](parsed, PYTHON_LANGUAGE_CONFIG)
        # Alpha.x and Beta.y should be set to None
        assert "= None" in result

    def test_python_module_level_asserts_stripped(self):
        """Module-level assert statements must be stripped from Python stubs."""
        parsed = make_python_ast(PYTHON_WITH_ASSERT)
        result = STUB_GENERATORS["python"](parsed, PYTHON_LANGUAGE_CONFIG)
        # No assert statements should survive in the stub
        lines = result.split("\n")
        assert_lines = [line for line in lines if line.strip().startswith("assert ")]
        assert len(assert_lines) == 0, f"Found assert lines: {assert_lines}"

    def test_python_sentinel_prepended(self):
        """The Python stub sentinel must be prepended as the first non-import statement."""
        parsed = make_python_ast(PYTHON_TIER2_SOURCE)
        result = STUB_GENERATORS["python"](parsed, PYTHON_LANGUAGE_CONFIG)
        assert PYTHON_SENTINEL in result

    def test_python_sentinel_is_first_non_import_line(self):
        """The sentinel must appear before any non-import code in the stub."""
        parsed = make_python_ast(PYTHON_TIER2_SOURCE)
        result = STUB_GENERATORS["python"](parsed, PYTHON_LANGUAGE_CONFIG)
        lines = result.split("\n")
        sentinel_index = None
        first_non_import_index = None
        for i, line in enumerate(lines):
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if stripped.startswith(("import ", "from ")):
                continue
            if PYTHON_SENTINEL in line:
                sentinel_index = i
                break
            if first_non_import_index is None:
                first_non_import_index = i
                break
        # Sentinel should appear at or before first non-import line
        if sentinel_index is not None and first_non_import_index is not None:
            assert sentinel_index <= first_non_import_index
        elif sentinel_index is not None:
            # Sentinel found, no other non-import code before it -- correct
            pass
        else:
            pytest.fail("Sentinel not found in stub output")

    def test_python_stub_preserves_function_signature(self):
        """Function signatures (name, params, return type) must be preserved in the stub."""
        parsed = make_python_ast(PYTHON_SIMPLE_FUNC)
        result = STUB_GENERATORS["python"](parsed, PYTHON_LANGUAGE_CONFIG)
        assert "def foo" in result
        assert "x" in result

    def test_python_stub_preserves_class_name(self):
        """Class names must be preserved in the generated Python stub."""
        parsed = make_python_ast(PYTHON_MULTI_CLASS)
        result = STUB_GENERATORS["python"](parsed, PYTHON_LANGUAGE_CONFIG)
        assert "class Alpha" in result
        assert "class Beta" in result

    def test_python_stub_preserves_imports(self):
        """Import statements from the source must be preserved in the stub."""
        parsed = make_python_ast(PYTHON_TIER2_SOURCE)
        result = STUB_GENERATORS["python"](parsed, PYTHON_LANGUAGE_CONFIG)
        assert "from typing import" in result or "import typing" in result
        assert "from pathlib import Path" in result or "import pathlib" in result

    def test_python_stub_multi_function_all_raise(self):
        """A stub with multiple functions must have raise NotImplementedError() in each."""
        source = textwrap.dedent("""\
            def alpha(x: int) -> int:
                ...

            def beta(y: str) -> str:
                ...

            def gamma() -> None:
                ...
        """)
        parsed = make_python_ast(source)
        result = STUB_GENERATORS["python"](parsed, PYTHON_LANGUAGE_CONFIG)
        assert result.count("raise NotImplementedError()") >= 3

    def test_python_stub_is_valid_python(self):
        """The generated Python stub must be syntactically valid Python."""
        parsed = make_python_ast(PYTHON_TIER2_SOURCE)
        result = STUB_GENERATORS["python"](parsed, PYTHON_LANGUAGE_CONFIG)
        # Should parse without SyntaxError
        ast.parse(result)

    def test_python_stub_complex_class_with_methods_and_attributes(self):
        """A class with both attributes and methods produces correct stub structure."""
        source = textwrap.dedent("""\
            class DataProcessor:
                name: str
                value: int

                def run(self, data) -> None:
                    ...

                def reset(self) -> None:
                    ...
        """)
        parsed = make_python_ast(source)
        result = STUB_GENERATORS["python"](parsed, PYTHON_LANGUAGE_CONFIG)
        assert "class DataProcessor" in result
        assert "def run" in result
        assert "def reset" in result
        assert "raise NotImplementedError()" in result

    def test_python_stub_empty_source_still_has_sentinel(self):
        """Even with an empty source, the generated Python stub contains the sentinel."""
        parsed = make_python_ast("")
        result = STUB_GENERATORS["python"](parsed, PYTHON_LANGUAGE_CONFIG)
        assert PYTHON_SENTINEL in result


# ---------------------------------------------------------------------------
# R stub generator (STUB_GENERATORS["r"])
# ---------------------------------------------------------------------------


class TestRStubGenerator:
    """Tests for the R stub generator via STUB_GENERATORS['r']."""

    def test_r_generator_returns_string(self):
        """R stub generator returns a string."""
        # R parser returns a list of function definitions; simulate that
        parsed = [{"name": "my_func", "params": ["x", "y"]}]
        result = STUB_GENERATORS["r"](parsed, R_LANGUAGE_CONFIG)
        assert isinstance(result, str)

    def test_r_function_body_has_stop_not_implemented(self):
        """R function bodies must contain stop("Not implemented")."""
        parsed = [{"name": "my_func", "params": ["x", "y"]}]
        result = STUB_GENERATORS["r"](parsed, R_LANGUAGE_CONFIG)
        assert 'stop("Not implemented")' in result

    def test_r_sentinel_prepended(self):
        """The R sentinel must be prepended as a comment."""
        parsed = [{"name": "my_func", "params": ["x"]}]
        result = STUB_GENERATORS["r"](parsed, R_LANGUAGE_CONFIG)
        assert R_SENTINEL in result

    def test_r_sentinel_appears_before_function_code(self):
        """The R sentinel must appear before any function definitions."""
        parsed = [{"name": "my_func", "params": ["x"]}]
        result = STUB_GENERATORS["r"](parsed, R_LANGUAGE_CONFIG)
        sentinel_pos = result.find(R_SENTINEL)
        func_pos = result.find("my_func")
        assert sentinel_pos < func_pos, "Sentinel must appear before function code"

    def test_r_multiple_functions_all_have_stop(self):
        """Multiple R functions in a stub each get stop("Not implemented")."""
        parsed = [
            {"name": "add", "params": ["a", "b"]},
            {"name": "subtract", "params": ["a", "b"]},
        ]
        result = STUB_GENERATORS["r"](parsed, R_LANGUAGE_CONFIG)
        assert result.count('stop("Not implemented")') >= 2

    def test_r_stub_preserves_function_names(self):
        """Function names must be preserved in the R stub."""
        parsed = [
            {"name": "add", "params": ["a", "b"]},
            {"name": "subtract", "params": ["a", "b"]},
        ]
        result = STUB_GENERATORS["r"](parsed, R_LANGUAGE_CONFIG)
        assert "add" in result
        assert "subtract" in result

    def test_r_stub_function_with_no_params(self):
        """An R function with no parameters produces a valid stub."""
        parsed = [{"name": "get_version", "params": []}]
        result = STUB_GENERATORS["r"](parsed, R_LANGUAGE_CONFIG)
        assert "get_version" in result
        assert 'stop("Not implemented")' in result

    def test_r_sentinel_is_verbatim(self):
        """The R sentinel must be the exact verbatim value, not reformatted."""
        parsed = [{"name": "f", "params": []}]
        result = STUB_GENERATORS["r"](parsed, R_LANGUAGE_CONFIG)
        # Check the sentinel appears exactly (not abbreviated, not reformatted)
        assert R_SENTINEL in result


# ---------------------------------------------------------------------------
# Stan template stub generator (STUB_GENERATORS["stan_template"])
# ---------------------------------------------------------------------------


class TestStanTemplateStubGenerator:
    """Tests for the Stan template stub generator."""

    def test_stan_template_returns_string(self):
        """Stan template generator returns a string."""
        result = STUB_GENERATORS["stan_template"](None, STAN_LANGUAGE_CONFIG)
        assert isinstance(result, str)

    def test_stan_template_receives_none_as_parsed_signatures(self):
        """Stan template generator must accept None as parsed_signatures."""
        # Should not raise when passed None
        result = STUB_GENERATORS["stan_template"](None, STAN_LANGUAGE_CONFIG)
        assert result is not None

    def test_stan_template_has_sentinel_comment(self):
        """Stan template must contain a sentinel comment."""
        result = STUB_GENERATORS["stan_template"](None, STAN_LANGUAGE_CONFIG)
        # Stan uses comments with //
        assert "SVP" in result or "stub" in result.lower() or "STUB" in result

    def test_stan_template_is_minimal_model(self):
        """Stan template must be a minimal Stan model template."""
        result = STUB_GENERATORS["stan_template"](None, STAN_LANGUAGE_CONFIG)
        # A minimal Stan model typically has data/parameters/model blocks
        # At minimum it should be non-empty and contain some stan structure
        assert len(result.strip()) > 0

    def test_stan_template_is_valid_structure(self):
        """Stan template should contain at least some recognizable Stan block keyword."""
        result = STUB_GENERATORS["stan_template"](None, STAN_LANGUAGE_CONFIG)
        # Stan models typically contain keywords like data, parameters, model
        result_lower = result.lower()
        has_stan_keywords = (
            "data" in result_lower
            or "parameters" in result_lower
            or "model" in result_lower
        )
        assert has_stan_keywords, (
            "Stan template should contain recognizable Stan block keywords"
        )


# ---------------------------------------------------------------------------
# Plugin stub generators
# ---------------------------------------------------------------------------


class TestPluginStubGenerators:
    """Tests for plugin artifact type stub generators."""

    def test_plugin_markdown_returns_string(self):
        """plugin_markdown generator returns a string."""
        result = STUB_GENERATORS["plugin_markdown"](None, PLUGIN_MARKDOWN_CONFIG)
        assert isinstance(result, str)

    def test_plugin_markdown_receives_none_signatures(self):
        """plugin_markdown generator accepts None as parsed_signatures."""
        result = STUB_GENERATORS["plugin_markdown"](None, PLUGIN_MARKDOWN_CONFIG)
        assert result is not None

    def test_plugin_markdown_produces_valid_markdown(self):
        """plugin_markdown generates a minimal valid markdown stub."""
        result = STUB_GENERATORS["plugin_markdown"](None, PLUGIN_MARKDOWN_CONFIG)
        assert len(result.strip()) > 0

    def test_plugin_bash_returns_string(self):
        """plugin_bash generator returns a string."""
        result = STUB_GENERATORS["plugin_bash"](None, PLUGIN_BASH_CONFIG)
        assert isinstance(result, str)

    def test_plugin_bash_receives_none_signatures(self):
        """plugin_bash generator accepts None as parsed_signatures."""
        result = STUB_GENERATORS["plugin_bash"](None, PLUGIN_BASH_CONFIG)
        assert result is not None

    def test_plugin_bash_produces_valid_bash(self):
        """plugin_bash generates a minimal valid bash stub."""
        result = STUB_GENERATORS["plugin_bash"](None, PLUGIN_BASH_CONFIG)
        assert len(result.strip()) > 0

    def test_plugin_json_returns_string(self):
        """plugin_json generator returns a string."""
        result = STUB_GENERATORS["plugin_json"](None, PLUGIN_JSON_CONFIG)
        assert isinstance(result, str)

    def test_plugin_json_receives_none_signatures(self):
        """plugin_json generator accepts None as parsed_signatures."""
        result = STUB_GENERATORS["plugin_json"](None, PLUGIN_JSON_CONFIG)
        assert result is not None

    def test_plugin_json_produces_valid_json(self):
        """plugin_json generates a minimal valid JSON stub."""
        import json

        result = STUB_GENERATORS["plugin_json"](None, PLUGIN_JSON_CONFIG)
        assert len(result.strip()) > 0
        # Should be parseable as JSON
        json.loads(result)


# ---------------------------------------------------------------------------
# generate_stub function
# ---------------------------------------------------------------------------


class TestGenerateStub:
    """Tests for the generate_stub dispatch function."""

    def test_generate_stub_python_dispatches_via_stub_generator_key(self):
        """generate_stub dispatches to STUB_GENERATORS[language_config['stub_generator_key']]."""
        parsed = make_python_ast(PYTHON_SIMPLE_FUNC)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        assert isinstance(result, str)
        assert "raise NotImplementedError()" in result

    def test_generate_stub_r_dispatches_correctly(self):
        """generate_stub for R dispatches to the R stub generator."""
        parsed = [{"name": "f", "params": ["x"]}]
        result = generate_stub(parsed, "r", R_LANGUAGE_CONFIG)
        assert isinstance(result, str)
        assert 'stop("Not implemented")' in result

    def test_generate_stub_python_includes_sentinel(self):
        """generate_stub for Python prepends the language-specific sentinel."""
        parsed = make_python_ast(PYTHON_SIMPLE_FUNC)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        assert PYTHON_SENTINEL in result

    def test_generate_stub_r_includes_sentinel(self):
        """generate_stub for R prepends the language-specific sentinel."""
        parsed = [{"name": "f", "params": ["x"]}]
        result = generate_stub(parsed, "r", R_LANGUAGE_CONFIG)
        assert R_SENTINEL in result

    def test_generate_stub_sentinel_is_verbatim_python(self):
        """The sentinel injected for Python is the exact verbatim string (Bug S3-2, S3-4)."""
        parsed = make_python_ast(PYTHON_SIMPLE_FUNC)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        # The sentinel must appear as-is, character-for-character
        assert PYTHON_SENTINEL in result

    def test_generate_stub_sentinel_is_verbatim_r(self):
        """The sentinel injected for R is the exact verbatim string (Bug S3-2, S3-4)."""
        parsed = [{"name": "f", "params": ["x"]}]
        result = generate_stub(parsed, "r", R_LANGUAGE_CONFIG)
        assert R_SENTINEL in result

    def test_generate_stub_plugin_markdown_bypasses_parsing(self):
        """Plugin dispatch keys bypass signature parsing; None is passed."""
        result = generate_stub(None, "plugin_markdown", PLUGIN_MARKDOWN_CONFIG)
        assert isinstance(result, str)
        assert len(result.strip()) > 0

    def test_generate_stub_plugin_bash_bypasses_parsing(self):
        """plugin_bash bypasses signature parsing entirely."""
        result = generate_stub(None, "plugin_bash", PLUGIN_BASH_CONFIG)
        assert isinstance(result, str)
        assert len(result.strip()) > 0

    def test_generate_stub_plugin_json_bypasses_parsing(self):
        """plugin_json bypasses signature parsing entirely."""
        result = generate_stub(None, "plugin_json", PLUGIN_JSON_CONFIG)
        assert isinstance(result, str)
        assert len(result.strip()) > 0

    def test_generate_stub_stan_template_bypasses_parsing(self):
        """Stan template bypasses signature parsing; None is passed."""
        result = generate_stub(None, "stan", STAN_LANGUAGE_CONFIG)
        assert isinstance(result, str)
        assert len(result.strip()) > 0

    def test_generate_stub_python_result_is_importable(self):
        """The generated Python stub must be importable (valid syntax)."""
        parsed = make_python_ast(PYTHON_TIER2_SOURCE)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        # Compiling should not raise
        compile(result, "<stub>", "exec")

    def test_generate_stub_python_with_asserts_stripped(self):
        """Module-level asserts in Python source are stripped in the stub."""
        parsed = make_python_ast(PYTHON_WITH_ASSERT)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        lines = result.split("\n")
        assert_lines = [l for l in lines if l.strip().startswith("assert ")]
        assert len(assert_lines) == 0

    def test_generate_stub_python_preserves_type_annotations(self):
        """Type annotations in function signatures should be preserved."""
        source = "def compute(x: int, y: float = 0.0) -> str:\n    ...\n"
        parsed = make_python_ast(source)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        assert "int" in result
        assert "str" in result

    def test_generate_stub_python_class_attributes_none(self):
        """Class-level attributes in the stub are set to None."""
        source = textwrap.dedent("""\
            class Config:
                name: str
                count: int
                def method(self) -> None:
                    ...
        """)
        parsed = make_python_ast(source)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        assert "= None" in result

    def test_generate_stub_returns_string_for_all_dispatch_keys(self):
        """generate_stub returns a string for every known dispatch key."""
        # Python
        parsed_py = make_python_ast(PYTHON_SIMPLE_FUNC)
        assert isinstance(
            generate_stub(parsed_py, "python", PYTHON_LANGUAGE_CONFIG), str
        )
        # R
        parsed_r = [{"name": "f", "params": []}]
        assert isinstance(generate_stub(parsed_r, "r", R_LANGUAGE_CONFIG), str)
        # Stan template
        assert isinstance(generate_stub(None, "stan", STAN_LANGUAGE_CONFIG), str)
        # Plugins
        assert isinstance(
            generate_stub(None, "plugin_markdown", PLUGIN_MARKDOWN_CONFIG), str
        )
        assert isinstance(generate_stub(None, "plugin_bash", PLUGIN_BASH_CONFIG), str)
        assert isinstance(generate_stub(None, "plugin_json", PLUGIN_JSON_CONFIG), str)


# ---------------------------------------------------------------------------
# generate_upstream_stubs function
# ---------------------------------------------------------------------------


class TestGenerateUpstreamStubs:
    """Tests for the generate_upstream_stubs function."""

    def _make_blueprint_dir(self, tmp_path, units_content):
        """Create a blueprint directory with contracts and prose files."""
        bp_dir = tmp_path / "blueprint"
        bp_dir.mkdir(exist_ok=True)
        contracts_path = bp_dir / "blueprint_contracts.md"
        contracts_path.write_text(units_content)
        # Prose file can be minimal
        prose_path = bp_dir / "blueprint_prose.md"
        prose_path.write_text("")
        return bp_dir

    def _make_minimal_blueprint(self, tmp_path, unit_numbers):
        """Create a minimal blueprint with Python Tier 2 blocks for given unit numbers."""
        sections = []
        for n in unit_numbers:
            sections.append(
                textwrap.dedent(f"""\
                ## Unit {n}: Unit{n}Name

                ### Tier 2 -- Signatures

                ```python
                def unit_{n}_func(x: int) -> str:
                    ...
                ```

                ### Tier 3 -- Behavioral Contracts

                Dependencies: none.
            """)
            )
        content = "\n".join(sections)
        return self._make_blueprint_dir(tmp_path, content)

    def test_generate_upstream_stubs_creates_output_dir_files(self, tmp_path):
        """generate_upstream_stubs writes stub files to output_dir for each upstream unit."""
        bp_dir = self._make_minimal_blueprint(tmp_path, [1, 2, 5])
        output_dir = tmp_path / "stubs"
        output_dir.mkdir()
        generate_upstream_stubs(
            bp_dir,
            unit_number=5,
            upstream_units=[1, 2],
            output_dir=output_dir,
            language="python",
        )
        # Should have created files for units 1 and 2
        output_files = list(output_dir.iterdir())
        assert len(output_files) >= 2

    def test_generate_upstream_stubs_files_contain_stub_content(self, tmp_path):
        """Generated upstream stub files must contain actual stub code."""
        bp_dir = self._make_minimal_blueprint(tmp_path, [1, 3])
        output_dir = tmp_path / "stubs"
        output_dir.mkdir()
        generate_upstream_stubs(
            bp_dir,
            unit_number=3,
            upstream_units=[1],
            output_dir=output_dir,
            language="python",
        )
        output_files = list(output_dir.iterdir())
        assert len(output_files) >= 1
        content = output_files[0].read_text()
        assert len(content.strip()) > 0

    def test_generate_upstream_stubs_forward_reference_raises_value_error(
        self, tmp_path
    ):
        """Forward reference (dependency >= unit_number) raises ValueError."""
        bp_dir = self._make_minimal_blueprint(tmp_path, [3, 5, 7])
        output_dir = tmp_path / "stubs"
        output_dir.mkdir()
        with pytest.raises(ValueError):
            generate_upstream_stubs(
                bp_dir,
                unit_number=5,
                upstream_units=[7],
                output_dir=output_dir,
                language="python",
            )

    def test_generate_upstream_stubs_equal_unit_number_raises_value_error(
        self, tmp_path
    ):
        """A dependency equal to unit_number is a forward reference and raises ValueError."""
        bp_dir = self._make_minimal_blueprint(tmp_path, [5])
        output_dir = tmp_path / "stubs"
        output_dir.mkdir()
        with pytest.raises(ValueError):
            generate_upstream_stubs(
                bp_dir,
                unit_number=5,
                upstream_units=[5],
                output_dir=output_dir,
                language="python",
            )

    def test_generate_upstream_stubs_all_deps_lower_succeeds(self, tmp_path):
        """All dependencies with lower unit numbers than unit_number succeed."""
        bp_dir = self._make_minimal_blueprint(tmp_path, [1, 2, 3, 10])
        output_dir = tmp_path / "stubs"
        output_dir.mkdir()
        # Should not raise
        generate_upstream_stubs(
            bp_dir,
            unit_number=10,
            upstream_units=[1, 2, 3],
            output_dir=output_dir,
            language="python",
        )

    def test_generate_upstream_stubs_empty_upstream_list(self, tmp_path):
        """Empty upstream list produces no output files and does not raise."""
        bp_dir = self._make_minimal_blueprint(tmp_path, [5])
        output_dir = tmp_path / "stubs"
        output_dir.mkdir()
        generate_upstream_stubs(
            bp_dir,
            unit_number=5,
            upstream_units=[],
            output_dir=output_dir,
            language="python",
        )
        output_files = list(output_dir.iterdir())
        assert len(output_files) == 0

    def test_generate_upstream_stubs_multiple_forward_refs_raises(self, tmp_path):
        """Multiple forward references still raise ValueError."""
        bp_dir = self._make_minimal_blueprint(tmp_path, [1, 8, 9, 5])
        output_dir = tmp_path / "stubs"
        output_dir.mkdir()
        with pytest.raises(ValueError):
            generate_upstream_stubs(
                bp_dir,
                unit_number=5,
                upstream_units=[1, 8, 9],
                output_dir=output_dir,
                language="python",
            )

    def test_generate_upstream_stubs_mixed_valid_and_forward_ref_raises(self, tmp_path):
        """Even one forward reference among valid deps raises ValueError."""
        bp_dir = self._make_minimal_blueprint(tmp_path, [1, 2, 10, 5])
        output_dir = tmp_path / "stubs"
        output_dir.mkdir()
        with pytest.raises(ValueError):
            generate_upstream_stubs(
                bp_dir,
                unit_number=5,
                upstream_units=[1, 2, 10],
                output_dir=output_dir,
                language="python",
            )

    def test_generate_upstream_stubs_writes_to_correct_directory(self, tmp_path):
        """Stub files are written into the specified output_dir, not elsewhere."""
        bp_dir = self._make_minimal_blueprint(tmp_path, [1, 5])
        output_dir = tmp_path / "my_output"
        output_dir.mkdir()
        generate_upstream_stubs(
            bp_dir,
            unit_number=5,
            upstream_units=[1],
            output_dir=output_dir,
            language="python",
        )
        # All generated files should be inside output_dir
        for f in output_dir.iterdir():
            assert f.parent == output_dir


# ---------------------------------------------------------------------------
# main CLI entry point
# ---------------------------------------------------------------------------


class TestMainCLI:
    """Tests for the main CLI entry point."""

    def _make_blueprint_dir(self, tmp_path, units_content):
        """Create a blueprint directory with a contracts file."""
        bp_dir = tmp_path / "blueprint"
        bp_dir.mkdir(exist_ok=True)
        contracts_path = bp_dir / "blueprint_contracts.md"
        contracts_path.write_text(units_content)
        prose_path = bp_dir / "blueprint_prose.md"
        prose_path.write_text("")
        return bp_dir

    def _make_standard_blueprint(self, tmp_path):
        """Create a standard blueprint with units 1, 2, and 5."""
        content = textwrap.dedent("""\
            ## Unit 1: Foundation

            ### Tier 2 -- Signatures

            ```python
            def foundation_func(x: int) -> str:
                ...
            ```

            ### Tier 3 -- Behavioral Contracts

            No dependencies.

            ## Unit 2: Language Registry

            ### Tier 2 -- Signatures

            ```python
            def registry_func(lang: str) -> dict:
                ...
            ```

            ### Tier 3 -- Behavioral Contracts

            Dependencies: Unit 1.

            ## Unit 5: Target Unit

            ### Tier 2 -- Signatures

            ```python
            def target_func(data: list) -> None:
                ...
            ```

            ### Tier 3 -- Behavioral Contracts

            Dependencies: Unit 1, Unit 2.
        """)
        return self._make_blueprint_dir(tmp_path, content)

    def test_main_success_exit_code_zero(self, tmp_path):
        """main exits with code 0 on success."""
        bp_dir = self._make_standard_blueprint(tmp_path)
        output_dir = tmp_path / "output"
        output_dir.mkdir()
        bp_file = bp_dir / "blueprint_contracts.md"
        try:
            main(
                [
                    "--blueprint",
                    str(bp_file),
                    "--unit",
                    "5",
                    "--output-dir",
                    str(output_dir),
                    "--upstream",
                    "1,2",
                ]
            )
        except SystemExit as e:
            assert e.code == 0 or e.code is None

    def test_main_failure_exit_code_one(self, tmp_path):
        """main exits with code 1 on failure."""
        with pytest.raises(SystemExit) as exc_info:
            main(
                [
                    "--blueprint",
                    "/nonexistent/blueprint_contracts.md",
                    "--unit",
                    "5",
                    "--output-dir",
                    str(tmp_path),
                    "--upstream",
                    "1,2",
                ]
            )
        assert exc_info.value.code == 1

    def test_main_accepts_blueprint_argument(self, tmp_path):
        """main accepts --blueprint as a path argument."""
        bp_dir = self._make_standard_blueprint(tmp_path)
        output_dir = tmp_path / "output"
        output_dir.mkdir()
        bp_file = bp_dir / "blueprint_contracts.md"
        try:
            main(
                [
                    "--blueprint",
                    str(bp_file),
                    "--unit",
                    "5",
                    "--output-dir",
                    str(output_dir),
                    "--upstream",
                    "1,2",
                ]
            )
        except SystemExit as e:
            assert e.code == 0 or e.code is None

    def test_main_accepts_unit_argument(self, tmp_path):
        """main accepts --unit as an integer argument."""
        bp_dir = self._make_standard_blueprint(tmp_path)
        output_dir = tmp_path / "output"
        output_dir.mkdir()
        bp_file = bp_dir / "blueprint_contracts.md"
        try:
            main(
                [
                    "--blueprint",
                    str(bp_file),
                    "--unit",
                    "2",
                    "--output-dir",
                    str(output_dir),
                    "--upstream",
                    "1",
                ]
            )
        except SystemExit as e:
            assert e.code == 0 or e.code is None

    def test_main_accepts_output_dir_argument(self, tmp_path):
        """main accepts --output-dir as a path argument."""
        bp_dir = self._make_standard_blueprint(tmp_path)
        output_dir = tmp_path / "custom_output"
        output_dir.mkdir()
        bp_file = bp_dir / "blueprint_contracts.md"
        try:
            main(
                [
                    "--blueprint",
                    str(bp_file),
                    "--unit",
                    "1",
                    "--output-dir",
                    str(output_dir),
                    "--upstream",
                    "",
                ]
            )
        except SystemExit as e:
            assert e.code == 0 or e.code is None

    def test_main_accepts_upstream_comma_separated(self, tmp_path):
        """main accepts --upstream as a comma-separated list of ints."""
        bp_dir = self._make_standard_blueprint(tmp_path)
        output_dir = tmp_path / "output"
        output_dir.mkdir()
        bp_file = bp_dir / "blueprint_contracts.md"
        try:
            main(
                [
                    "--blueprint",
                    str(bp_file),
                    "--unit",
                    "5",
                    "--output-dir",
                    str(output_dir),
                    "--upstream",
                    "1,2",
                ]
            )
        except SystemExit as e:
            assert e.code == 0 or e.code is None

    def test_main_accepts_empty_upstream(self, tmp_path):
        """main accepts --upstream as an empty string for no dependencies."""
        bp_dir = self._make_standard_blueprint(tmp_path)
        output_dir = tmp_path / "output"
        output_dir.mkdir()
        bp_file = bp_dir / "blueprint_contracts.md"
        try:
            main(
                [
                    "--blueprint",
                    str(bp_file),
                    "--unit",
                    "1",
                    "--output-dir",
                    str(output_dir),
                    "--upstream",
                    "",
                ]
            )
        except SystemExit as e:
            assert e.code == 0 or e.code is None

    def test_main_generates_current_unit_stub(self, tmp_path):
        """main generates a stub for the current unit."""
        bp_dir = self._make_standard_blueprint(tmp_path)
        output_dir = tmp_path / "output"
        output_dir.mkdir()
        bp_file = bp_dir / "blueprint_contracts.md"
        try:
            main(
                [
                    "--blueprint",
                    str(bp_file),
                    "--unit",
                    "1",
                    "--output-dir",
                    str(output_dir),
                    "--upstream",
                    "",
                ]
            )
        except SystemExit:
            pass
        # Output directory should contain at least the current unit's stub
        output_files = list(output_dir.iterdir())
        assert len(output_files) >= 1

    def test_main_generates_upstream_stubs(self, tmp_path):
        """main generates upstream stubs for each dependency."""
        bp_dir = self._make_standard_blueprint(tmp_path)
        output_dir = tmp_path / "output"
        output_dir.mkdir()
        bp_file = bp_dir / "blueprint_contracts.md"
        try:
            main(
                [
                    "--blueprint",
                    str(bp_file),
                    "--unit",
                    "5",
                    "--output-dir",
                    str(output_dir),
                    "--upstream",
                    "1,2",
                ]
            )
        except SystemExit:
            pass
        # Should have stubs for units 1, 2, and 5 (current + upstream)
        output_files = list(output_dir.iterdir())
        assert len(output_files) >= 3

    def test_main_default_argv_is_none(self):
        """main with no arguments defaults to reading sys.argv."""
        with patch(
            "sys.argv",
            [
                "prog",
                "--blueprint",
                "/dev/null",
                "--unit",
                "1",
                "--output-dir",
                "/tmp",
                "--upstream",
                "",
            ],
        ):
            try:
                main()
            except (SystemExit, Exception):
                pass  # Expected -- /dev/null is not a valid blueprint

    def test_main_forward_reference_in_upstream_exits_one(self, tmp_path):
        """main with a forward reference in upstream exits with code 1."""
        bp_dir = self._make_standard_blueprint(tmp_path)
        output_dir = tmp_path / "output"
        output_dir.mkdir()
        bp_file = bp_dir / "blueprint_contracts.md"
        with pytest.raises(SystemExit) as exc_info:
            main(
                [
                    "--blueprint",
                    str(bp_file),
                    "--unit",
                    "1",
                    "--output-dir",
                    str(output_dir),
                    "--upstream",
                    "5",
                ]
            )
        assert exc_info.value.code == 1

    def test_main_nonexistent_blueprint_exits_one(self, tmp_path):
        """main with a nonexistent blueprint path exits with code 1."""
        output_dir = tmp_path / "output"
        output_dir.mkdir()
        with pytest.raises(SystemExit) as exc_info:
            main(
                [
                    "--blueprint",
                    "/nonexistent/path/blueprint_contracts.md",
                    "--unit",
                    "1",
                    "--output-dir",
                    str(output_dir),
                    "--upstream",
                    "",
                ]
            )
        assert exc_info.value.code == 1


# ---------------------------------------------------------------------------
# Sentinel injection invariant (Bug S3-2, S3-4)
# ---------------------------------------------------------------------------


class TestSentinelInjectionInvariant:
    """Tests verifying the sentinel injection invariant (Bug S3-2, S3-4).

    The sentinel string MUST be the exact value from LANGUAGE_REGISTRY,
    injected verbatim. No reformatting, abbreviation, or improvisation.
    """

    def test_python_sentinel_exact_match(self):
        """Python stub sentinel matches the exact LANGUAGE_REGISTRY value character-by-character."""
        parsed = make_python_ast(PYTHON_SIMPLE_FUNC)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        # Find the sentinel line in the output
        found = False
        for line in result.split("\n"):
            if PYTHON_SENTINEL in line:
                found = True
                break
        assert found, "Python sentinel not found verbatim in stub output"

    def test_r_sentinel_exact_match(self):
        """R stub sentinel matches the exact LANGUAGE_REGISTRY value character-by-character."""
        parsed = [{"name": "f", "params": []}]
        result = generate_stub(parsed, "r", R_LANGUAGE_CONFIG)
        found = False
        for line in result.split("\n"):
            if R_SENTINEL in line:
                found = True
                break
        assert found, "R sentinel not found verbatim in stub output"

    def test_python_sentinel_not_abbreviated(self):
        """Python sentinel is not an abbreviated version (must contain full text)."""
        parsed = make_python_ast(PYTHON_SIMPLE_FUNC)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        # The full sentinel includes "DO NOT DELIVER"
        assert "DO NOT DELIVER" in result
        assert "stub file generated by SVP" in result

    def test_r_sentinel_not_abbreviated(self):
        """R sentinel is not an abbreviated version (must contain full text)."""
        parsed = [{"name": "f", "params": []}]
        result = generate_stub(parsed, "r", R_LANGUAGE_CONFIG)
        assert "DO NOT DELIVER" in result
        assert "stub file generated by SVP" in result

    def test_python_sentinel_not_reformatted(self):
        """Python sentinel is not reformatted (e.g., no extra quotes or comment wrapping)."""
        parsed = make_python_ast(PYTHON_SIMPLE_FUNC)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        # The Python sentinel is a statement, not a comment
        assert "__SVP_STUB__ = True" in result
        # Should not be wrapped in quotes or turned into a comment
        sentinel_lines = [l for l in result.split("\n") if "__SVP_STUB__" in l]
        assert len(sentinel_lines) >= 1
        for line in sentinel_lines:
            stripped = line.strip()
            assert not stripped.startswith("#"), (
                "Python sentinel should not be a comment"
            )
            assert not stripped.startswith('"'), (
                "Python sentinel should not be a string literal"
            )
            assert not stripped.startswith("'"), (
                "Python sentinel should not be a string literal"
            )

    def test_r_sentinel_is_comment_format(self):
        """R sentinel must be in comment format (starts with #)."""
        parsed = [{"name": "f", "params": []}]
        result = generate_stub(parsed, "r", R_LANGUAGE_CONFIG)
        sentinel_lines = [l for l in result.split("\n") if "__SVP_STUB__" in l]
        assert len(sentinel_lines) >= 1
        for line in sentinel_lines:
            assert line.strip().startswith("#"), "R sentinel must be a comment"

    def test_sentinel_from_config_is_used_not_hardcoded(self):
        """The sentinel comes from the config, not hardcoded in the generator."""
        custom_sentinel = "__CUSTOM_STUB__ = True  # CUSTOM SENTINEL FOR TESTING"
        custom_config = {
            **PYTHON_LANGUAGE_CONFIG,
            "stub_sentinel": custom_sentinel,
        }
        parsed = make_python_ast(PYTHON_SIMPLE_FUNC)
        result = generate_stub(parsed, "python", custom_config)
        # Should use the config sentinel, not a hardcoded one
        assert custom_sentinel in result


# ---------------------------------------------------------------------------
# generate_stub dispatch correctness
# ---------------------------------------------------------------------------


class TestGenerateStubDispatchCorrectness:
    """Tests verifying that generate_stub dispatches correctly per language_config."""

    def test_dispatch_uses_stub_generator_key(self):
        """generate_stub uses language_config['stub_generator_key'] for dispatch."""
        # Python config has stub_generator_key="python"
        parsed = make_python_ast(PYTHON_SIMPLE_FUNC)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        # Python generator produces raise NotImplementedError()
        assert "raise NotImplementedError()" in result

    def test_dispatch_stan_template_via_config_key(self):
        """Stan config with stub_generator_key='stan_template' dispatches to stan generator."""
        result = generate_stub(None, "stan", STAN_LANGUAGE_CONFIG)
        assert isinstance(result, str)
        assert len(result.strip()) > 0

    def test_dispatch_plugin_markdown_via_config_key(self):
        """Plugin markdown config dispatches to plugin_markdown generator."""
        result = generate_stub(None, "plugin_markdown", PLUGIN_MARKDOWN_CONFIG)
        assert isinstance(result, str)

    def test_dispatch_plugin_bash_via_config_key(self):
        """Plugin bash config dispatches to plugin_bash generator."""
        result = generate_stub(None, "plugin_bash", PLUGIN_BASH_CONFIG)
        assert isinstance(result, str)

    def test_dispatch_plugin_json_via_config_key(self):
        """Plugin json config dispatches to plugin_json generator."""
        result = generate_stub(None, "plugin_json", PLUGIN_JSON_CONFIG)
        assert isinstance(result, str)

    def test_python_full_language_stub_is_importable(self):
        """Full Python stub is importable without error."""
        parsed = make_python_ast(PYTHON_TIER2_SOURCE)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        # Compile to verify importability
        compile(result, "<test_stub>", "exec")

    def test_plugin_and_component_no_sentinel_required(self):
        """Plugin and component stubs do not require full-language sentinels.

        Only full-language code languages (Python, R) prepend sentinels.
        Stan templates and plugins may have their own sentinel conventions
        but are not required to use LANGUAGE_REGISTRY sentinels.
        """
        stan_result = generate_stub(None, "stan", STAN_LANGUAGE_CONFIG)
        md_result = generate_stub(None, "plugin_markdown", PLUGIN_MARKDOWN_CONFIG)
        # These should be valid output but not necessarily contain Python/R sentinels
        assert isinstance(stan_result, str)
        assert isinstance(md_result, str)


# ---------------------------------------------------------------------------
# Edge cases and robustness
# ---------------------------------------------------------------------------


class TestEdgeCases:
    """Tests for edge cases in stub generation."""

    def test_python_stub_from_empty_source(self):
        """An empty Python source produces a stub with at least the sentinel."""
        parsed = make_python_ast("")
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        assert PYTHON_SENTINEL in result

    def test_python_stub_imports_only(self):
        """Source with only imports produces a stub with imports and sentinel."""
        source = "from typing import Any, Dict\nimport os\n"
        parsed = make_python_ast(source)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        assert PYTHON_SENTINEL in result

    def test_python_stub_single_constant(self):
        """Source with a single constant assignment produces a valid stub."""
        source = "REGISTRY: dict\n"
        parsed = make_python_ast(source)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        assert isinstance(result, str)
        assert PYTHON_SENTINEL in result

    def test_python_stub_mixed_content(self):
        """Source with imports, constants, functions, and classes produces valid stub."""
        parsed = make_python_ast(PYTHON_TIER2_SOURCE)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        assert PYTHON_SENTINEL in result
        assert "raise NotImplementedError()" in result
        assert "class DataProcessor" in result
        assert "def process_data" in result

    def test_r_stub_empty_function_list(self):
        """An empty R function list produces a stub with at least the sentinel."""
        parsed = []
        result = generate_stub(parsed, "r", R_LANGUAGE_CONFIG)
        assert R_SENTINEL in result

    def test_python_stub_namedtuple_class(self):
        """A NamedTuple class in Python produces a valid stub."""
        source = textwrap.dedent("""\
            from typing import NamedTuple

            class Result(NamedTuple):
                status: str
                value: int
        """)
        parsed = make_python_ast(source)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        assert isinstance(result, str)
        assert "Result" in result

    def test_python_stub_dataclass(self):
        """A dataclass in Python produces a valid stub."""
        source = textwrap.dedent("""\
            from dataclasses import dataclass

            @dataclass
            class Config:
                name: str
                value: int
        """)
        parsed = make_python_ast(source)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        assert isinstance(result, str)
        assert "Config" in result

    def test_python_stub_function_with_default_values(self):
        """Functions with default parameter values produce valid stubs."""
        source = "def setup(name: str = 'default', count: int = 0) -> None:\n    ...\n"
        parsed = make_python_ast(source)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        assert "def setup" in result
        assert "raise NotImplementedError()" in result

    def test_python_stub_with_starred_args(self):
        """Functions with *args and **kwargs produce valid stubs."""
        source = "def flexible(*args, **kwargs) -> None:\n    ...\n"
        parsed = make_python_ast(source)
        result = generate_stub(parsed, "python", PYTHON_LANGUAGE_CONFIG)
        assert "def flexible" in result
        assert "raise NotImplementedError()" in result

    def test_plugin_json_stub_is_parseable_json(self):
        """plugin_json stub must be parseable as valid JSON."""
        import json

        result = generate_stub(None, "plugin_json", PLUGIN_JSON_CONFIG)
        parsed = json.loads(result)
        assert parsed is not None

    def test_generate_stub_r_single_function_with_many_params(self):
        """R stub handles a function with many parameters."""
        parsed = [{"name": "big_func", "params": ["a", "b", "c", "d", "e"]}]
        result = generate_stub(parsed, "r", R_LANGUAGE_CONFIG)
        assert "big_func" in result
        assert 'stop("Not implemented")' in result


# ---------------------------------------------------------------------------
# Forward-reference guard detailed tests
# ---------------------------------------------------------------------------


class TestForwardReferenceGuard:
    """Detailed tests for the forward-reference guard in generate_upstream_stubs."""

    def _make_minimal_blueprint(self, tmp_path, unit_numbers):
        """Create a minimal blueprint with Python Tier 2 blocks."""
        sections = []
        for n in unit_numbers:
            sections.append(
                textwrap.dedent(f"""\
                ## Unit {n}: Unit{n}

                ### Tier 2 -- Signatures

                ```python
                def unit_{n}_func() -> None:
                    ...
                ```

                ### Tier 3 -- Behavioral Contracts

                No deps.
            """)
            )
        content = "\n".join(sections)
        bp_dir = tmp_path / "blueprint"
        bp_dir.mkdir(exist_ok=True)
        (bp_dir / "blueprint_contracts.md").write_text(content)
        (bp_dir / "blueprint_prose.md").write_text("")
        return bp_dir

    def test_forward_ref_unit_number_plus_one(self, tmp_path):
        """Dependency exactly one above unit_number is a forward reference."""
        bp_dir = self._make_minimal_blueprint(tmp_path, [5, 6])
        output_dir = tmp_path / "out"
        output_dir.mkdir()
        with pytest.raises(ValueError):
            generate_upstream_stubs(
                bp_dir,
                unit_number=5,
                upstream_units=[6],
                output_dir=output_dir,
                language="python",
            )

    def test_backward_ref_unit_number_minus_one_succeeds(self, tmp_path):
        """Dependency exactly one below unit_number succeeds."""
        bp_dir = self._make_minimal_blueprint(tmp_path, [4, 5])
        output_dir = tmp_path / "out"
        output_dir.mkdir()
        generate_upstream_stubs(
            bp_dir,
            unit_number=5,
            upstream_units=[4],
            output_dir=output_dir,
            language="python",
        )
        assert len(list(output_dir.iterdir())) >= 1

    def test_forward_ref_large_gap(self, tmp_path):
        """Dependency far above unit_number is still caught as a forward reference."""
        bp_dir = self._make_minimal_blueprint(tmp_path, [1, 100])
        output_dir = tmp_path / "out"
        output_dir.mkdir()
        with pytest.raises(ValueError):
            generate_upstream_stubs(
                bp_dir,
                unit_number=1,
                upstream_units=[100],
                output_dir=output_dir,
                language="python",
            )

    def test_multiple_valid_backward_refs(self, tmp_path):
        """Multiple valid backward references all succeed."""
        bp_dir = self._make_minimal_blueprint(tmp_path, [1, 2, 3, 4, 10])
        output_dir = tmp_path / "out"
        output_dir.mkdir()
        generate_upstream_stubs(
            bp_dir,
            unit_number=10,
            upstream_units=[1, 2, 3, 4],
            output_dir=output_dir,
            language="python",
        )
        assert len(list(output_dir.iterdir())) >= 4

    def test_single_forward_ref_among_valid_raises(self, tmp_path):
        """A single forward reference among otherwise valid deps raises ValueError."""
        bp_dir = self._make_minimal_blueprint(tmp_path, [1, 2, 3, 15, 10])
        output_dir = tmp_path / "out"
        output_dir.mkdir()
        with pytest.raises(ValueError):
            generate_upstream_stubs(
                bp_dir,
                unit_number=10,
                upstream_units=[1, 2, 3, 15],
                output_dir=output_dir,
                language="python",
            )
