"""
Test suite for Unit 3: Profile Schema.

SVP 2.2 Pass 2 -- Generated by Test Agent.

Synthetic Data Assumptions:
    - project_profile.json files are created in temporary directories via tmp_path.
    - LANGUAGE_REGISTRY entries for "python" and "r" follow the structure defined in
      Unit 2 blueprint contracts, using representative subsets of keys.
    - DEFAULT_PROFILE is expected to contain all top-level keys: archetype, language,
      delivery, quality, testing, readme, license, vcs, pipeline.
    - Delivery and quality sections in DEFAULT_PROFILE are language-keyed dicts,
      keyed by "python" by default.
    - Mixed archetype profiles include both "python" and "r" language keys.
    - SVP 2.1 migration test data uses flat (non-language-keyed) delivery/quality dicts.
    - Validation tests construct language_registry dicts with valid_linters,
      valid_formatters, valid_type_checkers, and valid_source_layouts sets as
      defined in the Unit 2 contracts.
"""

import json

import pytest

from profile_schema import (
    DEFAULT_PROFILE,
    get_delivery_config,
    get_quality_config,
    load_profile,
    validate_profile,
)

# ---------------------------------------------------------------------------
# Fixtures: synthetic language registry data
# ---------------------------------------------------------------------------


@pytest.fixture
def python_registry_entry():
    """Minimal Python language registry entry matching Unit 2 contracts."""
    return {
        "id": "python",
        "display_name": "Python",
        "file_extension": ".py",
        "source_dir": "src",
        "test_dir": "tests",
        "is_component_only": False,
        "compatible_hosts": [],
        "default_delivery": {
            "environment_recommendation": "conda",
            "dependency_format": "environment.yml",
            "source_layout": "conventional",
            "entry_points": False,
        },
        "default_quality": {
            "linter": "ruff",
            "formatter": "ruff",
            "type_checker": "mypy",
            "import_sorter": "ruff",
            "line_length": 88,
        },
        "valid_linters": {"ruff", "flake8", "pylint", "none"},
        "valid_formatters": {"ruff", "black", "autopep8", "none"},
        "valid_type_checkers": {"mypy", "pyright", "none"},
        "valid_source_layouts": ["conventional", "flat", "svp_native"],
    }


@pytest.fixture
def r_registry_entry():
    """Minimal R language registry entry matching Unit 2 contracts."""
    return {
        "id": "r",
        "display_name": "R",
        "file_extension": ".R",
        "source_dir": "R",
        "test_dir": "tests/testthat",
        "is_component_only": False,
        "compatible_hosts": [],
        "default_delivery": {
            "environment_recommendation": "renv",
            "dependency_format": "renv.lock",
            "source_layout": "package",
            "entry_points": False,
        },
        "default_quality": {
            "linter": "lintr",
            "formatter": "styler",
            "type_checker": "none",
            "line_length": 80,
        },
        "valid_linters": {"lintr", "none"},
        "valid_formatters": {"styler", "none"},
        "valid_type_checkers": {"none"},
        "valid_source_layouts": ["package", "scripts"],
    }


@pytest.fixture
def language_registry(python_registry_entry, r_registry_entry):
    """Full language registry with python and r entries."""
    return {
        "python": python_registry_entry,
        "r": r_registry_entry,
    }


@pytest.fixture
def minimal_valid_profile():
    """A minimal valid profile for a python_project archetype."""
    return {
        "archetype": "python_project",
        "language": {
            "primary": "python",
            "components": [],
            "communication": {},
            "notebooks": None,
        },
        "delivery": {
            "python": {
                "environment_recommendation": "conda",
                "dependency_format": "environment.yml",
                "source_layout": "conventional",
                "entry_points": False,
            },
        },
        "quality": {
            "python": {
                "linter": "ruff",
                "formatter": "ruff",
                "type_checker": "mypy",
                "import_sorter": "ruff",
                "line_length": 88,
            },
        },
        "testing": {},
        "readme": {},
        "license": {},
        "vcs": {},
        "pipeline": {},
    }


@pytest.fixture
def mixed_valid_profile():
    """A valid profile for the mixed archetype with both python and r."""
    return {
        "archetype": "mixed",
        "language": {
            "primary": "python",
            "components": [],
            "communication": {},
            "notebooks": None,
        },
        "delivery": {
            "python": {
                "environment_recommendation": "conda",
                "dependency_format": "environment.yml",
                "source_layout": "conventional",
                "entry_points": False,
            },
            "r": {
                "environment_recommendation": "conda",
                "dependency_format": "environment.yml",
                "source_layout": "package",
                "entry_points": False,
            },
        },
        "quality": {
            "python": {
                "linter": "ruff",
                "formatter": "ruff",
                "type_checker": "mypy",
                "import_sorter": "ruff",
                "line_length": 88,
            },
            "r": {
                "linter": "lintr",
                "formatter": "styler",
                "type_checker": "none",
                "line_length": 80,
            },
        },
        "testing": {},
        "readme": {},
        "license": {},
        "vcs": {},
        "pipeline": {},
    }


def write_profile(tmp_path, profile_data):
    """Helper: write a project_profile.json to the given directory."""
    profile_path = tmp_path / "project_profile.json"
    profile_path.write_text(json.dumps(profile_data, indent=2))
    return profile_path


# ===========================================================================
# DEFAULT_PROFILE tests
# ===========================================================================


class TestDefaultProfileStructure:
    def test_default_profile_contains_all_top_level_keys(self):
        expected_keys = {
            "archetype",
            "language",
            "delivery",
            "quality",
            "testing",
            "readme",
            "license",
            "vcs",
            "pipeline",
        }
        assert expected_keys.issubset(set(DEFAULT_PROFILE.keys())), (
            f"Missing top-level keys: {expected_keys - set(DEFAULT_PROFILE.keys())}"
        )

    def test_default_archetype_is_python_project(self):
        assert DEFAULT_PROFILE["archetype"] == "python_project"

    def test_default_language_primary_is_python(self):
        lang = DEFAULT_PROFILE["language"]
        assert lang["primary"] == "python"

    def test_default_language_has_expected_subkeys(self):
        lang = DEFAULT_PROFILE["language"]
        assert "primary" in lang
        assert "components" in lang
        assert "communication" in lang
        assert "notebooks" in lang

    def test_default_language_components_is_empty_list(self):
        assert DEFAULT_PROFILE["language"]["components"] == []

    def test_default_language_communication_is_empty_dict(self):
        assert DEFAULT_PROFILE["language"]["communication"] == {}

    def test_default_language_notebooks_is_none(self):
        assert DEFAULT_PROFILE["language"]["notebooks"] is None

    def test_default_delivery_is_language_keyed(self):
        delivery = DEFAULT_PROFILE["delivery"]
        assert isinstance(delivery, dict)
        assert "python" in delivery

    def test_default_quality_is_language_keyed(self):
        quality = DEFAULT_PROFILE["quality"]
        assert isinstance(quality, dict)
        assert "python" in quality

    def test_default_delivery_python_matches_registry_defaults(self):
        delivery_python = DEFAULT_PROFILE["delivery"]["python"]
        assert delivery_python["environment_recommendation"] == "conda"
        assert delivery_python["dependency_format"] == "environment.yml"
        assert delivery_python["source_layout"] == "conventional"
        assert delivery_python["entry_points"] is False

    def test_default_quality_python_matches_registry_defaults(self):
        quality_python = DEFAULT_PROFILE["quality"]["python"]
        assert quality_python["linter"] == "ruff"
        assert quality_python["formatter"] == "ruff"
        assert quality_python["type_checker"] == "mypy"
        assert quality_python["line_length"] == 88

    def test_default_profile_includes_requires_statistical_analysis(self):
        """Bug S3-164: DEFAULT_PROFILE has the new top-level
        requires_statistical_analysis field defaulting to False."""
        assert "requires_statistical_analysis" in DEFAULT_PROFILE
        assert DEFAULT_PROFILE["requires_statistical_analysis"] is False


# ===========================================================================
# load_profile tests
# ===========================================================================


class TestLoadProfileFileHandling:
    def test_load_profile_reads_project_profile_json(
        self, tmp_path, minimal_valid_profile
    ):
        write_profile(tmp_path, minimal_valid_profile)
        result = load_profile(tmp_path)
        assert result["archetype"] == "python_project"

    def test_load_profile_raises_file_not_found_when_absent(self, tmp_path):
        with pytest.raises(FileNotFoundError):
            load_profile(tmp_path)

    def test_load_profile_reads_from_correct_filename(
        self, tmp_path, minimal_valid_profile
    ):
        write_profile(tmp_path, minimal_valid_profile)
        # Verify it reads project_profile.json specifically
        result = load_profile(tmp_path)
        assert isinstance(result, dict)


class TestLoadProfileDeepMerge:
    def test_load_profile_merges_with_default_profile(self, tmp_path):
        # Write a partial profile -- missing several top-level keys
        partial_profile = {
            "archetype": "python_project",
            "language": {"primary": "python"},
        }
        write_profile(tmp_path, partial_profile)
        result = load_profile(tmp_path)
        # All default keys should be present after merge
        for key in (
            "archetype",
            "language",
            "delivery",
            "quality",
            "testing",
            "readme",
            "license",
            "vcs",
            "pipeline",
        ):
            assert key in result, f"Missing key after merge: {key}"

    def test_user_values_override_defaults(self, tmp_path):
        custom_profile = {
            "archetype": "r_project",
            "language": {
                "primary": "python",
                "components": [],
                "communication": {},
                "notebooks": None,
            },
        }
        write_profile(tmp_path, custom_profile)
        result = load_profile(tmp_path)
        assert result["archetype"] == "r_project"

    def test_deep_merge_preserves_nested_user_overrides(self, tmp_path):
        custom_profile = {
            "language": {
                "primary": "python",
                "components": ["stan"],
                "communication": {},
                "notebooks": None,
            },
        }
        write_profile(tmp_path, custom_profile)
        result = load_profile(tmp_path)
        assert result["language"]["components"] == ["stan"]

    def test_deep_merge_fills_missing_nested_defaults(self, tmp_path):
        # Only set archetype; language and delivery should come from defaults
        write_profile(tmp_path, {"archetype": "python_project"})
        result = load_profile(tmp_path)
        assert "primary" in result["language"]
        assert result["language"]["primary"] == "python"


class TestLoadProfileSvp21Migration:
    def test_flat_delivery_wraps_under_primary_language(self, tmp_path):
        """SVP 2.1 migration: flat delivery dict wraps under language.primary key."""
        legacy_profile = {
            "archetype": "python_project",
            "language": {
                "primary": "python",
                "components": [],
                "communication": {},
                "notebooks": None,
            },
            "delivery": {
                "environment_recommendation": "conda",
                "dependency_format": "environment.yml",
                "source_layout": "flat",
                "entry_points": False,
            },
        }
        write_profile(tmp_path, legacy_profile)
        result = load_profile(tmp_path)
        # Delivery should now be language-keyed
        assert "python" in result["delivery"]
        assert result["delivery"]["python"]["source_layout"] == "flat"

    def test_flat_quality_wraps_under_primary_language(self, tmp_path):
        """SVP 2.1 migration: flat quality dict wraps under language.primary key."""
        legacy_profile = {
            "archetype": "python_project",
            "language": {
                "primary": "python",
                "components": [],
                "communication": {},
                "notebooks": None,
            },
            "quality": {
                "linter": "flake8",
                "formatter": "black",
                "type_checker": "mypy",
                "line_length": 100,
            },
        }
        write_profile(tmp_path, legacy_profile)
        result = load_profile(tmp_path)
        # Quality should now be language-keyed
        assert "python" in result["quality"]
        assert result["quality"]["python"]["linter"] == "flake8"

    def test_already_language_keyed_delivery_not_double_wrapped(
        self, tmp_path, minimal_valid_profile
    ):
        """Delivery that is already language-keyed should not be wrapped again."""
        write_profile(tmp_path, minimal_valid_profile)
        result = load_profile(tmp_path)
        assert "python" in result["delivery"]
        # Should not have a nested "python" under the python key
        python_delivery = result["delivery"]["python"]
        assert "environment_recommendation" in python_delivery

    def test_already_language_keyed_quality_not_double_wrapped(
        self, tmp_path, minimal_valid_profile
    ):
        """Quality that is already language-keyed should not be wrapped again."""
        write_profile(tmp_path, minimal_valid_profile)
        result = load_profile(tmp_path)
        assert "python" in result["quality"]
        python_quality = result["quality"]["python"]
        assert "linter" in python_quality


class TestLoadProfileSvpBuildArchetypes:
    def test_svp_language_extension_sets_is_svp_build_true(self, tmp_path):
        profile = {
            "archetype": "svp_language_extension",
            "language": {
                "primary": "python",
                "components": [],
                "communication": {},
                "notebooks": None,
            },
        }
        write_profile(tmp_path, profile)
        result = load_profile(tmp_path)
        assert result["is_svp_build"] is True

    def test_svp_architectural_sets_is_svp_build_true(self, tmp_path):
        profile = {
            "archetype": "svp_architectural",
            "language": {
                "primary": "python",
                "components": [],
                "communication": {},
                "notebooks": None,
            },
        }
        write_profile(tmp_path, profile)
        result = load_profile(tmp_path)
        assert result["is_svp_build"] is True

    def test_svp_language_extension_sets_self_build_scope(self, tmp_path):
        profile = {
            "archetype": "svp_language_extension",
            "language": {
                "primary": "python",
                "components": [],
                "communication": {},
                "notebooks": None,
            },
        }
        write_profile(tmp_path, profile)
        result = load_profile(tmp_path)
        assert "self_build_scope" in result

    def test_svp_architectural_sets_self_build_scope(self, tmp_path):
        profile = {
            "archetype": "svp_architectural",
            "language": {
                "primary": "python",
                "components": [],
                "communication": {},
                "notebooks": None,
            },
        }
        write_profile(tmp_path, profile)
        result = load_profile(tmp_path)
        assert "self_build_scope" in result

    def test_python_project_does_not_set_is_svp_build(
        self, tmp_path, minimal_valid_profile
    ):
        write_profile(tmp_path, minimal_valid_profile)
        result = load_profile(tmp_path)
        # Either key is absent or it's False
        assert result.get("is_svp_build", False) is False

    def test_is_svp_build_derived_from_archetype_not_independently_set(self, tmp_path):
        """is_svp_build and self_build_scope are derived from archetype,
        never independently settable."""
        profile = {
            "archetype": "python_project",
            "language": {
                "primary": "python",
                "components": [],
                "communication": {},
                "notebooks": None,
            },
            "is_svp_build": True,  # Attempting to force it
            "self_build_scope": "full",
        }
        write_profile(tmp_path, profile)
        result = load_profile(tmp_path)
        # Because archetype is python_project, is_svp_build must not be True
        assert result.get("is_svp_build", False) is False


# ===========================================================================
# validate_profile tests
# ===========================================================================


class TestValidateProfileArchetype:
    def test_valid_archetype_python_project(
        self, minimal_valid_profile, language_registry
    ):
        errors = validate_profile(minimal_valid_profile, language_registry)
        archetype_errors = [e for e in errors if "archetype" in e.lower()]
        assert len(archetype_errors) == 0

    def test_valid_archetype_r_project(self, language_registry):
        profile = {
            "archetype": "r_project",
            "language": {
                "primary": "r",
                "components": [],
                "communication": {},
                "notebooks": None,
            },
            "delivery": {
                "r": {
                    "environment_recommendation": "renv",
                    "dependency_format": "renv.lock",
                    "source_layout": "package",
                    "entry_points": False,
                }
            },
            "quality": {
                "r": {
                    "linter": "lintr",
                    "formatter": "styler",
                    "type_checker": "none",
                    "line_length": 80,
                }
            },
        }
        errors = validate_profile(profile, language_registry)
        archetype_errors = [e for e in errors if "archetype" in e.lower()]
        assert len(archetype_errors) == 0

    def test_valid_archetype_claude_code_plugin(self, language_registry):
        profile = {
            "archetype": "claude_code_plugin",
            "language": {
                "primary": "python",
                "components": [],
                "communication": {},
                "notebooks": None,
            },
            "delivery": {
                "python": {
                    "environment_recommendation": "conda",
                    "dependency_format": "environment.yml",
                    "source_layout": "conventional",
                    "entry_points": False,
                }
            },
            "quality": {
                "python": {
                    "linter": "ruff",
                    "formatter": "ruff",
                    "type_checker": "mypy",
                    "import_sorter": "ruff",
                    "line_length": 88,
                }
            },
        }
        errors = validate_profile(profile, language_registry)
        archetype_errors = [e for e in errors if "archetype" in e.lower()]
        assert len(archetype_errors) == 0

    def test_valid_archetype_mixed(self, mixed_valid_profile, language_registry):
        errors = validate_profile(mixed_valid_profile, language_registry)
        archetype_errors = [e for e in errors if "archetype" in e.lower()]
        assert len(archetype_errors) == 0

    def test_valid_archetype_svp_language_extension(self, language_registry):
        profile = {
            "archetype": "svp_language_extension",
            "language": {
                "primary": "python",
                "components": [],
                "communication": {},
                "notebooks": None,
            },
            "delivery": {
                "python": {
                    "environment_recommendation": "conda",
                    "dependency_format": "environment.yml",
                    "source_layout": "conventional",
                    "entry_points": False,
                }
            },
            "quality": {
                "python": {
                    "linter": "ruff",
                    "formatter": "ruff",
                    "type_checker": "mypy",
                    "import_sorter": "ruff",
                    "line_length": 88,
                }
            },
        }
        errors = validate_profile(profile, language_registry)
        archetype_errors = [e for e in errors if "archetype" in e.lower()]
        assert len(archetype_errors) == 0

    def test_valid_archetype_svp_architectural(self, language_registry):
        profile = {
            "archetype": "svp_architectural",
            "language": {
                "primary": "python",
                "components": [],
                "communication": {},
                "notebooks": None,
            },
            "delivery": {
                "python": {
                    "environment_recommendation": "conda",
                    "dependency_format": "environment.yml",
                    "source_layout": "conventional",
                    "entry_points": False,
                }
            },
            "quality": {
                "python": {
                    "linter": "ruff",
                    "formatter": "ruff",
                    "type_checker": "mypy",
                    "import_sorter": "ruff",
                    "line_length": 88,
                }
            },
        }
        errors = validate_profile(profile, language_registry)
        archetype_errors = [e for e in errors if "archetype" in e.lower()]
        assert len(archetype_errors) == 0

    def test_invalid_archetype_produces_error(self, language_registry):
        profile = {
            "archetype": "nonexistent_archetype",
            "language": {
                "primary": "python",
                "components": [],
                "communication": {},
                "notebooks": None,
            },
            "delivery": {"python": {}},
            "quality": {"python": {}},
        }
        errors = validate_profile(profile, language_registry)
        assert any("archetype" in e.lower() for e in errors)


class TestValidateProfileLanguage:
    def test_primary_language_in_registry_is_valid(
        self, minimal_valid_profile, language_registry
    ):
        errors = validate_profile(minimal_valid_profile, language_registry)
        lang_errors = [
            e for e in errors if "language" in e.lower() and "primary" in e.lower()
        ]
        assert len(lang_errors) == 0

    def test_primary_language_not_in_registry_produces_error(self, language_registry):
        profile = {
            "archetype": "python_project",
            "language": {
                "primary": "julia",
                "components": [],
                "communication": {},
                "notebooks": None,
            },
            "delivery": {"julia": {}},
            "quality": {"julia": {}},
        }
        errors = validate_profile(profile, language_registry)
        assert len(errors) > 0


class TestValidateProfileToolChoices:
    def test_valid_linter_choice_no_error(
        self, minimal_valid_profile, language_registry
    ):
        errors = validate_profile(minimal_valid_profile, language_registry)
        linter_errors = [e for e in errors if "linter" in e.lower()]
        assert len(linter_errors) == 0

    def test_invalid_linter_choice_produces_error(self, language_registry):
        profile = {
            "archetype": "python_project",
            "language": {
                "primary": "python",
                "components": [],
                "communication": {},
                "notebooks": None,
            },
            "delivery": {
                "python": {
                    "environment_recommendation": "conda",
                    "dependency_format": "environment.yml",
                    "source_layout": "conventional",
                    "entry_points": False,
                }
            },
            "quality": {
                "python": {
                    "linter": "invalid_linter",
                    "formatter": "ruff",
                    "type_checker": "mypy",
                    "import_sorter": "ruff",
                    "line_length": 88,
                }
            },
        }
        errors = validate_profile(profile, language_registry)
        assert any("linter" in e.lower() for e in errors)

    def test_invalid_formatter_choice_produces_error(self, language_registry):
        profile = {
            "archetype": "python_project",
            "language": {
                "primary": "python",
                "components": [],
                "communication": {},
                "notebooks": None,
            },
            "delivery": {
                "python": {
                    "environment_recommendation": "conda",
                    "dependency_format": "environment.yml",
                    "source_layout": "conventional",
                    "entry_points": False,
                }
            },
            "quality": {
                "python": {
                    "linter": "ruff",
                    "formatter": "invalid_formatter",
                    "type_checker": "mypy",
                    "import_sorter": "ruff",
                    "line_length": 88,
                }
            },
        }
        errors = validate_profile(profile, language_registry)
        assert any("formatter" in e.lower() for e in errors)

    def test_invalid_type_checker_choice_produces_error(self, language_registry):
        profile = {
            "archetype": "python_project",
            "language": {
                "primary": "python",
                "components": [],
                "communication": {},
                "notebooks": None,
            },
            "delivery": {
                "python": {
                    "environment_recommendation": "conda",
                    "dependency_format": "environment.yml",
                    "source_layout": "conventional",
                    "entry_points": False,
                }
            },
            "quality": {
                "python": {
                    "linter": "ruff",
                    "formatter": "ruff",
                    "type_checker": "invalid_checker",
                    "import_sorter": "ruff",
                    "line_length": 88,
                }
            },
        }
        errors = validate_profile(profile, language_registry)
        assert any(
            "type_checker" in e.lower() or "type checker" in e.lower() for e in errors
        )

    def test_all_valid_python_linters_accepted(self, language_registry):
        for linter in ("ruff", "flake8", "pylint", "none"):
            profile = {
                "archetype": "python_project",
                "language": {
                    "primary": "python",
                    "components": [],
                    "communication": {},
                    "notebooks": None,
                },
                "delivery": {
                    "python": {
                        "environment_recommendation": "conda",
                        "dependency_format": "environment.yml",
                        "source_layout": "conventional",
                        "entry_points": False,
                    }
                },
                "quality": {
                    "python": {
                        "linter": linter,
                        "formatter": "ruff",
                        "type_checker": "mypy",
                        "import_sorter": "ruff",
                        "line_length": 88,
                    }
                },
            }
            errors = validate_profile(profile, language_registry)
            linter_errors = [e for e in errors if "linter" in e.lower()]
            assert len(linter_errors) == 0, (
                f"Linter {linter!r} should be valid but got errors: {linter_errors}"
            )

    def test_r_tool_validation_against_r_registry(self, language_registry):
        profile = {
            "archetype": "r_project",
            "language": {
                "primary": "r",
                "components": [],
                "communication": {},
                "notebooks": None,
            },
            "delivery": {
                "r": {
                    "environment_recommendation": "renv",
                    "dependency_format": "renv.lock",
                    "source_layout": "package",
                    "entry_points": False,
                }
            },
            "quality": {
                "r": {
                    "linter": "lintr",
                    "formatter": "styler",
                    "type_checker": "none",
                    "line_length": 80,
                }
            },
        }
        errors = validate_profile(profile, language_registry)
        tool_errors = [
            e
            for e in errors
            if "linter" in e.lower()
            or "formatter" in e.lower()
            or "type_checker" in e.lower()
        ]
        assert len(tool_errors) == 0

    def test_r_invalid_linter_produces_error(self, language_registry):
        profile = {
            "archetype": "r_project",
            "language": {
                "primary": "r",
                "components": [],
                "communication": {},
                "notebooks": None,
            },
            "delivery": {
                "r": {
                    "environment_recommendation": "renv",
                    "dependency_format": "renv.lock",
                    "source_layout": "package",
                    "entry_points": False,
                }
            },
            "quality": {
                "r": {
                    "linter": "pylint",
                    "formatter": "styler",
                    "type_checker": "none",
                    "line_length": 80,
                }
            },
        }
        errors = validate_profile(profile, language_registry)
        assert any("linter" in e.lower() for e in errors)


class TestValidateProfileMixedArchetype:
    def test_mixed_archetype_valid_with_both_languages(
        self, mixed_valid_profile, language_registry
    ):
        errors = validate_profile(mixed_valid_profile, language_registry)
        assert len(errors) == 0

    def test_mixed_archetype_missing_second_language_in_delivery(
        self, language_registry
    ):
        profile = {
            "archetype": "mixed",
            "language": {
                "primary": "python",
                "components": [],
                "communication": {},
                "notebooks": None,
            },
            "delivery": {
                "python": {
                    "environment_recommendation": "conda",
                    "dependency_format": "environment.yml",
                    "source_layout": "conventional",
                    "entry_points": False,
                },
                # Missing "r" delivery
            },
            "quality": {
                "python": {
                    "linter": "ruff",
                    "formatter": "ruff",
                    "type_checker": "mypy",
                    "import_sorter": "ruff",
                    "line_length": 88,
                },
                "r": {
                    "linter": "lintr",
                    "formatter": "styler",
                    "type_checker": "none",
                    "line_length": 80,
                },
            },
        }
        errors = validate_profile(profile, language_registry)
        assert len(errors) > 0

    def test_mixed_archetype_missing_second_language_in_quality(
        self, language_registry
    ):
        profile = {
            "archetype": "mixed",
            "language": {
                "primary": "python",
                "components": [],
                "communication": {},
                "notebooks": None,
            },
            "delivery": {
                "python": {
                    "environment_recommendation": "conda",
                    "dependency_format": "environment.yml",
                    "source_layout": "conventional",
                    "entry_points": False,
                },
                "r": {
                    "environment_recommendation": "conda",
                    "dependency_format": "environment.yml",
                    "source_layout": "package",
                    "entry_points": False,
                },
            },
            "quality": {
                "python": {
                    "linter": "ruff",
                    "formatter": "ruff",
                    "type_checker": "mypy",
                    "import_sorter": "ruff",
                    "line_length": 88,
                },
                # Missing "r" quality
            },
        }
        errors = validate_profile(profile, language_registry)
        assert len(errors) > 0

    def test_mixed_archetype_forces_conda_environment_for_both(self, language_registry):
        """Mixed archetype hard constraint: both environment_recommendation forced to conda."""
        profile = {
            "archetype": "mixed",
            "language": {
                "primary": "python",
                "components": [],
                "communication": {},
                "notebooks": None,
            },
            "delivery": {
                "python": {
                    "environment_recommendation": "conda",
                    "dependency_format": "environment.yml",
                    "source_layout": "conventional",
                    "entry_points": False,
                },
                "r": {
                    "environment_recommendation": "renv",
                    "dependency_format": "renv.lock",
                    "source_layout": "package",
                    "entry_points": False,
                },
            },
            "quality": {
                "python": {
                    "linter": "ruff",
                    "formatter": "ruff",
                    "type_checker": "mypy",
                    "import_sorter": "ruff",
                    "line_length": 88,
                },
                "r": {
                    "linter": "lintr",
                    "formatter": "styler",
                    "type_checker": "none",
                    "line_length": 80,
                },
            },
        }
        errors = validate_profile(profile, language_registry)
        # Should produce error because r.environment_recommendation is not "conda"
        assert any("environment" in e.lower() or "conda" in e.lower() for e in errors)

    def test_mixed_archetype_forces_environment_yml_for_both(self, language_registry):
        """Mixed archetype hard constraint: both dependency_format forced to environment.yml."""
        profile = {
            "archetype": "mixed",
            "language": {
                "primary": "python",
                "components": [],
                "communication": {},
                "notebooks": None,
            },
            "delivery": {
                "python": {
                    "environment_recommendation": "conda",
                    "dependency_format": "environment.yml",
                    "source_layout": "conventional",
                    "entry_points": False,
                },
                "r": {
                    "environment_recommendation": "conda",
                    "dependency_format": "renv.lock",
                    "source_layout": "package",
                    "entry_points": False,
                },
            },
            "quality": {
                "python": {
                    "linter": "ruff",
                    "formatter": "ruff",
                    "type_checker": "mypy",
                    "import_sorter": "ruff",
                    "line_length": 88,
                },
                "r": {
                    "linter": "lintr",
                    "formatter": "styler",
                    "type_checker": "none",
                    "line_length": 80,
                },
            },
        }
        errors = validate_profile(profile, language_registry)
        assert any(
            "dependency" in e.lower() or "environment.yml" in e.lower() for e in errors
        )

    def test_mixed_archetype_valid_with_conda_and_env_yml_for_both(
        self, language_registry
    ):
        """Mixed archetype: both languages with conda + environment.yml should validate clean."""
        profile = {
            "archetype": "mixed",
            "language": {
                "primary": "python",
                "components": [],
                "communication": {},
                "notebooks": None,
            },
            "delivery": {
                "python": {
                    "environment_recommendation": "conda",
                    "dependency_format": "environment.yml",
                    "source_layout": "conventional",
                    "entry_points": False,
                },
                "r": {
                    "environment_recommendation": "conda",
                    "dependency_format": "environment.yml",
                    "source_layout": "package",
                    "entry_points": False,
                },
            },
            "quality": {
                "python": {
                    "linter": "ruff",
                    "formatter": "ruff",
                    "type_checker": "mypy",
                    "import_sorter": "ruff",
                    "line_length": 88,
                },
                "r": {
                    "linter": "lintr",
                    "formatter": "styler",
                    "type_checker": "none",
                    "line_length": 80,
                },
            },
        }
        errors = validate_profile(profile, language_registry)
        assert len(errors) == 0


class TestValidateProfileComponentLanguage:
    def test_component_language_must_have_host(self, language_registry):
        """Component language referenced without a compatible host should produce error."""
        # Add a component-only entry
        language_registry["stan"] = {
            "id": "stan",
            "display_name": "Stan",
            "file_extension": ".stan",
            "is_component_only": True,
            "compatible_hosts": ["r", "python"],
        }
        profile = {
            "archetype": "python_project",
            "language": {
                "primary": "python",
                "components": ["stan"],
                "communication": {},
                "notebooks": None,
            },
            "delivery": {
                "python": {
                    "environment_recommendation": "conda",
                    "dependency_format": "environment.yml",
                    "source_layout": "conventional",
                    "entry_points": False,
                }
            },
            "quality": {
                "python": {
                    "linter": "ruff",
                    "formatter": "ruff",
                    "type_checker": "mypy",
                    "import_sorter": "ruff",
                    "line_length": 88,
                }
            },
        }
        # Should be valid because python is a compatible host for stan
        errors = validate_profile(profile, language_registry)
        host_errors = [
            e for e in errors if "host" in e.lower() or "component" in e.lower()
        ]
        assert len(host_errors) == 0


class TestValidateProfileReturnType:
    def test_returns_list(self, minimal_valid_profile, language_registry):
        result = validate_profile(minimal_valid_profile, language_registry)
        assert isinstance(result, list)

    def test_returns_empty_list_for_valid_profile(
        self, minimal_valid_profile, language_registry
    ):
        errors = validate_profile(minimal_valid_profile, language_registry)
        assert errors == []

    def test_returns_list_of_strings_on_error(self, language_registry):
        profile = {
            "archetype": "bad_archetype",
            "language": {
                "primary": "python",
                "components": [],
                "communication": {},
                "notebooks": None,
            },
            "delivery": {"python": {}},
            "quality": {"python": {}},
        }
        errors = validate_profile(profile, language_registry)
        assert len(errors) > 0
        assert all(isinstance(e, str) for e in errors)


# ===========================================================================
# get_delivery_config tests
# ===========================================================================


class TestGetDeliveryConfig:
    def test_returns_delivery_config_for_python(
        self, minimal_valid_profile, language_registry
    ):
        result = get_delivery_config(minimal_valid_profile, "python", language_registry)
        assert isinstance(result, dict)
        assert "environment_recommendation" in result

    def test_returns_deep_merged_with_registry_defaults(self, language_registry):
        """Profile delivery merged with registry default_delivery."""
        profile = {
            "delivery": {
                "python": {
                    "source_layout": "flat",
                },
            },
        }
        result = get_delivery_config(profile, "python", language_registry)
        # User override should be preserved
        assert result["source_layout"] == "flat"
        # Registry defaults should fill in missing keys
        assert "environment_recommendation" in result
        assert result["environment_recommendation"] == "conda"

    def test_profile_values_override_registry_defaults(self, language_registry):
        profile = {
            "delivery": {
                "python": {
                    "environment_recommendation": "pip",
                    "dependency_format": "requirements.txt",
                    "source_layout": "flat",
                    "entry_points": True,
                },
            },
        }
        result = get_delivery_config(profile, "python", language_registry)
        assert result["environment_recommendation"] == "pip"
        assert result["dependency_format"] == "requirements.txt"
        assert result["source_layout"] == "flat"
        assert result["entry_points"] is True

    def test_raises_key_error_for_unknown_language(
        self, minimal_valid_profile, language_registry
    ):
        with pytest.raises(KeyError):
            get_delivery_config(minimal_valid_profile, "julia", language_registry)

    def test_r_language_delivery_config(self, language_registry):
        profile = {
            "delivery": {
                "r": {
                    "source_layout": "scripts",
                },
            },
        }
        result = get_delivery_config(profile, "r", language_registry)
        assert result["source_layout"] == "scripts"
        assert result["environment_recommendation"] == "renv"

    def test_missing_language_key_in_profile_delivery_still_returns_defaults(
        self, language_registry
    ):
        """If profile delivery has no key for the requested language, registry defaults apply."""
        profile = {
            "delivery": {},
        }
        result = get_delivery_config(profile, "python", language_registry)
        assert result["environment_recommendation"] == "conda"
        assert result["dependency_format"] == "environment.yml"
        assert result["source_layout"] == "conventional"
        assert result["entry_points"] is False


# ===========================================================================
# get_quality_config tests
# ===========================================================================


class TestGetQualityConfig:
    def test_returns_quality_config_for_python(
        self, minimal_valid_profile, language_registry
    ):
        result = get_quality_config(minimal_valid_profile, "python", language_registry)
        assert isinstance(result, dict)
        assert "linter" in result

    def test_returns_deep_merged_with_registry_defaults(self, language_registry):
        """Profile quality merged with registry default_quality."""
        profile = {
            "quality": {
                "python": {
                    "linter": "flake8",
                },
            },
        }
        result = get_quality_config(profile, "python", language_registry)
        # User override preserved
        assert result["linter"] == "flake8"
        # Registry defaults fill in
        assert result["formatter"] == "ruff"
        assert result["type_checker"] == "mypy"
        assert result["line_length"] == 88

    def test_profile_values_override_registry_defaults(self, language_registry):
        profile = {
            "quality": {
                "python": {
                    "linter": "pylint",
                    "formatter": "black",
                    "type_checker": "pyright",
                    "import_sorter": "ruff",
                    "line_length": 120,
                },
            },
        }
        result = get_quality_config(profile, "python", language_registry)
        assert result["linter"] == "pylint"
        assert result["formatter"] == "black"
        assert result["type_checker"] == "pyright"
        assert result["line_length"] == 120

    def test_raises_key_error_for_unknown_language(
        self, minimal_valid_profile, language_registry
    ):
        with pytest.raises(KeyError):
            get_quality_config(minimal_valid_profile, "julia", language_registry)

    def test_r_language_quality_config(self, language_registry):
        profile = {
            "quality": {
                "r": {
                    "linter": "lintr",
                },
            },
        }
        result = get_quality_config(profile, "r", language_registry)
        assert result["linter"] == "lintr"
        assert result["formatter"] == "styler"
        assert result["type_checker"] == "none"
        assert result["line_length"] == 80

    def test_missing_language_key_in_profile_quality_still_returns_defaults(
        self, language_registry
    ):
        """If profile quality has no key for the requested language, registry defaults apply."""
        profile = {
            "quality": {},
        }
        result = get_quality_config(profile, "python", language_registry)
        assert result["linter"] == "ruff"
        assert result["formatter"] == "ruff"
        assert result["type_checker"] == "mypy"
        assert result["line_length"] == 88

    def test_python_quality_includes_import_sorter(self, language_registry):
        """Python default quality includes import_sorter key."""
        profile = {"quality": {}}
        result = get_quality_config(profile, "python", language_registry)
        assert "import_sorter" in result


# ===========================================================================
# Cross-function integration scenarios
# ===========================================================================


class TestLoadThenValidateIntegration:
    def test_loaded_default_profile_validates_clean(self, tmp_path, language_registry):
        """A profile that only relies on defaults should validate without errors."""
        write_profile(
            tmp_path, {"archetype": "python_project", "language": {"primary": "python"}}
        )
        loaded = load_profile(tmp_path)
        errors = validate_profile(loaded, language_registry)
        assert errors == []

    def test_loaded_profile_with_custom_tools_validates(
        self, tmp_path, language_registry
    ):
        profile = {
            "archetype": "python_project",
            "language": {
                "primary": "python",
                "components": [],
                "communication": {},
                "notebooks": None,
            },
            "quality": {
                "python": {
                    "linter": "flake8",
                    "formatter": "black",
                    "type_checker": "pyright",
                    "import_sorter": "ruff",
                    "line_length": 100,
                },
            },
        }
        write_profile(tmp_path, profile)
        loaded = load_profile(tmp_path)
        errors = validate_profile(loaded, language_registry)
        assert errors == []


class TestLoadThenGetConfigIntegration:
    def test_loaded_profile_delivery_config_accessible(
        self, tmp_path, language_registry
    ):
        profile = {
            "archetype": "python_project",
            "language": {
                "primary": "python",
                "components": [],
                "communication": {},
                "notebooks": None,
            },
            "delivery": {"python": {"source_layout": "flat"}},
        }
        write_profile(tmp_path, profile)
        loaded = load_profile(tmp_path)
        delivery = get_delivery_config(loaded, "python", language_registry)
        assert delivery["source_layout"] == "flat"
        assert delivery["environment_recommendation"] == "conda"

    def test_loaded_profile_quality_config_accessible(
        self, tmp_path, language_registry
    ):
        profile = {
            "archetype": "python_project",
            "language": {
                "primary": "python",
                "components": [],
                "communication": {},
                "notebooks": None,
            },
            "quality": {"python": {"linter": "pylint", "line_length": 120}},
        }
        write_profile(tmp_path, profile)
        loaded = load_profile(tmp_path)
        quality = get_quality_config(loaded, "python", language_registry)
        assert quality["linter"] == "pylint"
        assert quality["line_length"] == 120
        # Defaults filled in
        assert quality["formatter"] == "ruff"


class TestSvp21MigrationThenGetConfig:
    def test_migrated_flat_delivery_accessible_via_get_delivery_config(
        self, tmp_path, language_registry
    ):
        """After SVP 2.1 migration wraps flat delivery, get_delivery_config works."""
        legacy_profile = {
            "archetype": "python_project",
            "language": {
                "primary": "python",
                "components": [],
                "communication": {},
                "notebooks": None,
            },
            "delivery": {
                "environment_recommendation": "conda",
                "dependency_format": "environment.yml",
                "source_layout": "flat",
                "entry_points": True,
            },
        }
        write_profile(tmp_path, legacy_profile)
        loaded = load_profile(tmp_path)
        delivery = get_delivery_config(loaded, "python", language_registry)
        assert delivery["source_layout"] == "flat"
        assert delivery["entry_points"] is True

    def test_migrated_flat_quality_accessible_via_get_quality_config(
        self, tmp_path, language_registry
    ):
        """After SVP 2.1 migration wraps flat quality, get_quality_config works."""
        legacy_profile = {
            "archetype": "python_project",
            "language": {
                "primary": "python",
                "components": [],
                "communication": {},
                "notebooks": None,
            },
            "quality": {
                "linter": "flake8",
                "formatter": "black",
                "type_checker": "mypy",
                "line_length": 100,
            },
        }
        write_profile(tmp_path, legacy_profile)
        loaded = load_profile(tmp_path)
        quality = get_quality_config(loaded, "python", language_registry)
        assert quality["linter"] == "flake8"
        assert quality["formatter"] == "black"
        assert quality["line_length"] == 100
