"""test_unit_4.py -- Test suite for Unit 4: Toolchain Reader.

SVP 2.2 Pass 2 -- Generated by Test Agent.

Tests all behavioral contracts from the blueprint for the toolchain reader module,
including load_toolchain, resolve_command, and get_gate_composition. Also includes
structural regression tests enforcing the Layer 1/Layer 2 vs. Layer 3 separation.

Synthetic Data Assumptions:
    - toolchain.json (pipeline toolchain, Layer 1) is created in temporary directories
      via tmp_path, containing a JSON object with a "quality" key holding gate definitions.
    - Language-specific toolchain files (python_conda_pytest.json, r_conda_testthat.json)
      are placed under scripts/toolchain_defaults/ relative to the project root.
    - LANGUAGE_REGISTRY entries for "python" have toolchain_file = "python_conda_pytest.json"
      and for "r" have toolchain_file = "r_conda_testthat.json", as defined in Unit 2 contracts.
    - Command templates use the placeholders {run_prefix}, {env_name}, {python_version},
      {flags}, and {target} in various combinations.
    - Gate compositions are lists of operation dicts, each with at minimum "operation" and
      "command" keys, representing quality gate steps.
    - No project_profile.json is ever created or read during these tests, enforcing the
      three-layer separation contract.
"""

import inspect
import json
from pathlib import Path

import pytest

from toolchain_reader import (
    get_gate_composition,
    load_toolchain,
    resolve_command,
)

# ---------------------------------------------------------------------------
# Fixtures: synthetic toolchain data
# ---------------------------------------------------------------------------


@pytest.fixture
def pipeline_toolchain_data():
    """Minimal pipeline toolchain (Layer 1) with quality gate definitions."""
    return {
        "version": "1.0",
        "quality": {
            "gate_a": [
                {"operation": "lint", "command": "ruff check {target}"},
                {
                    "operation": "format_check",
                    "command": "ruff format --check {target}",
                },
            ],
            "gate_b": [
                {"operation": "type_check", "command": "mypy {target} {flags}"},
            ],
        },
    }


@pytest.fixture
def python_toolchain_data():
    """Synthetic Python toolchain file matching python_conda_pytest.json."""
    return {
        "language": "python",
        "test_framework": "pytest",
        "environment_manager": "conda",
        "quality": {
            "gate_a": [
                {"operation": "lint", "command": "ruff check {target}"},
                {
                    "operation": "format_check",
                    "command": "ruff format --check {target}",
                },
            ],
            "gate_b": [
                {"operation": "type_check", "command": "mypy {target}"},
            ],
        },
    }


@pytest.fixture
def r_toolchain_data():
    """Synthetic R toolchain file matching r_conda_testthat.json."""
    return {
        "language": "r",
        "test_framework": "testthat",
        "environment_manager": "conda",
        "quality": {
            "gate_a": [
                {
                    "operation": "lint",
                    "command": "Rscript -e \"lintr::lint_dir('{target}')\"",
                },
            ],
        },
    }


@pytest.fixture
def project_root_with_pipeline_toolchain(tmp_path, pipeline_toolchain_data):
    """Creates a project root with a pipeline toolchain.json."""
    toolchain_path = tmp_path / "toolchain.json"
    toolchain_path.write_text(json.dumps(pipeline_toolchain_data, indent=2))
    return tmp_path


@pytest.fixture
def project_root_with_python_toolchain(tmp_path, python_toolchain_data):
    """Creates a project root with a Python toolchain in scripts/toolchain_defaults/."""
    defaults_dir = tmp_path / "scripts" / "toolchain_defaults"
    defaults_dir.mkdir(parents=True)
    toolchain_path = defaults_dir / "python_conda_pytest.json"
    toolchain_path.write_text(json.dumps(python_toolchain_data, indent=2))
    return tmp_path


@pytest.fixture
def project_root_with_r_toolchain(tmp_path, r_toolchain_data):
    """Creates a project root with an R toolchain in scripts/toolchain_defaults/."""
    defaults_dir = tmp_path / "scripts" / "toolchain_defaults"
    defaults_dir.mkdir(parents=True)
    toolchain_path = defaults_dir / "r_conda_testthat.json"
    toolchain_path.write_text(json.dumps(r_toolchain_data, indent=2))
    return tmp_path


@pytest.fixture
def project_root_with_all_toolchains(
    tmp_path, pipeline_toolchain_data, python_toolchain_data, r_toolchain_data
):
    """Creates a project root with pipeline, Python, and R toolchains."""
    # Pipeline toolchain
    toolchain_path = tmp_path / "toolchain.json"
    toolchain_path.write_text(json.dumps(pipeline_toolchain_data, indent=2))
    # Language-specific toolchains
    defaults_dir = tmp_path / "scripts" / "toolchain_defaults"
    defaults_dir.mkdir(parents=True)
    (defaults_dir / "python_conda_pytest.json").write_text(
        json.dumps(python_toolchain_data, indent=2)
    )
    (defaults_dir / "r_conda_testthat.json").write_text(
        json.dumps(r_toolchain_data, indent=2)
    )
    return tmp_path


# ---------------------------------------------------------------------------
# load_toolchain: language=None (pipeline toolchain)
# ---------------------------------------------------------------------------


class TestLoadToolchainPipeline:
    """Tests for load_toolchain with language=None (pipeline toolchain, Layer 1)."""

    def test_loads_pipeline_toolchain_from_project_root(
        self, project_root_with_pipeline_toolchain, pipeline_toolchain_data
    ):
        """language=None loads toolchain.json from project_root."""
        result = load_toolchain(project_root_with_pipeline_toolchain, language=None)
        assert result == pipeline_toolchain_data

    def test_default_language_is_none(
        self, project_root_with_pipeline_toolchain, pipeline_toolchain_data
    ):
        """Calling without language argument defaults to None and loads pipeline toolchain."""
        result = load_toolchain(project_root_with_pipeline_toolchain)
        assert result == pipeline_toolchain_data

    def test_returns_dict(self, project_root_with_pipeline_toolchain):
        """load_toolchain returns a Dict[str, Any]."""
        result = load_toolchain(project_root_with_pipeline_toolchain)
        assert isinstance(result, dict)

    def test_raises_file_not_found_when_absent(self, tmp_path):
        """Raises FileNotFoundError if toolchain.json is absent."""
        with pytest.raises(FileNotFoundError):
            load_toolchain(tmp_path, language=None)

    def test_preserves_quality_section(
        self, project_root_with_pipeline_toolchain, pipeline_toolchain_data
    ):
        """Pipeline toolchain quality section is preserved in returned dict."""
        result = load_toolchain(project_root_with_pipeline_toolchain)
        assert "quality" in result
        assert result["quality"] == pipeline_toolchain_data["quality"]


# ---------------------------------------------------------------------------
# load_toolchain: language="python"
# ---------------------------------------------------------------------------


class TestLoadToolchainPython:
    """Tests for load_toolchain with language='python'."""

    def test_loads_python_toolchain(
        self, project_root_with_python_toolchain, python_toolchain_data
    ):
        """language='python' loads scripts/toolchain_defaults/python_conda_pytest.json."""
        result = load_toolchain(project_root_with_python_toolchain, language="python")
        assert result == python_toolchain_data

    def test_python_toolchain_has_language_key(
        self, project_root_with_python_toolchain
    ):
        """Python toolchain contains the language field."""
        result = load_toolchain(project_root_with_python_toolchain, language="python")
        assert result.get("language") == "python"

    def test_raises_file_not_found_when_python_toolchain_absent(self, tmp_path):
        """Raises FileNotFoundError if python toolchain file is absent."""
        with pytest.raises(FileNotFoundError):
            load_toolchain(tmp_path, language="python")


# ---------------------------------------------------------------------------
# load_toolchain: language="r"
# ---------------------------------------------------------------------------


class TestLoadToolchainR:
    """Tests for load_toolchain with language='r'."""

    def test_loads_r_toolchain(self, project_root_with_r_toolchain, r_toolchain_data):
        """language='r' loads scripts/toolchain_defaults/r_conda_testthat.json."""
        result = load_toolchain(project_root_with_r_toolchain, language="r")
        assert result == r_toolchain_data

    def test_r_toolchain_has_language_key(self, project_root_with_r_toolchain):
        """R toolchain contains the language field."""
        result = load_toolchain(project_root_with_r_toolchain, language="r")
        assert result.get("language") == "r"

    def test_raises_file_not_found_when_r_toolchain_absent(self, tmp_path):
        """Raises FileNotFoundError if R toolchain file is absent."""
        with pytest.raises(FileNotFoundError):
            load_toolchain(tmp_path, language="r")


# ---------------------------------------------------------------------------
# load_toolchain: path resolution via LANGUAGE_REGISTRY
# ---------------------------------------------------------------------------


class TestLoadToolchainRegistryDispatch:
    """Tests that load_toolchain resolves paths from LANGUAGE_REGISTRY[language]['toolchain_file']."""

    def test_python_path_matches_registry_toolchain_file(
        self, project_root_with_python_toolchain
    ):
        """Python toolchain file path comes from LANGUAGE_REGISTRY['python']['toolchain_file']."""
        # The contract states python maps to python_conda_pytest.json
        # If file exists at scripts/toolchain_defaults/python_conda_pytest.json, load succeeds
        result = load_toolchain(project_root_with_python_toolchain, language="python")
        assert isinstance(result, dict)

    def test_r_path_matches_registry_toolchain_file(
        self, project_root_with_r_toolchain
    ):
        """R toolchain file path comes from LANGUAGE_REGISTRY['r']['toolchain_file']."""
        # The contract states r maps to r_conda_testthat.json
        result = load_toolchain(project_root_with_r_toolchain, language="r")
        assert isinstance(result, dict)

    def test_different_languages_load_different_files(
        self, project_root_with_all_toolchains
    ):
        """Python and R load different toolchain files."""
        py_result = load_toolchain(project_root_with_all_toolchains, language="python")
        r_result = load_toolchain(project_root_with_all_toolchains, language="r")
        assert py_result != r_result
        assert py_result.get("language") == "python"
        assert r_result.get("language") == "r"


# ---------------------------------------------------------------------------
# load_toolchain: three-layer separation
# ---------------------------------------------------------------------------


class TestLoadToolchainLayerSeparation:
    """Tests for three-layer separation: pipeline toolchain (Layer 1) never reads profile."""

    def test_pipeline_toolchain_does_not_read_profile(
        self, project_root_with_pipeline_toolchain
    ):
        """Loading pipeline toolchain does not require or read project_profile.json."""
        # Ensure no profile exists yet loading succeeds
        profile_path = project_root_with_pipeline_toolchain / "project_profile.json"
        assert not profile_path.exists()
        result = load_toolchain(project_root_with_pipeline_toolchain)
        assert isinstance(result, dict)

    def test_language_toolchain_does_not_read_profile(
        self, project_root_with_python_toolchain
    ):
        """Loading language toolchain does not require or read project_profile.json."""
        profile_path = project_root_with_python_toolchain / "project_profile.json"
        assert not profile_path.exists()
        result = load_toolchain(project_root_with_python_toolchain, language="python")
        assert isinstance(result, dict)


# ---------------------------------------------------------------------------
# resolve_command: single-pass substitution
# ---------------------------------------------------------------------------


class TestResolveCommandSubstitution:
    """Tests for resolve_command placeholder substitution."""

    def test_substitutes_run_prefix(self):
        """Substitutes {run_prefix} placeholder."""
        result = resolve_command(
            template="{run_prefix} pytest",
            env_name="svp-test",
            run_prefix="conda run -n svp-test",
        )
        assert "conda run -n svp-test" in result
        assert "{run_prefix}" not in result

    def test_substitutes_env_name(self):
        """Substitutes {env_name} placeholder."""
        result = resolve_command(
            template="conda run -n {env_name} pytest",
            env_name="svp-myproject",
            run_prefix="",
        )
        assert "svp-myproject" in result
        assert "{env_name}" not in result

    def test_substitutes_python_version(self):
        """Substitutes {python_version} placeholder."""
        result = resolve_command(
            template="python{python_version} -m pytest",
            env_name="svp-test",
            run_prefix="",
            python_version="3.11",
        )
        assert "python3.11" in result
        assert "{python_version}" not in result

    def test_substitutes_flags(self):
        """Substitutes {flags} placeholder."""
        result = resolve_command(
            template="pytest {flags} tests/",
            env_name="svp-test",
            run_prefix="",
            flags="--verbose --tb=short",
        )
        assert "--verbose --tb=short" in result
        assert "{flags}" not in result

    def test_substitutes_target(self):
        """Substitutes {target} placeholder."""
        result = resolve_command(
            template="ruff check {target}",
            env_name="svp-test",
            run_prefix="",
            target="src/unit_4/",
        )
        assert "src/unit_4/" in result
        assert "{target}" not in result

    def test_substitutes_all_placeholders_together(self):
        """All placeholders resolved in a single template."""
        result = resolve_command(
            template="{run_prefix} python{python_version} -m pytest {flags} {target}",
            env_name="svp-proj",
            run_prefix="conda run -n svp-proj",
            target="tests/",
            python_version="3.11",
            flags="-v",
        )
        assert "conda run -n svp-proj" in result
        assert "python3.11" in result
        assert "-v" in result
        assert "tests/" in result
        assert "{run_prefix}" not in result
        assert "{python_version}" not in result
        assert "{flags}" not in result
        assert "{target}" not in result

    def test_env_name_in_template(self):
        """env_name substitution works within larger template."""
        result = resolve_command(
            template="conda activate {env_name} && pytest",
            env_name="svp-demo",
            run_prefix="",
        )
        assert "svp-demo" in result
        assert "{env_name}" not in result


# ---------------------------------------------------------------------------
# resolve_command: substitution order (run_prefix first)
# ---------------------------------------------------------------------------


class TestResolveCommandSubstitutionOrder:
    """Tests for single-pass substitution order: run_prefix first, then env_name, python_version, flags, target."""

    def test_run_prefix_substituted_first(self):
        """run_prefix is substituted before env_name, so run_prefix containing {env_name} literal is not re-expanded."""
        # If run_prefix contains the literal string "{env_name}", that should remain
        # because run_prefix is substituted first and env_name substitution happens after.
        # However, the contract says single-pass: run_prefix first, then env_name.
        # So {env_name} in the template (not in run_prefix value) gets substituted.
        result = resolve_command(
            template="{run_prefix} {env_name}",
            env_name="myenv",
            run_prefix="prefix",
        )
        assert result == "prefix myenv"

    def test_empty_run_prefix_does_not_leave_artifacts(self):
        """Empty run_prefix + whitespace collapse produces clean output."""
        result = resolve_command(
            template="{run_prefix} pytest {target}",
            env_name="svp-test",
            run_prefix="",
            target="tests/",
        )
        # After collapse: no double spaces, no leading/trailing whitespace
        assert "  " not in result
        assert result == result.strip()
        assert "pytest" in result


# ---------------------------------------------------------------------------
# resolve_command: whitespace normalization
# ---------------------------------------------------------------------------


class TestResolveCommandWhitespace:
    """Tests for whitespace handling after substitution."""

    def test_collapses_multiple_spaces_to_single(self):
        """Multiple consecutive spaces are collapsed to single space."""
        result = resolve_command(
            template="{run_prefix}  pytest  {target}",
            env_name="svp-test",
            run_prefix="",
            target="",
        )
        assert "  " not in result

    def test_strips_leading_whitespace(self):
        """No leading whitespace in resolved command."""
        result = resolve_command(
            template=" {run_prefix} pytest",
            env_name="svp-test",
            run_prefix="",
        )
        assert not result.startswith(" ")

    def test_strips_trailing_whitespace(self):
        """No trailing whitespace in resolved command."""
        result = resolve_command(
            template="pytest {target} ",
            env_name="svp-test",
            run_prefix="",
            target="",
        )
        assert not result.endswith(" ")

    def test_empty_optional_params_collapse_cleanly(self):
        """When optional params are empty, spaces collapse cleanly."""
        result = resolve_command(
            template="{run_prefix} pytest {flags} {target}",
            env_name="svp-test",
            run_prefix="",
            target="",
            flags="",
        )
        assert "  " not in result
        assert result == result.strip()

    def test_no_double_spaces_after_full_resolution(self):
        """Even with all params filled, no double spaces appear."""
        result = resolve_command(
            template="{run_prefix} python{python_version} -m pytest {flags} {target}",
            env_name="svp-proj",
            run_prefix="conda run -n svp-proj",
            target="tests/",
            python_version="3.11",
            flags="-v",
        )
        assert "  " not in result


# ---------------------------------------------------------------------------
# resolve_command: no unresolved placeholders
# ---------------------------------------------------------------------------


class TestResolveCommandNoUnresolved:
    """Tests that no unresolved {...} placeholders remain after resolution."""

    def test_no_unresolved_placeholders_all_filled(self):
        """All known placeholders resolved, none remain."""
        result = resolve_command(
            template="{run_prefix} {env_name} {python_version} {flags} {target}",
            env_name="env",
            run_prefix="prefix",
            target="tgt",
            python_version="3.11",
            flags="-v",
        )
        assert "{" not in result
        assert "}" not in result

    def test_no_unresolved_placeholders_empty_optionals(self):
        """Empty optional params produce no leftover placeholders."""
        result = resolve_command(
            template="{run_prefix} pytest {flags} {target}",
            env_name="svp-test",
            run_prefix="",
            target="",
            flags="",
        )
        assert "{" not in result
        assert "}" not in result

    def test_no_unresolved_placeholders_defaults_only(self):
        """Using only required params (template, env_name, run_prefix) leaves no placeholders."""
        result = resolve_command(
            template="{run_prefix} pytest",
            env_name="svp-test",
            run_prefix="conda run -n svp-test",
        )
        assert "{" not in result
        assert "}" not in result

    def test_template_with_only_run_prefix(self):
        """Template with single placeholder resolves cleanly."""
        result = resolve_command(
            template="{run_prefix}",
            env_name="e",
            run_prefix="echo hello",
        )
        assert result == "echo hello"
        assert "{" not in result

    def test_template_with_all_placeholders_some_empty(self):
        """Mixed filled and empty placeholders leave no unresolved markers."""
        result = resolve_command(
            template="{run_prefix} python{python_version} {flags} {target}",
            env_name="e",
            run_prefix="conda run -n e",
            target="",
            python_version="",
            flags="",
        )
        assert "{" not in result
        assert "}" not in result


# ---------------------------------------------------------------------------
# resolve_command: return type and edge cases
# ---------------------------------------------------------------------------


class TestResolveCommandReturnType:
    """Tests for resolve_command return value type and edge cases."""

    def test_returns_string(self):
        """resolve_command returns a str."""
        result = resolve_command(
            template="pytest",
            env_name="e",
            run_prefix="",
        )
        assert isinstance(result, str)

    def test_template_with_no_placeholders(self):
        """Template with no placeholders passes through unchanged (after strip)."""
        result = resolve_command(
            template="pytest --verbose",
            env_name="svp-test",
            run_prefix="",
        )
        assert result == "pytest --verbose"

    def test_run_prefix_with_env_name_embedded(self):
        """run_prefix can contain the env_name value already embedded."""
        result = resolve_command(
            template="{run_prefix} pytest",
            env_name="svp-proj",
            run_prefix="conda run -n svp-proj",
        )
        assert result == "conda run -n svp-proj pytest"


# ---------------------------------------------------------------------------
# get_gate_composition: basic behavior
# ---------------------------------------------------------------------------


class TestGetGateCompositionBasic:
    """Tests for get_gate_composition returning ordered operation dicts."""

    def test_returns_list(self, pipeline_toolchain_data):
        """get_gate_composition returns a list."""
        result = get_gate_composition(pipeline_toolchain_data, "gate_a")
        assert isinstance(result, list)

    def test_returns_ordered_operations(self, pipeline_toolchain_data):
        """Operations are returned in the order defined in the toolchain."""
        result = get_gate_composition(pipeline_toolchain_data, "gate_a")
        assert len(result) == 2
        # Order must match: lint first, then format_check
        assert result[0]["operation"] == "quality.lint"
        assert result[1]["operation"] == "quality.format_check"

    def test_single_operation_gate(self, pipeline_toolchain_data):
        """Gate with a single operation returns a single-element list."""
        result = get_gate_composition(pipeline_toolchain_data, "gate_b")
        assert len(result) == 1

    def test_each_operation_has_operation_key(self, pipeline_toolchain_data):
        """Every operation dict contains an 'operation' key."""
        result = get_gate_composition(pipeline_toolchain_data, "gate_a")
        for op in result:
            assert "operation" in op

    def test_each_operation_has_command_key(self, pipeline_toolchain_data):
        """Every operation dict contains a 'command' key."""
        result = get_gate_composition(pipeline_toolchain_data, "gate_a")
        for op in result:
            assert "command" in op


# ---------------------------------------------------------------------------
# get_gate_composition: quality prefix qualification
# ---------------------------------------------------------------------------


class TestGetGateCompositionQualityPrefix:
    """Tests that operation names are qualified with 'quality.' prefix."""

    def test_operation_names_prefixed_with_quality(self, pipeline_toolchain_data):
        """Each operation name is prefixed with 'quality.'."""
        result = get_gate_composition(pipeline_toolchain_data, "gate_a")
        for op in result:
            assert op["operation"].startswith("quality.")

    def test_lint_operation_becomes_quality_lint(self, pipeline_toolchain_data):
        """'lint' operation in toolchain becomes 'quality.lint' in output."""
        result = get_gate_composition(pipeline_toolchain_data, "gate_a")
        operation_names = [op["operation"] for op in result]
        assert "quality.lint" in operation_names

    def test_format_check_becomes_quality_format_check(self, pipeline_toolchain_data):
        """'format_check' in toolchain becomes 'quality.format_check' in output."""
        result = get_gate_composition(pipeline_toolchain_data, "gate_a")
        operation_names = [op["operation"] for op in result]
        assert "quality.format_check" in operation_names

    def test_type_check_becomes_quality_type_check(self, pipeline_toolchain_data):
        """'type_check' in toolchain becomes 'quality.type_check' in output."""
        result = get_gate_composition(pipeline_toolchain_data, "gate_b")
        operation_names = [op["operation"] for op in result]
        assert "quality.type_check" in operation_names

    def test_command_values_preserved_after_prefix(self, pipeline_toolchain_data):
        """Command values are not altered by the prefix operation."""
        result = get_gate_composition(pipeline_toolchain_data, "gate_a")
        assert result[0]["command"] == "ruff check {target}"
        assert result[1]["command"] == "ruff format --check {target}"


# ---------------------------------------------------------------------------
# get_gate_composition: KeyError on missing gate_id
# ---------------------------------------------------------------------------


class TestGetGateCompositionMissingGate:
    """Tests for KeyError when gate_id is not in toolchain quality config."""

    def test_raises_key_error_for_unknown_gate(self, pipeline_toolchain_data):
        """Raises KeyError if gate_id not present in toolchain quality config."""
        with pytest.raises(KeyError):
            get_gate_composition(pipeline_toolchain_data, "gate_z")

    def test_raises_key_error_for_empty_string_gate(self, pipeline_toolchain_data):
        """Raises KeyError for an empty-string gate_id."""
        with pytest.raises(KeyError):
            get_gate_composition(pipeline_toolchain_data, "")

    def test_raises_key_error_for_nonexistent_gate_with_message(
        self, pipeline_toolchain_data
    ):
        """KeyError for missing gate is propagated (not swallowed)."""
        with pytest.raises(KeyError):
            get_gate_composition(pipeline_toolchain_data, "nonexistent_gate")


# ---------------------------------------------------------------------------
# get_gate_composition: with language-specific toolchains
# ---------------------------------------------------------------------------


class TestGetGateCompositionLanguageToolchains:
    """Tests for get_gate_composition with language-specific toolchain data."""

    def test_python_toolchain_gate_a(self, python_toolchain_data):
        """Python toolchain gate_a returns qualified operations."""
        result = get_gate_composition(python_toolchain_data, "gate_a")
        assert len(result) == 2
        assert all(op["operation"].startswith("quality.") for op in result)

    def test_python_toolchain_gate_b(self, python_toolchain_data):
        """Python toolchain gate_b returns type_check operation."""
        result = get_gate_composition(python_toolchain_data, "gate_b")
        assert len(result) == 1
        assert result[0]["operation"] == "quality.type_check"

    def test_r_toolchain_gate_a(self, r_toolchain_data):
        """R toolchain gate_a returns lint operation."""
        result = get_gate_composition(r_toolchain_data, "gate_a")
        assert len(result) == 1
        assert result[0]["operation"] == "quality.lint"

    def test_r_toolchain_missing_gate_b(self, r_toolchain_data):
        """R toolchain without gate_b raises KeyError."""
        with pytest.raises(KeyError):
            get_gate_composition(r_toolchain_data, "gate_b")


# ---------------------------------------------------------------------------
# get_gate_composition: operation dict structure
# ---------------------------------------------------------------------------


class TestGetGateCompositionDictStructure:
    """Tests for the structure of operation dicts returned by get_gate_composition."""

    def test_operation_dict_is_dict(self, pipeline_toolchain_data):
        """Each element in the returned list is a dict."""
        result = get_gate_composition(pipeline_toolchain_data, "gate_a")
        for op in result:
            assert isinstance(op, dict)

    def test_operation_dict_operation_is_string(self, pipeline_toolchain_data):
        """The 'operation' value in each dict is a string."""
        result = get_gate_composition(pipeline_toolchain_data, "gate_a")
        for op in result:
            assert isinstance(op["operation"], str)

    def test_operation_dict_command_is_string(self, pipeline_toolchain_data):
        """The 'command' value in each dict is a string."""
        result = get_gate_composition(pipeline_toolchain_data, "gate_a")
        for op in result:
            assert isinstance(op["command"], str)

    def test_extra_keys_preserved(self):
        """Operation dicts with extra keys beyond 'operation' and 'command' are preserved."""
        toolchain = {
            "quality": {
                "gate_x": [
                    {
                        "operation": "custom_check",
                        "command": "custom-tool run",
                        "timeout": 30,
                        "critical": True,
                    },
                ],
            },
        }
        result = get_gate_composition(toolchain, "gate_x")
        assert result[0]["operation"] == "quality.custom_check"
        assert result[0]["command"] == "custom-tool run"
        # Extra keys should be preserved
        assert result[0]["timeout"] == 30
        assert result[0]["critical"] is True


# ---------------------------------------------------------------------------
# get_gate_composition: empty gate
# ---------------------------------------------------------------------------


class TestGetGateCompositionEmptyGate:
    """Tests for get_gate_composition when a gate has an empty operations list."""

    def test_empty_gate_returns_empty_list(self):
        """Gate with empty operations list returns empty list."""
        toolchain = {"quality": {"empty_gate": []}}
        result = get_gate_composition(toolchain, "empty_gate")
        assert result == []


# ---------------------------------------------------------------------------
# load_toolchain + get_gate_composition integration
# ---------------------------------------------------------------------------


class TestLoadToolchainAndGetGateComposition:
    """Integration tests: load a toolchain, then get gate composition from it."""

    def test_pipeline_toolchain_round_trip(self, project_root_with_pipeline_toolchain):
        """Load pipeline toolchain, then get gate_a composition."""
        tc = load_toolchain(project_root_with_pipeline_toolchain)
        ops = get_gate_composition(tc, "gate_a")
        assert len(ops) == 2
        assert ops[0]["operation"] == "quality.lint"

    def test_python_toolchain_round_trip(self, project_root_with_python_toolchain):
        """Load Python toolchain, then get gate_a composition."""
        tc = load_toolchain(project_root_with_python_toolchain, language="python")
        ops = get_gate_composition(tc, "gate_a")
        assert len(ops) >= 1
        assert all("operation" in op for op in ops)
        assert all("command" in op for op in ops)

    def test_r_toolchain_round_trip(self, project_root_with_r_toolchain):
        """Load R toolchain, then get gate_a composition."""
        tc = load_toolchain(project_root_with_r_toolchain, language="r")
        ops = get_gate_composition(tc, "gate_a")
        assert len(ops) >= 1
        assert ops[0]["operation"] == "quality.lint"


# ---------------------------------------------------------------------------
# resolve_command + get_gate_composition integration
# ---------------------------------------------------------------------------


class TestResolveCommandWithGateComposition:
    """Integration: resolve commands from gate compositions."""

    def test_resolve_gate_a_lint_command(self, pipeline_toolchain_data):
        """Resolve the lint command from gate_a composition."""
        ops = get_gate_composition(pipeline_toolchain_data, "gate_a")
        lint_cmd = ops[0]["command"]
        resolved = resolve_command(
            template=lint_cmd,
            env_name="svp-test",
            run_prefix="",
            target="src/",
        )
        assert "ruff check src/" in resolved
        assert "{target}" not in resolved

    def test_resolve_gate_b_type_check_command(self, pipeline_toolchain_data):
        """Resolve the type_check command from gate_b composition."""
        ops = get_gate_composition(pipeline_toolchain_data, "gate_b")
        type_cmd = ops[0]["command"]
        resolved = resolve_command(
            template=type_cmd,
            env_name="svp-test",
            run_prefix="",
            target="src/unit_4/",
            flags="--strict",
        )
        assert "mypy" in resolved
        assert "src/unit_4/" in resolved
        assert "--strict" in resolved
        assert "{" not in resolved


# ---------------------------------------------------------------------------
# Structural regression: Layer 1/Layer 2 vs Layer 3 separation
# ---------------------------------------------------------------------------


class TestStructuralRegressionLayerSeparation:
    """Structural regression test: no function in this module reads project_profile.json.

    No function reads delivery quality settings. This enforces the
    Layer 1/Layer 2 vs. Layer 3 separation (Section 3.25).
    """

    def test_load_toolchain_source_does_not_reference_project_profile(self):
        """load_toolchain source code does not contain 'project_profile' string."""
        source = inspect.getsource(load_toolchain)
        assert "project_profile" not in source.lower()

    def test_resolve_command_source_does_not_reference_project_profile(self):
        """resolve_command source code does not contain 'project_profile' string."""
        source = inspect.getsource(resolve_command)
        assert "project_profile" not in source.lower()

    def test_get_gate_composition_source_does_not_reference_project_profile(self):
        """get_gate_composition source code does not contain 'project_profile' string."""
        source = inspect.getsource(get_gate_composition)
        assert "project_profile" not in source.lower()

    def test_module_source_does_not_import_load_profile(self):
        """The module does not import load_profile from Unit 3."""
        import src.unit_4.stub as module

        source = inspect.getsource(module)
        assert "load_profile" not in source

    def test_module_source_does_not_reference_delivery_quality(self):
        """The module does not reference delivery quality settings."""
        import src.unit_4.stub as module

        source = inspect.getsource(module)
        # Should not reference delivery-layer quality config reading
        assert "get_delivery_config" not in source
        assert "get_quality_config" not in source

    def test_load_toolchain_does_not_read_profile_file(
        self, project_root_with_all_toolchains
    ):
        """Even when project_profile.json exists, load_toolchain does not read it."""
        # Create a profile file with a canary value
        profile_path = project_root_with_all_toolchains / "project_profile.json"
        profile_path.write_text(json.dumps({"canary": "should_not_appear"}))

        # Load pipeline toolchain - should not incorporate profile data
        result = load_toolchain(project_root_with_all_toolchains)
        assert "canary" not in str(result)
        assert "should_not_appear" not in str(result)

    def test_load_toolchain_python_does_not_read_profile_file(
        self, project_root_with_all_toolchains
    ):
        """Even when project_profile.json exists, language toolchain does not read it."""
        profile_path = project_root_with_all_toolchains / "project_profile.json"
        profile_path.write_text(json.dumps({"canary": "should_not_appear"}))

        result = load_toolchain(project_root_with_all_toolchains, language="python")
        assert "canary" not in str(result)
        assert "should_not_appear" not in str(result)


# ---------------------------------------------------------------------------
# Signature contracts: parameter types and defaults
# ---------------------------------------------------------------------------


class TestSignatureContracts:
    """Tests that function signatures match the blueprint Tier 2 definitions."""

    def test_load_toolchain_accepts_path_and_optional_language(self):
        """load_toolchain signature: (project_root: Path, language: Optional[str] = None)."""
        sig = inspect.signature(load_toolchain)
        params = list(sig.parameters.keys())
        assert "project_root" in params
        assert "language" in params
        assert sig.parameters["language"].default is None

    def test_resolve_command_signature(self):
        """resolve_command signature matches blueprint Tier 2."""
        sig = inspect.signature(resolve_command)
        params = list(sig.parameters.keys())
        assert "template" in params
        assert "env_name" in params
        assert "run_prefix" in params
        assert "target" in params
        assert "python_version" in params
        assert "flags" in params
        # Default values for optional params
        assert sig.parameters["target"].default == ""
        assert sig.parameters["python_version"].default == ""
        assert sig.parameters["flags"].default == ""

    def test_get_gate_composition_signature(self):
        """get_gate_composition signature: (toolchain: Dict, gate_id: str) -> List[Dict]."""
        sig = inspect.signature(get_gate_composition)
        params = list(sig.parameters.keys())
        assert "toolchain" in params
        assert "gate_id" in params
        assert len(params) == 2


# ---------------------------------------------------------------------------
# Edge cases: toolchain file content
# ---------------------------------------------------------------------------


class TestLoadToolchainEdgeCases:
    """Edge case tests for load_toolchain."""

    def test_toolchain_with_no_quality_key(self, tmp_path):
        """Toolchain without 'quality' key still loads successfully."""
        toolchain_path = tmp_path / "toolchain.json"
        data = {"version": "1.0", "other_key": "value"}
        toolchain_path.write_text(json.dumps(data))
        result = load_toolchain(tmp_path)
        assert result == data

    def test_toolchain_with_nested_structure(self, tmp_path):
        """Toolchain with deeply nested structure loads correctly."""
        data = {
            "quality": {
                "gate_a": [
                    {
                        "operation": "lint",
                        "command": "ruff check",
                        "config": {"severity": "error", "rules": ["E501", "W291"]},
                    }
                ]
            }
        }
        toolchain_path = tmp_path / "toolchain.json"
        toolchain_path.write_text(json.dumps(data))
        result = load_toolchain(tmp_path)
        assert result["quality"]["gate_a"][0]["config"]["severity"] == "error"

    def test_load_toolchain_path_type_is_path(self, tmp_path):
        """project_root parameter accepts a Path object."""
        toolchain_path = tmp_path / "toolchain.json"
        toolchain_path.write_text(json.dumps({"key": "value"}))
        result = load_toolchain(Path(tmp_path))
        assert isinstance(result, dict)


# ---------------------------------------------------------------------------
# Edge cases: resolve_command
# ---------------------------------------------------------------------------


class TestResolveCommandEdgeCases:
    """Edge case tests for resolve_command."""

    def test_template_with_repeated_placeholder(self):
        """Template with the same placeholder twice resolves both occurrences."""
        result = resolve_command(
            template="{run_prefix} and {run_prefix}",
            env_name="e",
            run_prefix="echo",
        )
        assert result == "echo and echo"

    def test_template_with_no_whitespace_issues(self):
        """Clean template with no extra whitespace passes through unchanged."""
        result = resolve_command(
            template="pytest -v tests/",
            env_name="e",
            run_prefix="",
        )
        assert result == "pytest -v tests/"

    def test_template_with_adjacent_placeholders(self):
        """Adjacent placeholders without space resolve correctly."""
        result = resolve_command(
            template="{run_prefix}{flags}",
            env_name="e",
            run_prefix="conda run",
            flags=" -v",
        )
        # Should produce "conda run -v" after collapse
        assert "conda run" in result
        assert "-v" in result

    def test_template_with_only_whitespace_after_resolution(self):
        """Template that resolves to only whitespace returns empty or minimal string."""
        result = resolve_command(
            template="{run_prefix} {flags} {target}",
            env_name="e",
            run_prefix="",
            flags="",
            target="",
        )
        # After collapsing spaces and stripping, result should be empty or minimal
        assert "  " not in result
        assert result == result.strip()


# ---------------------------------------------------------------------------
# verify_toolchain_ready (Bug S3-160)
# ---------------------------------------------------------------------------


class TestVerifyToolchainReady:
    """Tests for verify_toolchain_ready (Bug S3-160 / IMPROV-19)."""

    @pytest.fixture
    def toolchain_with_verify(self, tmp_path):
        """Write a pipeline toolchain.json with environment.verify_commands."""
        data = {
            "environment": {
                "tool": "conda",
                "run_prefix": "conda run -n {env_name}",
                "verify_commands": [
                    "{run_prefix} python --version",
                    "{run_prefix} pytest --version",
                ],
            },
            "quality": {},
        }
        (tmp_path / "toolchain.json").write_text(json.dumps(data, indent=2))
        return tmp_path

    def test_verify_toolchain_ready_success_path(self, toolchain_with_verify):
        """Mock runner returns 0 for all commands -> (True, [])."""
        from toolchain_reader import verify_toolchain_ready

        calls: list[str] = []

        def fake_runner(cmd: str) -> int:
            calls.append(cmd)
            return 0

        ok, errors = verify_toolchain_ready(
            toolchain_with_verify, "svp-test", runner=fake_runner
        )
        assert ok is True
        assert errors == []
        assert len(calls) == 2

    def test_verify_toolchain_ready_failure_path(self, toolchain_with_verify):
        """Mock runner returns non-zero for one command -> (False, [msg])."""
        from toolchain_reader import verify_toolchain_ready

        def fake_runner(cmd: str) -> int:
            # Fail on the pytest --version probe; pass on the python one.
            return 0 if "python --version" in cmd else 7

        ok, errors = verify_toolchain_ready(
            toolchain_with_verify, "svp-test", runner=fake_runner
        )
        assert ok is False
        assert len(errors) == 1
        assert "pytest --version" in errors[0]
        assert "returncode=7" in errors[0]

    def test_verify_toolchain_ready_uses_manifest_verify_commands(
        self, toolchain_with_verify
    ):
        """Recorded commands match the manifest's verify_commands after substitution."""
        from toolchain_reader import verify_toolchain_ready

        calls: list[str] = []

        def fake_runner(cmd: str) -> int:
            calls.append(cmd)
            return 0

        verify_toolchain_ready(
            toolchain_with_verify, "svp-myproj", runner=fake_runner
        )
        # Both commands present
        assert any("python --version" in c for c in calls)
        assert any("pytest --version" in c for c in calls)
        # {run_prefix} and {env_name} fully substituted
        for c in calls:
            assert "{run_prefix}" not in c
            assert "{env_name}" not in c
            assert "conda run -n svp-myproj" in c

    def test_verify_toolchain_ready_returns_true_when_no_verify_commands(
        self, tmp_path
    ):
        """Manifest without verify_commands -> trivially (True, [])."""
        from toolchain_reader import verify_toolchain_ready

        data = {
            "environment": {
                "tool": "conda",
                "run_prefix": "conda run -n {env_name}",
            },
            "quality": {},
        }
        (tmp_path / "toolchain.json").write_text(json.dumps(data, indent=2))

        ok, errors = verify_toolchain_ready(
            tmp_path, "svp-test", runner=lambda cmd: 1
        )
        assert ok is True
        assert errors == []

    def test_verify_toolchain_ready_collects_multiple_failures(
        self, toolchain_with_verify
    ):
        """Multiple failing commands yield multiple error messages."""
        from toolchain_reader import verify_toolchain_ready

        ok, errors = verify_toolchain_ready(
            toolchain_with_verify, "svp-test", runner=lambda cmd: 5
        )
        assert ok is False
        assert len(errors) == 2
