from typing import Any, Dict, List, NamedTuple, Optional, Set

__SVP_STUB__ = True  # DO NOT DELIVER -- stub file generated by SVP

class RunResult(NamedTuple):
    status: str = None
    passed: int = None
    failed: int = None
    errors: int = None
    output: str = None
    collection_error: bool = None

class QualityResult(NamedTuple):
    status: str = None
    auto_fixed: bool = None
    residuals: List[str] = None
    report: str = None

LANGUAGE_REGISTRY: Dict[str, Dict[str, Any]] = {}
FULL_REQUIRED_KEYS: Set[str] = set()
COMPONENT_REQUIRED_KEYS: Set[str] = set()
def get_language_config(language: str) -> Dict[str, Any]:
    raise NotImplementedError()

def validate_registry_entry(entry: Dict[str, Any]) -> List[str]:
    raise NotImplementedError()

def validate_component_entry(entry: Dict[str, Any]) -> List[str]:
    raise NotImplementedError()

def load_registry_extensions(extensions_path: str) -> Dict[str, Dict[str, Any]]:
    raise NotImplementedError()
