from typing import Any, Callable, Dict
from pathlib import Path

__SVP_STUB__ = True  # DO NOT DELIVER -- stub file generated by SVP

SIGNATURE_PARSERS: Dict[str, Callable[[str, Dict[str, Any]], Any]] = {}
def parse_signatures(source: str, language: str, language_config: Dict[str, Any]) -> Any:
    raise NotImplementedError()

def main(argv: list = None) -> None:
    raise NotImplementedError()
