from typing import Any, Dict, List, Optional, Set
from pathlib import Path
from dataclasses import dataclass

__SVP_STUB__ = True  # DO NOT DELIVER -- stub file generated by SVP

class UnitDefinition:
    number: int = None
    name: str = None
    tier1: str = None
    tier2: str = None
    tier3: str = None
    dependencies: List[int] = None
    languages: Set[str] = None
    machinery: bool = None

def extract_units(blueprint_dir: Path) -> List[UnitDefinition]:
    raise NotImplementedError()

def build_unit_context(unit: UnitDefinition, all_units: List[UnitDefinition], include_tier1: bool = True) -> str:
    raise NotImplementedError()

def detect_code_block_language(blueprint_dir: Path, unit_number: int) -> Set[str]:
    raise NotImplementedError()
