from typing import Any, Dict, List, Optional
from pathlib import Path

__SVP_STUB__ = True  # DO NOT DELIVER -- stub file generated by SVP

def load_toolchain(project_root: Path, language: Optional[str] = None) -> Dict[str, Any]:
    raise NotImplementedError()

def resolve_command(template: str, env_name: str, run_prefix: str, target: str = '', python_version: str = '', flags: str = '') -> str:
    raise NotImplementedError()

def get_gate_composition(toolchain: Dict[str, Any], gate_id: str) -> List[Dict[str, str]]:
    raise NotImplementedError()
