from typing import Any, Dict, List, Optional
from pathlib import Path

__SVP_STUB__ = True  # DO NOT DELIVER -- stub file generated by SVP

def append_entry(ledger_path: Path, role: str, content: str, tags: Optional[List[str]] = None) -> None:
    raise NotImplementedError()

def read_ledger(ledger_path: Path) -> List[Dict[str, Any]]:
    raise NotImplementedError()

def compact_ledger(ledger_path: Path, character_threshold: int = 200) -> None:
    raise NotImplementedError()

def clear_ledger(ledger_path: Path) -> None:
    raise NotImplementedError()

def get_ledger_path(project_root: Path, ledger_type: str, session_number: Optional[int] = None) -> Path:
    raise NotImplementedError()
