from typing import Any, Dict, Optional

__SVP_STUB__ = True  # DO NOT DELIVER -- stub file generated by SVP

def assemble_hint_prompt(hint_text: str, agent_type: str, ladder_position: Optional[str], unit_number: Optional[int], gate_context: Optional[str]) -> str:
    raise NotImplementedError()
