from typing import Any, Dict, List, Optional
from pathlib import Path
import json

__SVP_STUB__ = True  # DO NOT DELIVER -- stub file generated by SVP

ARTIFACT_FILENAMES: Dict[str, str] = {}
DEFAULT_CONFIG: Dict[str, Any] = {}
def load_config(project_root: Path) -> Dict[str, Any]:
    raise NotImplementedError()

def save_config(project_root: Path, config: Dict[str, Any]) -> None:
    raise NotImplementedError()

def derive_env_name(project_root: Path) -> str:
    raise NotImplementedError()

def get_blueprint_dir(project_root: Path) -> Path:
    raise NotImplementedError()

def get_model_for_agent(agent_key: str, config: Dict[str, Any], profile: Dict[str, Any]) -> str:
    raise NotImplementedError()
