"""Cycle K-2 (S3-204) -- stub generator selective TYPE_CHECKING wrap.

S3-47 originally wrapped every non-stdlib (upstream) import in
``if TYPE_CHECKING:`` on the premise that "stubs never execute upstream
code at runtime, so upstream imports are only needed for type annotations."
The premise was incomplete: function/method bodies are
``raise NotImplementedError()``, but Python evaluates **class base
classes, decorators, and default argument values at module-load time**.
A Tier-2 signature like ``class DataLoadError(WGCNAError): ...`` evaluates
``WGCNAError`` when the stub module is imported -- so wrapping
``from wgcna.config import WGCNAError`` under ``TYPE_CHECKING`` (False at
runtime) raises ``NameError`` at exec-time, even though the stub
``compile()``s cleanly.

The fix: ``_generate_python_stub`` walks the parsed Tier-2 body to
identify upstream-imported names referenced at module-load time
(``ClassDef.bases``/``keywords``, ``decorator_list``,
``arguments.defaults``/``kw_defaults``, ``Assign.value``/``AnnAssign.value``).
Imports providing those names emit OUTSIDE the ``TYPE_CHECKING`` guard;
type-only-use imports stay INSIDE.

These tests use ``exec()`` -- not just ``compile()`` -- because module-load
NameErrors are runtime errors that ``compile()`` does not detect (Pattern
P89 test discipline; C-10-K2b acceptance mandate).

Pattern reference: P89 (TYPE_CHECKING wraps must be selective re
module-load-time references).
"""

from __future__ import annotations

import ast
import sys
import textwrap
import types

from stub_generator import _generate_python_stub


PYTHON_SENTINEL = "_SVP_SENTINEL_TOKEN_ = True  # DO NOT DELIVER -- stub file generated by SVP"

PYTHON_LANGUAGE_CONFIG = {
    "id": "python",
    "stub_generator_key": "python",
    "stub_sentinel": PYTHON_SENTINEL,
    "is_component_only": False,
}


def _make_ast(source: str) -> ast.Module:
    return ast.parse(source)


def _install_fake_upstream_modules() -> dict:
    """Install synthetic upstream modules so the stub can `exec` cleanly.

    Returns a snapshot of which modules were installed, so tests can clean up.
    """
    installed: dict = {}
    wgcna_pkg = types.ModuleType("wgcna")
    wgcna_config = types.ModuleType("wgcna.config")

    class WGCNAError(Exception):
        pass

    def log_event(cls):
        return cls

    wgcna_config.WGCNAError = WGCNAError
    wgcna_config.log_event = log_event
    wgcna_config.RAW_DEFAULT = "raw_default"
    wgcna_types = types.ModuleType("wgcna.types")
    wgcna_types.LoadResult = list
    wgcna_pkg.config = wgcna_config
    wgcna_pkg.types = wgcna_types
    for name, mod in [
        ("wgcna", wgcna_pkg),
        ("wgcna.config", wgcna_config),
        ("wgcna.types", wgcna_types),
    ]:
        installed[name] = sys.modules.get(name)
        sys.modules[name] = mod
    return installed


def _restore_modules(snapshot: dict) -> None:
    for name, prior in snapshot.items():
        if prior is None:
            sys.modules.pop(name, None)
        else:
            sys.modules[name] = prior


def _exec_stub(stub_source: str) -> dict:
    """Compile + exec the stub. Returns the module namespace."""
    snapshot = _install_fake_upstream_modules()
    try:
        ns: dict = {}
        exec(compile(stub_source, "<k2_stub>", "exec"), ns)
        return ns
    finally:
        _restore_modules(snapshot)


# ---------------------------------------------------------------------------
# K-2 tests (6) -- selective TYPE_CHECKING wrap
# ---------------------------------------------------------------------------


def test_k2_class_base_from_upstream_runtime_imports():
    """The actual K-2 bug: class declares an upstream symbol as base.
    Pre-fix, the stub failed at exec with `NameError: name 'WGCNAError' is
    not defined` because `from wgcna.config import WGCNAError` was wrapped
    in `if TYPE_CHECKING:` (False at runtime). Post-fix, the import emits
    at runtime so the class declaration succeeds."""
    source = textwrap.dedent("""\
        from __future__ import annotations
        from wgcna.config import WGCNAError

        class DataLoadError(WGCNAError):
            def __init__(self, msg: str) -> None:
                ...
    """)
    parsed = _make_ast(source)
    stub = _generate_python_stub(parsed, PYTHON_LANGUAGE_CONFIG)
    # The runtime-required import must NOT be inside TYPE_CHECKING.
    assert "from wgcna.config import WGCNAError" in stub
    # Find the position of the runtime import vs the TYPE_CHECKING block.
    if "if TYPE_CHECKING:" in stub:
        runtime_pos = stub.index("from wgcna.config import WGCNAError")
        guard_pos = stub.index("if TYPE_CHECKING:")
        assert runtime_pos < guard_pos, (
            "WGCNAError import must emit BEFORE TYPE_CHECKING guard"
        )
    ns = _exec_stub(stub)
    assert "DataLoadError" in ns
    assert issubclass(ns["DataLoadError"], Exception)


def test_k2_decorator_from_upstream_runtime_imports():
    """Decorator references evaluate at function/class-definition time
    (module load). Upstream-imported decorators must emit at runtime."""
    source = textwrap.dedent("""\
        from __future__ import annotations
        from wgcna.config import log_event

        @log_event
        class Loader:
            def run(self) -> None:
                ...
    """)
    parsed = _make_ast(source)
    stub = _generate_python_stub(parsed, PYTHON_LANGUAGE_CONFIG)
    assert "from wgcna.config import log_event" in stub
    ns = _exec_stub(stub)
    assert "Loader" in ns


def test_k2_default_arg_from_upstream_runtime_imports():
    """Default argument values are evaluated at function-definition time
    (module load). Upstream symbols referenced in defaults must emit at
    runtime."""
    source = textwrap.dedent("""\
        from __future__ import annotations
        from wgcna.config import RAW_DEFAULT

        def load_data(path: str = RAW_DEFAULT) -> None:
            ...
    """)
    parsed = _make_ast(source)
    stub = _generate_python_stub(parsed, PYTHON_LANGUAGE_CONFIG)
    assert "from wgcna.config import RAW_DEFAULT" in stub
    ns = _exec_stub(stub)
    assert "load_data" in ns


def test_k2_module_level_assign_value_from_upstream_runtime_imports():
    """Module-level assignment values are evaluated at module load.
    Upstream symbols on the RHS must emit at runtime."""
    source = textwrap.dedent("""\
        from __future__ import annotations
        from wgcna.config import RAW_DEFAULT

        DEFAULT_PATH: str = RAW_DEFAULT

        def use_it() -> str:
            ...
    """)
    parsed = _make_ast(source)
    stub = _generate_python_stub(parsed, PYTHON_LANGUAGE_CONFIG)
    assert "from wgcna.config import RAW_DEFAULT" in stub
    ns = _exec_stub(stub)
    assert ns.get("DEFAULT_PATH") == "raw_default"


def test_k2_pure_annotation_use_stays_type_checking():
    """Upstream symbols referenced ONLY in annotations stay under
    TYPE_CHECKING (preserves S3-47 import-path-resolution-variability
    isolation for the type-only case)."""
    source = textwrap.dedent("""\
        from __future__ import annotations
        from wgcna.types import LoadResult

        def load(path: str) -> LoadResult:
            ...
    """)
    parsed = _make_ast(source)
    stub = _generate_python_stub(parsed, PYTHON_LANGUAGE_CONFIG)
    # Annotation-only upstream MUST be inside the TYPE_CHECKING guard.
    assert "if TYPE_CHECKING:" in stub
    guard_idx = stub.index("if TYPE_CHECKING:")
    after_guard = stub[guard_idx:]
    assert "from wgcna.types import LoadResult" in after_guard, (
        "annotation-only upstream import MUST emit inside TYPE_CHECKING"
    )
    # Annotations are stringified by `from __future__ annotations`, so
    # the stub still execs cleanly without the upstream module loadable.
    snapshot = sys.modules.pop("wgcna.types", None)
    try:
        sys.modules.pop("wgcna.types", None)
        # Don't install wgcna.types: stub must exec without it.
        ns: dict = {}
        exec(compile(stub, "<k2_anno_only>", "exec"), ns)
        assert "load" in ns
    finally:
        if snapshot is not None:
            sys.modules["wgcna.types"] = snapshot


def test_k2_mixed_runtime_and_annotation_uses_emit_at_runtime():
    """When a single import line binds both a runtime-used name and an
    annotation-only name, the entire line emits at runtime (conservative
    classification; safe for runtime use, retains type-resolution
    availability). C-10-K2a final clause."""
    source = textwrap.dedent("""\
        from __future__ import annotations
        from wgcna.config import WGCNAError, RAW_DEFAULT

        # WGCNAError is used as a class base (runtime).
        # RAW_DEFAULT is used only as a default arg value (runtime).
        # Both are runtime; the line emits at runtime.

        class CustomError(WGCNAError):
            def __init__(self, msg: str = RAW_DEFAULT) -> None:
                ...
    """)
    parsed = _make_ast(source)
    stub = _generate_python_stub(parsed, PYTHON_LANGUAGE_CONFIG)
    # The shared import line must emit OUTSIDE TYPE_CHECKING.
    assert "from wgcna.config import WGCNAError, RAW_DEFAULT" in stub
    if "if TYPE_CHECKING:" in stub:
        runtime_pos = stub.index("from wgcna.config import WGCNAError, RAW_DEFAULT")
        guard_pos = stub.index("if TYPE_CHECKING:")
        assert runtime_pos < guard_pos
    ns = _exec_stub(stub)
    assert "CustomError" in ns
