"""Cycle H7 (S3-197) -- verify stub generation robustness fixes.

(a) `_generate_python_stub` emits ``from __future__ import annotations`` as the
    FIRST line of every stub, unconditionally, BEFORE the ``_SVP_SENTINEL_TOKEN_``
    sentinel (R1 #7). Per Python PEP 236, ``from __future__`` imports MUST
    precede any runtime statement (including the sentinel assignment). Sub-units
    of shared modules with Tier-2-signature-only blueprints (no upstream
    imports) previously emitted no preamble and NameError'd on annotations like
    ``Any`` or ``OpenAI`` at conftest exec time.

(b) `_parse_python_signatures` regex-strips ``, ...`` pseudocode from Tier-2
    blocks before ``ast.parse`` (R1 #9). Tier-2 signature blocks commonly
    contain ``{"key": "val", ...}`` bare-ellipsis pseudocode that Python rejects
    with SyntaxError. The fix uses ``re.sub(r",\\s*\\.\\.\\.", "", source)``
    before parsing; valid Python is unchanged (no real code uses this pattern).

Pattern reference: P81 (Stub generator robustness).
"""

from __future__ import annotations

import ast
import textwrap

from signature_parser import _parse_python_signatures
from stub_generator import _generate_python_stub


# ---------------------------------------------------------------------------
# Helpers / fixtures
# ---------------------------------------------------------------------------

PYTHON_SENTINEL = "_SVP_SENTINEL_TOKEN_ = True  # DO NOT DELIVER -- stub file generated by SVP"

PYTHON_LANGUAGE_CONFIG = {
    "id": "python",
    "stub_generator_key": "python",
    "stub_sentinel": PYTHON_SENTINEL,
    "is_component_only": False,
}

FUTURE_LINE = "from __future__ import annotations"


def _make_ast(source: str) -> ast.Module:
    """Parse Python source into an AST module (mirrors Unit 9's parser)."""
    return ast.parse(source)


def _first_non_blank_line(stub: str) -> str:
    for line in stub.split("\n"):
        if line.strip():
            return line
    return ""


# ---------------------------------------------------------------------------
# R1 #7 tests (5) -- preamble emission unconditionality + sentinel placement
# ---------------------------------------------------------------------------


def test_h7_stub_has_future_annotations_as_first_line_no_upstream_imports():
    """The actual R1 #7 bug: NO upstream/stdlib imports -> from __future__ is
    still line 1 (the gate on upstream_imports being non-empty is removed)."""
    source = textwrap.dedent("""\
        def foo(x):
            ...
    """)
    parsed = _make_ast(source)
    stub = _generate_python_stub(parsed, PYTHON_LANGUAGE_CONFIG)
    assert _first_non_blank_line(stub) == FUTURE_LINE, (
        f"Stub line 1 must be {FUTURE_LINE!r}; got stub:\n{stub}"
    )


def test_h7_stub_has_future_annotations_when_only_stdlib_imports():
    """stdlib imports only + no upstream imports -> from __future__ is line 1;
    stdlib imports follow the sentinel."""
    source = textwrap.dedent("""\
        import json
        from pathlib import Path

        def foo() -> Path:
            ...
    """)
    parsed = _make_ast(source)
    stub = _generate_python_stub(parsed, PYTHON_LANGUAGE_CONFIG)
    assert _first_non_blank_line(stub) == FUTURE_LINE
    # stdlib imports are present and follow the sentinel
    assert "import json" in stub
    assert "from pathlib import Path" in stub
    sentinel_idx = stub.index(PYTHON_SENTINEL)
    json_idx = stub.index("import json")
    assert sentinel_idx < json_idx, "stdlib imports must follow the sentinel"


def test_h7_stub_has_future_annotations_when_upstream_imports_exist():
    """Regression guard: original case (upstream imports non-empty) still has
    from __future__ as line 1; behavior unchanged in this respect."""
    source = textwrap.dedent("""\
        from openai import OpenAI

        def foo(client: OpenAI) -> None:
            ...
    """)
    parsed = _make_ast(source)
    stub = _generate_python_stub(parsed, PYTHON_LANGUAGE_CONFIG)
    assert _first_non_blank_line(stub) == FUTURE_LINE
    # upstream import is wrapped in TYPE_CHECKING guard
    assert "TYPE_CHECKING" in stub
    assert "from openai import OpenAI" in stub


def test_h7_stub_with_Any_annotation_executes_without_NameError():
    """End-to-end: build a stub with `Any` in the annotation but NO `Any`
    import. Under from __future__ import annotations, annotations become
    strings -- exec(stub) should NOT raise NameError."""
    source = textwrap.dedent("""\
        def foo(x: Any) -> Any:
            ...
    """)
    parsed = _make_ast(source)
    stub = _generate_python_stub(parsed, PYTHON_LANGUAGE_CONFIG)
    # Confirm Any is not imported at module top level
    assert "from typing import Any" not in stub.split(PYTHON_SENTINEL)[0]
    # exec the stub in an isolated namespace -- must not NameError
    namespace: dict = {}
    exec(stub, namespace)  # noqa: S102 -- intentional exec for stub validation
    assert "foo" in namespace, "Stub must define `foo` after exec"


def test_h7_stub_sentinel_placement_after_future_import():
    """The _SVP_SENTINEL_TOKEN_ assignment must come AFTER `from __future__ import
    annotations` (PEP 236 requirement: from __future__ precedes runtime
    statements, including assignments)."""
    source = textwrap.dedent("""\
        def foo():
            ...
    """)
    parsed = _make_ast(source)
    stub = _generate_python_stub(parsed, PYTHON_LANGUAGE_CONFIG)
    lines = stub.split("\n")
    future_idx = None
    sentinel_idx = None
    for i, line in enumerate(lines):
        if FUTURE_LINE in line and future_idx is None:
            future_idx = i
        if PYTHON_SENTINEL in line and sentinel_idx is None:
            sentinel_idx = i
    assert future_idx is not None, "from __future__ line must be present"
    assert sentinel_idx is not None, "Sentinel line must be present"
    assert sentinel_idx > future_idx, (
        f"Sentinel (line {sentinel_idx}) must come AFTER from __future__ "
        f"(line {future_idx})"
    )


# ---------------------------------------------------------------------------
# R1 #9 tests (3) -- pseudocode preprocessing in _parse_python_signatures
# ---------------------------------------------------------------------------


def test_h7_signature_parser_handles_bare_ellipsis_in_dict_literal():
    """The R1 #9 bug: source containing {"key": "val", ...} parses without
    SyntaxError after the regex preprocess strips the bare ', ...' pattern."""
    source = textwrap.dedent("""\
        def foo() -> dict:
            return {"key": "val", ...}
    """)
    # Should NOT raise SyntaxError
    result = _parse_python_signatures(source, {})
    assert result is not None
    assert isinstance(result, ast.Module)


def test_h7_signature_parser_preserves_valid_python_unchanged():
    """Regression guard: valid Python with no ', ...' patterns produces an AST
    structurally identical to plain ast.parse(source)."""
    source = textwrap.dedent("""\
        def foo() -> dict:
            return {"key": "val"}
    """)
    expected = ast.parse(source)
    result = _parse_python_signatures(source, {})
    assert ast.dump(result) == ast.dump(expected)


def test_h7_signature_parser_handles_multiple_ellipsis_patterns_in_one_block():
    """Multiple {"a": 1, ...} patterns in one source string all stripped, so
    the whole block parses cleanly."""
    source = textwrap.dedent("""\
        def foo() -> dict:
            return {"a": 1, ...}

        def bar() -> dict:
            return {"b": 2, ...}
    """)
    # Should NOT raise SyntaxError
    result = _parse_python_signatures(source, {})
    assert result is not None
    assert isinstance(result, ast.Module)
    # Both functions must be present after parsing
    func_names = [
        n.name for n in ast.walk(result) if isinstance(n, ast.FunctionDef)
    ]
    assert "foo" in func_names
    assert "bar" in func_names


# ---------------------------------------------------------------------------
# Cross-fix integration (1) -- both R1 #7 and R1 #9 fixes work together
# ---------------------------------------------------------------------------


def test_h7_full_stub_pipeline_with_dict_pseudocode_and_no_upstream_imports():
    """End-to-end: blueprint Tier-2 source contains {"foo": "bar", ...} AND has
    no upstream imports. R1 #9 strips the bare ellipsis; R1 #7 emits the
    from __future__ preamble first; the resulting stub exec()s cleanly."""
    source = textwrap.dedent("""\
        def foo() -> dict:
            return {"key": "val", ...}
    """)
    # R1 #9: parse without SyntaxError despite the bare ellipsis
    parsed = _parse_python_signatures(source, {})
    assert isinstance(parsed, ast.Module)
    # R1 #7: stub has from __future__ as line 1, no upstream imports needed
    stub = _generate_python_stub(parsed, PYTHON_LANGUAGE_CONFIG)
    assert _first_non_blank_line(stub) == FUTURE_LINE
    # Sentinel comes after from __future__
    future_idx = stub.index(FUTURE_LINE)
    sentinel_idx = stub.index(PYTHON_SENTINEL)
    assert sentinel_idx > future_idx
    # Stub exec()s without NameError
    namespace: dict = {}
    exec(stub, namespace)  # noqa: S102 -- intentional exec for stub validation
    assert "foo" in namespace
