"""Cycle K-1 (S3-203) -- stub generator dedupes leading __future__ imports.

When a Tier-2 blueprint signature begins with ``from __future__ import
annotations`` (the canonical Python idiom adopted by every Python unit),
the stub generator previously emitted TWO copies of that line: one at
file-line 1 (the unconditional always-prepend introduced by S3-197 / R1 #7)
AND one after the ``_SVP_SENTINEL_TOKEN_`` sentinel (re-emitted from
``stdlib_imports`` because ``__future__`` is in ``_STDLIB_MODULES``). The
second copy violates PEP 236 (``from __future__ imports must occur at the
beginning of the file``) and produces ``SyntaxError`` at compile time, even
though ``ast.parse()`` accepts the file.

The fix: ``_generate_python_stub`` filters ``ast.ImportFrom`` nodes whose
``module == "__future__"`` out of the per-node import collection BEFORE
classification into ``stdlib_imports``/``upstream_imports``. The
always-prepended copy from S3-197 / C-10-H7a remains the canonical line.

These tests use ``compile()`` -- not just ``ast.parse()`` -- because PEP 236
is a compile-time rule, not a parse-time rule (Pattern P88 test discipline).

Pattern reference: P88 (Always-prepend imports must dedupe against
source-side copies).
"""

from __future__ import annotations

import ast
import textwrap

from stub_generator import _generate_python_stub


PYTHON_SENTINEL = "_SVP_SENTINEL_TOKEN_ = True  # DO NOT DELIVER -- stub file generated by SVP"

PYTHON_LANGUAGE_CONFIG = {
    "id": "python",
    "stub_generator_key": "python",
    "stub_sentinel": PYTHON_SENTINEL,
    "is_component_only": False,
}

FUTURE_LINE = "from __future__ import annotations"


def _make_ast(source: str) -> ast.Module:
    return ast.parse(source)


def test_k1_leading_future_in_signature_compiles_cleanly():
    """The actual K-1 bug: signature begins with ``from __future__ import
    annotations`` (the canonical SVP/Python idiom). Pre-fix, the generator
    emitted two copies and the stub failed to compile()."""
    source = textwrap.dedent("""\
        from __future__ import annotations
        from typing import Any, Dict, List
        from pathlib import Path

        def process_data(input_path: Path, config: Dict[str, Any]) -> List[str]:
            ...
    """)
    parsed = _make_ast(source)
    stub = _generate_python_stub(parsed, PYTHON_LANGUAGE_CONFIG)
    # PEP 236 is a compile-time rule; ast.parse() does not enforce it.
    compile(stub, "<k1_stub>", "exec")


def test_k1_exactly_one_future_import_in_output():
    """The dedup invariant: the generated stub MUST contain exactly one
    ``from __future__ import annotations`` line, regardless of whether the
    source signature itself had one. Two copies would re-trip PEP 236."""
    source_with_future = textwrap.dedent("""\
        from __future__ import annotations
        from typing import Any

        def foo(x: Any) -> Any:
            ...
    """)
    parsed = _make_ast(source_with_future)
    stub = _generate_python_stub(parsed, PYTHON_LANGUAGE_CONFIG)
    count = stub.count(FUTURE_LINE)
    assert count == 1, (
        f"Expected exactly 1 occurrence of {FUTURE_LINE!r}, got {count}.\n"
        f"Stub:\n{stub}"
    )


def test_k1_no_future_in_signature_unchanged():
    """Idempotence: signatures WITHOUT a leading ``from __future__`` MUST
    produce the same output as before the dedup fix. Verifies the fix has
    no behavior change for the prior test fixture shape."""
    source_no_future = textwrap.dedent("""\
        from typing import Any, Dict, List
        from pathlib import Path

        def process_data(input_path: Path, config: Dict[str, Any]) -> List[str]:
            ...
    """)
    parsed = _make_ast(source_no_future)
    stub = _generate_python_stub(parsed, PYTHON_LANGUAGE_CONFIG)
    # The S3-197 always-prepend still emits exactly one copy.
    assert stub.count(FUTURE_LINE) == 1, (
        f"Always-prepend (S3-197) MUST still emit exactly 1 copy.\n"
        f"Stub:\n{stub}"
    )
    compile(stub, "<k1_stub_no_future>", "exec")


def test_k1_dedup_does_not_drop_other_stdlib_imports():
    """The filter targets ``__future__`` ImportFrom nodes ONLY -- other
    stdlib imports (typing, pathlib, json, etc.) MUST still appear in the
    post-sentinel stdlib block. Verifies the filter is not over-broad."""
    source = textwrap.dedent("""\
        from __future__ import annotations
        from typing import Any, Dict, List
        from pathlib import Path
        import json

        def foo(x: Any, p: Path, payload: str) -> Dict[str, List[str]]:
            ...
    """)
    parsed = _make_ast(source)
    stub = _generate_python_stub(parsed, PYTHON_LANGUAGE_CONFIG)
    # All three real stdlib imports must survive into the stub.
    assert "from typing import Any, Dict, List" in stub, (
        f"typing import lost.\nStub:\n{stub}"
    )
    assert "from pathlib import Path" in stub, (
        f"pathlib import lost.\nStub:\n{stub}"
    )
    assert "import json" in stub, f"json import lost.\nStub:\n{stub}"
    # And the deduped __future__ MUST still be exactly one copy.
    assert stub.count(FUTURE_LINE) == 1
    compile(stub, "<k1_stub_multi>", "exec")
