from typing import Any, Dict, List, Optional, Set
from pathlib import Path
import json

__SVP_STUB__ = True  # DO NOT DELIVER -- stub file generated by SVP

VALID_STAGES: Set[str] = set()
VALID_SUB_STAGES: Dict[str, Set[Optional[str]]] = {}
VALID_FIX_LADDER_POSITIONS: List[Optional[str]] = []
VALID_DEBUG_PHASES: Set[str] = set()
VALID_ORACLE_PHASES: Set[Optional[str]] = set()
class PipelineState:
    stage: str = None
    sub_stage: Optional[str] = None
    current_unit: Optional[int] = None
    total_units: int = None
    verified_units: List[Dict[str, Any]] = None
    alignment_iterations: int = None
    fix_ladder_position: Optional[str] = None
    red_run_retries: int = None
    pass_history: List[Dict[str, Any]] = None
    debug_session: Optional[Dict[str, Any]] = None
    debug_history: List[Dict[str, Any]] = None
    redo_triggered_from: Optional[Dict[str, Any]] = None
    delivered_repo_path: Optional[str] = None
    primary_language: str = None
    component_languages: List[str] = None
    secondary_language: Optional[str] = None
    oracle_session_active: bool = None
    oracle_test_project: Optional[str] = None
    oracle_phase: Optional[str] = None
    oracle_run_count: int = None
    oracle_nested_session_path: Optional[str] = None
    state_hash: Optional[str] = None
    spec_revision_count: int = None
    pass_: Optional[int] = None
    pass2_nested_session_path: Optional[str] = None
    deferred_broken_units: List[int] = None

def load_state(project_root: Path) -> PipelineState:
    raise NotImplementedError()

def save_state(project_root: Path, state: PipelineState) -> None:
    raise NotImplementedError()
