"""Unit 2: Language Registry.

Provides the LANGUAGE_REGISTRY, result types, validation functions,
and extension-loading capability for the SVP 2.2 pipeline.
"""

import copy
import json
import os
from typing import Any, Dict, List, NamedTuple, Set

# ---------------------------------------------------------------------------
# Result types
# ---------------------------------------------------------------------------


class RunResult(NamedTuple):
    status: str  # 'TESTS_PASSED', 'TESTS_FAILED', 'TESTS_ERROR', 'COLLECTION_ERROR'
    passed: int
    failed: int
    errors: int
    output: str
    collection_error: bool


class QualityResult(NamedTuple):
    status: str  # 'QUALITY_CLEAN', 'QUALITY_AUTO_FIXED', 'QUALITY_RESIDUAL', 'QUALITY_ERROR'
    auto_fixed: bool
    residuals: List[str]
    report: str


# ---------------------------------------------------------------------------
# Language registry data
# ---------------------------------------------------------------------------

LANGUAGE_REGISTRY: Dict[str, Dict[str, Any]] = {
    "python": {
        "id": "python",
        "display_name": "Python",
        "file_extension": ".py",
        "source_dir": "src",
        "test_dir": "tests",
        "test_file_pattern": "test_*.py",
        "toolchain_file": "python_conda_pytest.json",
        "environment_manager": "conda",
        "test_framework": "pytest",
        "version_check_command": "python --version",
        "stub_sentinel": (
            "__SVP_STUB__ = True  # DO NOT DELIVER -- stub file generated by SVP"
        ),
        "stub_generator_key": "python",
        "test_output_parser_key": "python",
        "quality_runner_key": "python",
        "is_component_only": False,
        "compatible_hosts": [],
        "bridge_libraries": {
            "python_r": {"library": "rpy2", "conda_package": "rpy2"},
        },
        "collection_error_indicators": [
            "ERROR collecting",
            "ImportError",
            "ModuleNotFoundError",
            "SyntaxError",
            "no tests ran",
        ],
        "authorized_write_dirs": ["src", "tests", "."],
        "default_delivery": {
            "environment_recommendation": "conda",
            "dependency_format": "environment.yml",
            "source_layout": "conventional",
            "entry_points": False,
        },
        "default_quality": {
            "linter": "ruff",
            "formatter": "ruff",
            "type_checker": "mypy",
            "import_sorter": "ruff",
            "line_length": 88,
        },
        "valid_linters": {"ruff", "flake8", "pylint", "none"},
        "valid_formatters": {"ruff", "black", "autopep8", "none"},
        "valid_type_checkers": {"mypy", "pyright", "none"},
        "valid_source_layouts": ["conventional", "flat", "svp_native"],
        "environment_file_name": "environment.yml",
        "project_manifest_file": "pyproject.toml",
        "gitignore_patterns": [
            "__pycache__/",
            "*.pyc",
            ".mypy_cache/",
            "dist/",
            "*.egg-info/",
        ],
        "entry_point_mechanism": "pyproject_scripts",
        "quality_config_mapping": {
            "ruff": "ruff.toml",
            "black": "pyproject.toml [tool.black]",
            "flake8": ".flake8",
            "mypy": "pyproject.toml [tool.mypy]",
            "pyright": "pyproject.toml [tool.pyright]",
        },
        "non_source_embedding": "module_level_string",
        "agent_prompts": {
            "test_agent": "Write pytest tests for the given unit.",
            "implementation_agent": "Implement the given unit following blueprint contracts.",
            "coverage_review_agent": "Review test coverage for the given unit.",
        },
    },
    "r": {
        "id": "r",
        "display_name": "R",
        "file_extension": ".R",
        "source_dir": "R",
        "test_dir": "tests/testthat",
        "test_file_pattern": "test-*.R",
        "toolchain_file": "r_renv_testthat.json",
        "environment_manager": "renv",
        "test_framework": "testthat",
        "version_check_command": "Rscript --version",
        "stub_sentinel": (
            "# __SVP_STUB__ <- TRUE  # DO NOT DELIVER -- stub file generated by SVP"
        ),
        "stub_generator_key": "r",
        "test_output_parser_key": "r",
        "quality_runner_key": "r",
        "is_component_only": False,
        "compatible_hosts": [],
        "bridge_libraries": {
            "r_python": {"library": "reticulate", "conda_package": "r-reticulate"},
        },
        "collection_error_indicators": [
            "Error in library",
            "there is no package called",
            "could not find function",
        ],
        "authorized_write_dirs": ["R", "tests/testthat", "."],
        "default_delivery": {
            "environment_recommendation": "renv",
            "dependency_format": "renv.lock",
            "source_layout": "package",
            "entry_points": False,
        },
        "default_quality": {
            "linter": "lintr",
            "formatter": "styler",
            "type_checker": "none",
            "line_length": 80,
        },
        "valid_linters": {"lintr", "none"},
        "valid_formatters": {"styler", "none"},
        "valid_type_checkers": {"none"},
        "valid_source_layouts": ["package", "scripts"],
        "environment_file_name": "renv.lock",
        "project_manifest_file": "DESCRIPTION",
        "gitignore_patterns": [
            ".Rhistory",
            ".RData",
            ".Rproj.user/",
            "inst/doc/",
        ],
        "entry_point_mechanism": "namespace_exports",
        "quality_config_mapping": {
            "lintr": ".lintr",
            "styler": ".styler.R",
        },
        "non_source_embedding": "toplevel_character",
        "agent_prompts": {
            "test_agent": "Write testthat tests for the given unit.",
            "implementation_agent": "Implement the given unit following blueprint contracts.",
            "coverage_review_agent": "Review test coverage for the given unit.",
        },
    },
    "stan": {
        "id": "stan",
        "display_name": "Stan",
        "file_extension": ".stan",
        "is_component_only": True,
        "compatible_hosts": ["r", "python"],
        "stub_generator_key": "stan_template",
        "quality_runner_key": "stan_syntax_check",
        "required_dispatch_entries": ["stub_generator_key", "quality_runner_key"],
        "bridge_libraries": {},
    },
}


# ---------------------------------------------------------------------------
# Required key sets
# ---------------------------------------------------------------------------

# FULL_REQUIRED_KEYS: all keys present in a full-language entry
FULL_REQUIRED_KEYS: Set[str] = {
    "id",
    "display_name",
    "file_extension",
    "source_dir",
    "test_dir",
    "test_file_pattern",
    "toolchain_file",
    "environment_manager",
    "test_framework",
    "version_check_command",
    "stub_sentinel",
    "stub_generator_key",
    "test_output_parser_key",
    "quality_runner_key",
    "is_component_only",
    "compatible_hosts",
    "bridge_libraries",
    "collection_error_indicators",
    "authorized_write_dirs",
    "default_delivery",
    "default_quality",
    "valid_linters",
    "valid_formatters",
    "valid_type_checkers",
    "valid_source_layouts",
    "environment_file_name",
    "project_manifest_file",
    "gitignore_patterns",
    "entry_point_mechanism",
    "quality_config_mapping",
    "non_source_embedding",
    "agent_prompts",
}

# COMPONENT_REQUIRED_KEYS: subset of FULL_REQUIRED_KEYS for component-only
# entries, minus full-language-only keys, plus required_dispatch_entries.
_FULL_LANGUAGE_ONLY_KEYS: Set[str] = {
    "source_dir",
    "test_dir",
    "test_file_pattern",
    "toolchain_file",
    "environment_manager",
    "test_framework",
    "version_check_command",
    "stub_sentinel",
    "test_output_parser_key",
    "collection_error_indicators",
    "authorized_write_dirs",
    "default_delivery",
    "default_quality",
    "valid_linters",
    "valid_formatters",
    "valid_type_checkers",
    "valid_source_layouts",
    "environment_file_name",
    "project_manifest_file",
    "gitignore_patterns",
    "entry_point_mechanism",
    "quality_config_mapping",
    "non_source_embedding",
    "agent_prompts",
}

COMPONENT_REQUIRED_KEYS: Set[str] = (FULL_REQUIRED_KEYS - _FULL_LANGUAGE_ONLY_KEYS) | {
    "required_dispatch_entries"
}


# ---------------------------------------------------------------------------
# Public functions
# ---------------------------------------------------------------------------


def get_language_config(language: str) -> Dict[str, Any]:
    """Return a deep copy of the registry entry for *language*.

    Raises KeyError with a descriptive message if the language is not
    registered.
    """
    if language not in LANGUAGE_REGISTRY:
        raise KeyError(f"Unknown language: {language}")
    return copy.deepcopy(LANGUAGE_REGISTRY[language])


def validate_registry_entry(entry: Dict[str, Any]) -> List[str]:
    """Validate a full-language registry entry.

    Returns a list of violation strings (empty if valid).
    """
    errors: List[str] = []

    # Check each required key individually
    entry_keys = set(entry.keys())
    for key in sorted(FULL_REQUIRED_KEYS):
        if key not in entry_keys:
            errors.append(f"Missing required key: {key}")

    # Check default_delivery fields
    if "default_delivery" in entry:
        dd = entry["default_delivery"]
        required_delivery_fields = {
            "environment_recommendation",
            "dependency_format",
            "source_layout",
            "entry_points",
        }
        missing_delivery = required_delivery_fields - set(dd.keys())
        for field in sorted(missing_delivery):
            errors.append(f"default_delivery missing field: {field}")

    # Check default_quality fields
    if "default_quality" in entry:
        dq = entry["default_quality"]
        required_quality_fields = {"linter", "formatter", "type_checker", "line_length"}
        # Python entries also require import_sorter
        if entry.get("id") == "python":
            required_quality_fields.add("import_sorter")
        missing_quality = required_quality_fields - set(dq.keys())
        for field in sorted(missing_quality):
            errors.append(f"default_quality missing field: {field}")

    return errors


def validate_component_entry(entry: Dict[str, Any]) -> List[str]:
    """Validate a component-only registry entry.

    Returns a list of violation strings (empty if valid).
    """
    errors: List[str] = []

    # Check each component required key individually
    entry_keys = set(entry.keys())
    for key in sorted(COMPONENT_REQUIRED_KEYS):
        if key not in entry_keys:
            errors.append(f"Missing required key: {key}")

    # Check is_component_only is True
    if "is_component_only" in entry and entry["is_component_only"] is not True:
        errors.append("is_component_only must be True for component entries")

    # Check compatible_hosts is non-empty
    if "compatible_hosts" in entry and len(entry["compatible_hosts"]) == 0:
        errors.append("compatible_hosts must be non-empty for component entries")

    # Check required_dispatch_entries
    if "required_dispatch_entries" in entry:
        rde = entry["required_dispatch_entries"]
        if not isinstance(rde, list) or len(rde) == 0:
            errors.append(
                "required_dispatch_entries must be a non-empty list of strings"
            )
        elif not all(isinstance(item, str) for item in rde):
            errors.append("required_dispatch_entries must contain only strings")

    return errors


def load_registry_extensions(extensions_path: str) -> Dict[str, Dict[str, Any]]:
    """Load language registry extensions from a JSON file.

    Reads ``language_registry_extensions.json`` from the given path.
    Returns an empty dict if the file does not exist.
    """
    file_path = os.path.join(extensions_path, "language_registry_extensions.json")
    if not os.path.isfile(file_path):
        return {}
    with open(file_path, "r") as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Import-time validation
# ---------------------------------------------------------------------------


def _validate_registry_at_import() -> None:
    """Validate all built-in registry entries at import time."""
    for lang_key, entry in LANGUAGE_REGISTRY.items():
        if entry.get("is_component_only", False):
            errs = validate_component_entry(entry)
            if errs:
                raise ValueError(
                    f"Component registry entry '{lang_key}' is invalid: "
                    + "; ".join(errs)
                )
        else:
            errs = validate_registry_entry(entry)
            if errs:
                raise ValueError(
                    f"Full-language registry entry '{lang_key}' is invalid: "
                    + "; ".join(errs)
                )


_validate_registry_at_import()
