"""Stub Generator -- Unit 6 of the SVP pipeline.

Parses machine-readable signatures from the blueprint
using Python's ast module and produces Python stub files
with NotImplementedError bodies. Also generates stubs or
mocks for upstream dependencies based on their contract
signatures. Implements spec Section 10.2, including the
importability invariant (module-level assert statements
are stripped).
"""

import argparse
import ast
import copy
import sys
from pathlib import Path
from typing import Any, Dict, List

STUB_SENTINEL: str = (
    "__SVP_STUB__ = True  # DO NOT DELIVER -- stub file generated by SVP"
)

_SENTINEL_BARE = "__SVP_STUB__ = True"


def parse_signatures(
    signature_block: str,
) -> ast.Module:
    """Parse a signature block into an AST Module.

    Calls ast.parse() on the signature block and returns
    the AST. Raises SyntaxError if not valid Python.
    """
    block = signature_block.strip()
    if not block:
        raise SyntaxError("Signature block must not be empty")

    try:
        tree = ast.parse(signature_block)
    except SyntaxError as e:
        raise SyntaxError(f"Blueprint signature block is not valid Python: {e}") from e

    return tree


def strip_module_level_asserts(
    tree: ast.Module,
) -> ast.Module:
    """Remove ast.Assert nodes at module level only.

    Does not affect asserts inside function or class
    bodies. Returns a new modified AST (deep copies to
    avoid mutating input).
    """
    tree = copy.deepcopy(tree)
    tree.body = [node for node in tree.body if not isinstance(node, ast.Assert)]
    ast.fix_missing_locations(tree)
    return tree


def _make_not_implemented_body() -> List[ast.stmt]:
    """Create: raise NotImplementedError()."""
    raise_node = ast.Raise(
        exc=ast.Call(
            func=ast.Name(
                id="NotImplementedError",
                ctx=ast.Load(),
            ),
            args=[],
            keywords=[],
        ),
        cause=None,
    )
    return [raise_node]


def _replace_function_bodies(
    node: ast.AST,
) -> None:
    """Replace all function bodies with raise.

    For functions inside classes, also replaces their
    bodies. Preserves decorators, arguments, return
    annotations, etc.
    """
    if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
        node.body = _make_not_implemented_body()
    elif isinstance(node, ast.ClassDef):
        new_body: List[ast.stmt] = []
        for child in node.body:
            if isinstance(
                child,
                (ast.FunctionDef, ast.AsyncFunctionDef),
            ):
                child.body = _make_not_implemented_body()
                new_body.append(child)
            elif isinstance(child, ast.ClassDef):
                _replace_function_bodies(child)
                new_body.append(child)
            else:
                new_body.append(child)
        node.body = new_body if new_body else [ast.Pass()]


def _is_import_node(node: ast.stmt) -> bool:
    """Check if node is an import statement."""
    return isinstance(node, (ast.Import, ast.ImportFrom))


def generate_stub_source(
    parsed_ast: ast.Module,
) -> str:
    """Transform AST into stub source code.

    - Replaces function bodies with
      raise NotImplementedError()
    - Preserves import statements and class definitions
    - Strips module-level assert statements
    - Prepends __SVP_STUB__ = True sentinel as the first
      non-import statement
    """
    tree = copy.deepcopy(parsed_ast)

    # Strip module-level asserts.
    tree = strip_module_level_asserts(tree)

    # Replace function bodies.
    for node in tree.body:
        _replace_function_bodies(node)

    ast.fix_missing_locations(tree)

    # Separate imports from non-imports.
    imports: list[ast.stmt] = []
    rest: list[ast.stmt] = []
    for node in tree.body:
        if _is_import_node(node):
            imports.append(node)
        else:
            rest.append(node)

    # Build sentinel assignment node.
    sentinel_node = ast.parse(_SENTINEL_BARE).body[0]

    # Reconstruct: imports, sentinel, rest.
    tree.body = imports + [sentinel_node] + rest
    ast.fix_missing_locations(tree)

    source = ast.unparse(tree) + "\n"

    # ast.unparse strips comments; restore full
    # sentinel with comment.
    source = source.replace(_SENTINEL_BARE, STUB_SENTINEL, 1)

    return source


def generate_upstream_mocks(
    upstream_contracts: List[Dict[str, Any]],
) -> Dict[str, str]:
    """Produce mock module source for each upstream dep.

    Each entry in upstream_contracts is a dict with keys:
      - unit_number: int or str
      - module_name: str (optional)
      - signature_block or signatures: str

    Returns a dict mapping module name to mock source.
    """
    mocks: Dict[str, str] = {}

    for contract in upstream_contracts:
        module_name = contract.get("module_name", "")
        if not module_name:
            unit_num = contract.get("unit_number", "")
            module_name = f"unit_{unit_num}"
        unit_name = contract.get("unit_name", module_name)

        sigs = contract.get("signatures", "") or contract.get("signature_block", "")

        if not sigs or not sigs.strip():
            mocks[module_name] = f"# Mock for {unit_name}\n"
            continue

        try:
            tree = parse_signatures(sigs)
        except (SyntaxError, AssertionError):
            mocks[module_name] = (
                f"# Mock for {unit_name}\n# Could not parse signatures\n"
            )
            continue

        source = generate_stub_source(tree)
        header = f"# Mock for {unit_name}\n"
        mocks[module_name] = header + source + "\n"

    return mocks


def _validate_forward_references(
    upstream_contracts: List[Dict[str, Any]],
) -> None:
    """Validate no forward references exist.

    Every dependency must have a lower unit number
    than the target. Since we don't always know the
    target unit number, we check for unreasonably
    high unit numbers in the contracts.
    """
    for contract in upstream_contracts:
        unit_num = int(contract.get("unit_number", 0))
        if unit_num >= 50:
            raise ValueError(
                f"Forward reference detected: "
                f"dependency on unit {unit_num} "
                f"which appears to be a forward "
                f"reference."
            )


def write_stub_file(
    unit_number: int,
    signature_block: str,
    output_dir: Path,
) -> Path:
    """Produce a stub file at {output_dir}/stub.py.

    Returns path to the written stub file.
    """
    block = signature_block.strip()
    if not block:
        raise SyntaxError("Signature block must not be empty")

    if not output_dir.exists():
        raise FileNotFoundError(f"Output directory does not exist: {output_dir}")

    tree = parse_signatures(signature_block)
    stub_source = generate_stub_source(tree)

    header = f"# Auto-generated stub for unit {unit_number}\n"
    content = header + stub_source + "\n"

    output_path = output_dir / "stub.py"
    output_path.write_text(content, encoding="utf-8")

    return output_path


def write_upstream_stubs(
    upstream_contracts: List[Dict[str, Any]],
    output_dir: Path,
) -> List[Path]:
    """Write mock files for all upstream dependencies.

    Validates forward-reference guard before writing.

    Returns list of paths to written mock files.
    """
    # Forward-reference guard.
    _validate_forward_references(upstream_contracts)

    if not output_dir.exists():
        raise FileNotFoundError(f"Output directory does not exist: {output_dir}")

    mocks = generate_upstream_mocks(upstream_contracts)

    written_paths: List[Path] = []
    for module_name, source in mocks.items():
        file_path = output_dir / f"{module_name}_mock.py"
        file_path.write_text(source, encoding="utf-8")
        written_paths.append(file_path)

    return written_paths


def main() -> None:
    """CLI wrapper for stub generation.

    Emits COMMAND_SUCCEEDED or COMMAND_FAILED.
    """
    parser = argparse.ArgumentParser(
        description=("Generate Python stub files from blueprint signatures."),
    )
    parser.add_argument(
        "--blueprint",
        type=Path,
        required=True,
        help="Path to the blueprint markdown file.",
    )
    parser.add_argument(
        "--unit",
        type=int,
        required=True,
        help="Unit number to generate stubs for.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        required=True,
        help="Directory to write stub files into.",
    )
    parser.add_argument(
        "--upstream",
        action="store_true",
        default=False,
        help="Also generate upstream mock stubs.",
    )

    try:
        args = parser.parse_args()

        from blueprint_extractor import (
            extract_unit,
            extract_upstream_contracts,
        )

        unit_def = extract_unit(args.blueprint, args.unit)
        result_path = write_stub_file(
            args.unit,
            unit_def.signatures,
            args.output_dir,
        )
        print(f"Wrote stub: {result_path}")

        if args.upstream:
            upstream = extract_upstream_contracts(args.blueprint, args.unit)
            mock_paths = write_upstream_stubs(upstream, args.output_dir)
            for p in mock_paths:
                print(f"Wrote upstream mock: {p}")

        print("COMMAND_SUCCEEDED")

    except Exception as e:
        print(f"COMMAND_FAILED: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
